- code/controllers/configuration/entries/general.dm
- code/modules/mob/living/silicon/robot/robot.dm
- config/entries/general.txt
На данный момент отсутствие боргов в секурити - лишает нас просто тонны вкусного нонкона. Поэтому было принято решение вернуть боргам возможность с начала игры выбирать модуль секурити. 
Думал сначала просто анкомитнуть строчку, но решил сделать правильнее и добавил настройку в конфиг. 
Чтобы заработало - нужно в конфиге анкоммитнуть строчку байпасса. 
Следовательно в конфиге General строчку - #BYPASS_SECBORG_CODE изменить в BYPASS_SECBORG_CODE
Это можно даже коммитнуть на оригинальный Сплюрт, но не думаю, что им это нужно.
> Конфиг на байпасс янтарного кода у боргов

- _maps/map_files/BoxStation/BoxStation.dmm
- _maps/map_files/CogStation/CogStation.dmm
- _maps/map_files/Deltastation/DeltaStation2.dmm
- _maps/map_files/FestiveBall/FestiveStation.dmm
- _maps/map_files/KiloStation/KiloStation.dmm
- _maps/map_files/MetaStation/MetaStation.dmm
- _maps/map_files/OmegaStation/OmegaStation.dmm
- _maps/map_files/PubbyStation/PubbyStation.dmm
- _maps/map_files/TauStation/TauStation.dmm
Изменения в карте сделаны по запросу на добавление спавнеров оружия в шкафчик с контрабандой (там, куда некуда было втулить шкафчик с контрабандой, запихнула в шкафчик с летальной аммуницией). Плюс ещё сверху перенесла на некоторые карты особые дормы с синдистейшена (космическую, ксено и тропическую комнаты)
Чейнджлог:
Cogstation
3 спавнера контрабандного оружия (в шкафчике с летальной аммуницей)
Boxstation
3 спавнера контрабандного оружия + дормы
Deltastation:
4 спавнера контрабандного оружия 
Festivestation:
3 спавнера контрабандного оружия 
Kilostation
3 спавнера контрабандного оружия (в шкафчике с летальной аммуницей)
Metastation
Дормы
Omegastation
4 спавнера контрабандного оружия
Pubbystation
3 спавнера контрабандного оружия
TauStation
3 спавнера контрабандного оружия
> Map impovement #1

- code/modules/mob/living/emote.dm
Снижение дальности распространения звука удушья вокруг до 3 тайлов, а также громкости.
https://discord.com/channels/875735187449847830/1058665181523218562/1058665181523218562 - апрув.
За 2 экранами от персонажа не будет слышно на полную громкость, как он задыхается. В условных техах всё ещё можно различить звук, если жертва лежит в нычке роли или неподалёку от стены.
:cl: SishTis
balance: Дальность распространения звука удушья уменьшена до 3 тайлов вокруг персонажа.
/:cl:
> Уменьшаем радиус распространения звука удушья

- code/modules/spells/spell_types/lichdom.dm
Маг-лич из-за бага после смерти спавнился из филактерии не скелетом, а человеком-невидимкой. Теперь всё работает как задумывалось.
:cl:
fix: fixed lich phylactery respawn
/:cl:
> Lich phylactery fix (again)

- code/datums/brain_damage/severe.dm
Монофоб не умерает в воре желудке и слепой монофоб не умерает если кто-то (подходящий под критерии) находится в 1 тайле от него)
Окей это мне уже 2 раза рп поломало, заебало. Слепые монофобы в принципе только умерают (у них нет спасения от этого)
https://github.com/tgstation/tgstation/pull/72829
https://github.com/Sandstorm-Station/Sandstorm-Station-13/pull/289
https://github.com/SPLURT-Station/S.P.L.U.R.T-Station-13/pull/701
Да, я гениален
:cl: Winter Schock
fix: Doll with monophobia dont get stress in someone vore belly 
fix: Blind doll with monophobia dont get stress while someone in 1 tile range 
/:cl:
>  monophobia blind fix

- tgui/packages/tgui/interfaces/Changelog.js
:cl:
fix: исправлено, что чеинжлоги за последние два месяца не показывались
/:cl:
> фикс дубликат кеев в ямле для чеинжлога

- code/controllers/subsystem/vote.dm
Включена возможность просмотра голосов за карту или за режим в процессе и в конце голосования.
В плане режима - точно видно, что интересно игрокам на данный момент в точном соотношении. Меньше нытья со стороны любителей одной из сторон и больше осознанности, если воут примерно 50/50.
Для карты - возможность сплотиться вокруг одной, когда выигрывает та, что не хочет никто.
✅ Теперь игроки видят количество голосов за режим или за карту в процессе голосования.
> Игроки могут видеть голоса за режим или за карту

- code/controllers/subsystem/ticker.dm
Теперь время для воута за режим (динамик/экста) - время до начала раунда (минус) 20 секунд.
Больше времени для того, чтобы зайти и успеть проголосовать.
✅ Игра теперь даёт практически всё время до начала игры для голосования за режим (динамик или эксту).
> Зависимость времени голосования за режим от времени до начала игры

- code/__BLUEMOONCODE/_DEFINES/time.dm
- code/__DEFINES/time.dm
- code/controllers/subsystem/statpanel.dm
- tgstation.dme
Всё в шапке.
Sol System Time - старое Station Time
https://discord.com/channels/875735187449847830/1083742509114601492/1083742509114601492
Sol System Time - довольно милое ролевое дополнение, на мой взгляд. Показывает, что время в аномальном секторе течёт иначе.
✅ Station Time теперь идёт с такой же скоростью, что и настоящее.
✅ Добавлено Sol System Time в основную вкладку. По сути старое Station time, показывает время в Солнечной Системе.
> Station time идёт с такой же скоростью, что и настоящее + Sol System Time

- code/game/machinery/announcement_system.dm
Было: 
```
[Common] Автоматизированная Система Оповещений холодно констатирует, "Боб Клувня прибывает на станцию как Clown"
[Common] Автоматизированная Система Оповещений холодно констатирует, "Боб Клувня, Clown, был(-а) телепортирован(-а) на Аванпост Центрального Командования."
```
Стало:
```
[Common] Автоматизированная Система Оповещений холодно констатирует, "Боб Клувня, Clown, прибывает на станцию."
[Common] Автоматизированная Система Оповещений холодно констатирует, "Боб Клувня, Clown, телепортируется на аванпост ЦК."
```
Мне кажется, что так выглядит благозвучнее.
1) Отсутствуют скобочки, которые в нормальной речи выделить тяжело и неприятно для уха.
2) Сокращена длина сообщений, повышая смысловую часть и убирая воду.
3) "Прибывает на станцию как..." - странное сочетание, на мой …
> Изменение сообщения о прибытии/отбытии со станции

- code/modules/client/preferences.dm
Под пунктом гетерохронии вручную указаны глаза, у которых в спрайтах есть особый визуальный стиль при включенной гетерохронии.
Гетерохрония у этих глаз - неочевидная фича, которую большинство явно не планирует использовать. Возможно, такое выделение поможет выбрать что-то новое.
Сравнение до:
<details>
</details>
И после (обращать внимание на пункт гетерохронии):
<details>
</details>
> Подписываем глаза с особой геторохронией

- code/game/objects/items/cards_ids.dm
- modular_bluemoon/station_agents_cards/cards_id.dm
- modular_citadel/code/modules/client/loadout/__donator.dm
- tgstation.dme
Всё в шапке.
Убираем возможность у карт агентов из лодаута воровать доступ со станционных карт.
Причины следующие:
1) Вещь из лодаута влияет на игровой баланс + находится за пэйволом (каким бы он ни был). Это выглядит мерзко.
2) Доступ клянчат. Его дают. Ценность ГП падает.
Самые дружелюбные члены экипажа спокойно клянчат карты у отделов, чтобы получать себе аналог полного доступа. По итогу появляются различные ниндзи синдиката в шахтёрском МОДе с убер-скоростью из-за химикатов, которые сами же варят. И никак доступ их в этом не останавливает, т.к. 1 из 4 сотрудников в отделе точно окажется достаточно услужливым. Самое печальное, что этим пользуются достаточно робастные игроки, чтобы получать дополнительное преимущество на случай проблем - например, эту карту можно брать в динамик и …
> Убираем у карт агентов из лодаута возможность забирать доступ

- code/game/machinery/dance_machine.dm
- code/modules/client/preferences.dm
- code/modules/client/preferences_savefile.dm
Добавляет в преференсы опцию танца около дискошара.
По умолчанию опция включена, но шарящие, а также особо жаждающие прекратить этот эппилептический припадок своего персонажа смогут наконец выключить это
> Add ability to not dance at disco

- _maps/RandomRuins/SpaceRuins/BlueMoon/space_syndicate_base.dmm
Там не хватает провода и постоянно вручную класть приходится. Так не придётся.
> Add missed wire to DS2 away site

- _maps/RandomRuins/SpaceRuins/BlueMoon/space_syndicate_base.dmm
Коноль не может подключиться без пересборки ибо у неё прописан `id`. А турбина по умолчанию не собрана, поэтому `id` только мешает, а не помогает подключиться.
> Fix DS2 turbine console

- code/controllers/subsystem/job.dm
Перед мерджем обязательно выставить в минимальное количество экипажа на skeleton crew таким, как был бы весь онлайн (skeleton crew при менее чем 50 человек по конфигу, например).
> Делаем skeleton crew зависящим от количества игроков на сервере

- code/modules/vending/kinkmate.dm
Убираем sizeray из кинкмата.
1. Это дебаговый инструмент. Он не должен находиться в общем доступе.
2. Он используется для ЛРП целей. Персонажам повышают размер до 800% без их согласия (или наоборот, снижают). Защиты от этого нет.
3. По механу, это лазер капитана (сам себя заряжает). Можно так грифонить всю станцию/бар.
Я делаю отдельный тул, который не будет иметь этих недостатков. Он будет идти в отдельном ПРе.
Меньше LRP.
> Убираем sizeray из кинкмата

- code/modules/mob/living/carbon/human/examine.dm
- code/modules/mob/living/carbon/human/human.dm
1. Убран дубликат накед флейвора, ибо если он виден, то он отображается как в старом виде - белым окном, так и в новом тгуи окошке
2. Окно флейвора можно теперь открыть всегда. Надевание маски хендлится через код отправки данных, так что нет необходимости не давать возможности открыть профиль. Тем более он содержит OOC Заметки, которые должны быть видны всегда.
Ну а ещё прошлый вариант мог бы легко абузиться открытием окна флейвора до того как маска надета. И после того как маску надел игрок, окно бы осталось открытым. Теперь это не баг, а фича.
> Profile fixes

- code/modules/clothing/spacesuits/plasmamen.dm
Теперь тождественны visor_flags_inv. Флаворы плазмаменов снова можно смотреть.
> Изменяем flags_inv плазмамена

- code/game/objects/items/plushes.dm
Теперь ручка не будет рвать плюшевые игрушки, а будет переименовывать их. Любите своих плюшевых друзей <3
> Ручка и плюшевые игрушки

- code/game/objects/items/plushes.dm
Жмаканье плюшевых игрушек показывает сердечки и теперь видно другим.
> Жмак-жмак плюшевые игрушки

- code/__DEFINES/traits.dm
- code/datums/mood_events/generic_positive_events.dm
- code/game/sound.dm
- modular_bluemoon/code/datums/traits/neutral.dm
- modular_citadel/code/modules/mob/cit_emotes.dm
- modular_splurt/code/modules/mob/living/emotes.dm
- modular_splurt/code/modules/mob/living/silicon/emotes.dm
- tgstation.dme
Нейтральный квирк, обладатели которого изредка непроизвольно воют. Также если обладатель квирка услышал чужой вой, то он сам начнет выть. Также вой слегка поднимает мораль обладателям квирка. 
(Квирк вдохновлен дефолтной механикой вульп с парадиза, которые воют по цепочке, если хотя бы одна из них завыла, так что чем больше народу возмет данный квирк, тем эффектнее он будет выглядеть)
> Новый квирк: Бесконтрольный вой

- code/modules/arousal/arousal.dm
- code/modules/arousal/genitals.dm
- code/modules/mob/living/carbon/human/examine.dm
- modular_splurt/code/game/objects/items/lewd_items/genital_equipment/chastity/chastity_belt.dm
- modular_splurt/code/game/objects/items/lewd_items/genital_equipment/chastity/metal_chastity_cage.dm
Массивный фикс различных багов и недоработок связанных с клетками для гениталий: 
- фикс багов со снятием клетки;
- фикс отображений сообщений у женщин;
- теперь для снятия пояса необходим ключ (логично);
- теперь скрытые под одеждой гениталии не рассказывают о том, что они находятся взаперти всем подряд при осмотре игрока.
P.S.: я бля бы этим говнокодерам жопу пожал за конченные нестандартные реализации стандартных действий по типу "хотите научиться нестандартно срать?" или как в том анекдоте про "унитаз на потолке".
> Фикс клеток и поясов

- modular_sand/code/game/objects/items/fleshlight.dm
1) портальные трусики имели русское название, но только до момента первого смены "цели" у них, теперь постоянно
2) портальные трусики давали дебафф к настроению у нудистов (ну и впринципе нет смысла скрывать пах только одними портальными трусиками)
> Портальные трусики всегда на русском, а ещё для нудистов не закрывают пах

- modular_splurt/code/game/objects/items/lewd_items/genital_equipment/condom.dm
Пустые презики ничего не расплескивают. Разрабы сплюрта за 16 месяцев не догадались добавить одну проверку на 25 символов для фикса проблемы.
> Фикс презиков

- code/__HELPERS/priority_announce.dm
- code/modules/reagents/chemistry/reagents/other_reagents.dm
- modular_sand/code/modules/keybindings/keybind/carbon.dm
- modular_splurt/code/modules/food_and_drinks/recipes/drink_recipes.dm
- modular_splurt/code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
- Теперь кнопка отображения предмета в руке имеет дефолтный бинд "Shift+G" (я искренне надеюсь, что это не изменит бинд у тех, у кого уже стоят другие кнопки на данную команду). 
- Секретные станционные объявления теперь имеют более подходящую озвучку. 
- Напиток "Boy Kisser" теперь имеет однозначное название ("Twink Juice" тоже неплохое название, но у вещества оно должно быть только одно, иначе шиза). 
- И напиток "Moon Sugar" теперь имеет достойное название и описание.
> Немножко изменений

- code/datums/emotes.dm
- code/modules/mob/living/carbon/human/emote.dm
- modular_splurt/code/modules/mob/living/emotes.dm
- modular_splurt/code/modules/mob/living/silicon/emotes.dm
Виляние хвостом это эмоут, и оно учитывало КД на эмоуты = ломало механику автовиляния. Теперь нет.
P.S.: Кодеры теперь точечно смогут ставить флаг игнора кд нужным им эмоутам.
> Фикс автовиляния хвостом

- code/game/machinery/computer/camera.dm
- code/modules/modular_computers/file_system/programs/secureye.dm
Незначительная проверка для камер. Она ничего не решает, но паранойя говорит "надо".
> Микропроверка

- code/game/objects/items/devices/radio/radio.dm
- modular_bluemoon/bigtalk/bigtalk.dm
У больших персонажей (и маленьких) есть SPAN_BIG или SPAN_SMALL при общении. Он ломал большой текст в радио-канал при попытке писать от лица большого персонажа, оставляя его обычным.
> Фикс командной частоты для персонажей с нестандартным размером

- code/__HELPERS/type2type.dm
- code/game/objects/items/clown_items.dm
- code/modules/arousal/organs/breasts.dm
- code/modules/arousal/organs/butt.dm
- code/modules/arousal/organs/penis.dm
- code/modules/arousal/organs/testicles.dm
- code/modules/arousal/organs/vagina.dm
- code/modules/mob/living/carbon/human/examine.dm
- code/modules/paperwork/pen.dm
- code/modules/surgery/organs/organ_internal.dm
- modular_splurt/code/game/objects/structures/watercloset.dm
- modular_splurt/code/modules/paperwork/pen.dm
Исправлено множество косяков в коде.
1. Теперь, надписи на теле с отдельных конечностей отображаются только, если видны эти самые конечности, а не при условии, что на цели открыта грудь.
2. Нет больше "На его chest написано: [...]". Корректно переведено.
3. Можно писать на отдельных конечностях, а не только когда открыта грудь.
4. Надписи на теле можно убирать с помощью мыла.
5. В описание мыла и ручки добавлены нужные примечания, что можно делать этими предметами.
> Множество исправлений возможности писать на частях тела

- code/modules/power/lighting.dm
Если лампочка смотрит "вниз", то она отображается позади персонажа.
[Тема](https://discord.com/channels/875735187449847830/1162339181159252018/1162339181159252018)
:cl:
qol: quality of …
> Если лампочка смотрит вниз - то она находится "под" персонажем.

- code/_rendering/atom_huds/data_huds.dm
- code/datums/components/storage/concrete/pockets.dm
- code/game/gamemodes/bloodsucker/bloodsucker.dm
- code/game/machinery/computer/crew.dm
- code/game/machinery/porta_turret/portable_turret.dm
- code/game/objects/items/pinpointer.dm
- code/game/objects/items/storage/wallets.dm
- code/modules/antagonists/bloodsucker/bloodsucker_objectives.dm
- code/modules/clothing/neck/_neck.dm
- code/modules/jobs/access.dm
- code/modules/mob/living/carbon/human/human.dm
- code/modules/mob/living/carbon/human/human_helpers.dm
- code/modules/mob/living/carbon/human/inventory.dm
- code/modules/mob/living/carbon/human/say.dm
- code/modules/mob/living/carbon/inventory.dm
- code/modules/mob/living/silicon/robot/robot.dm
- code/modules/modular_computers/file_system/programs/radar.dm
- code/modules/newscaster/newscaster_machine.dm
- code/modules/research/nanites/nanite_programs/utility.dm
- modular_bluemoon/SmiLeY/venicle/spacepods/spacepod.dm
- modular_sand/code/datums/elements/holder_micro.dm
- modular_splurt/code/datums/components/storage/concrete/pockets.dm
- ID карты теперь можно полноценно носить в ошейниках/чокерах/etc (кроме особых ошейников по типу работоргевцев).
- При осмотре персонажа с ID картой в кошельке будет выводиться информация на карте (с ошейниками тоже самое).
- Фикс проблемы смены СБ худов с картой в кошельке.
> ID карты в ошейниках и улучшение кошельков

- code/modules/antagonists/wizard/equipment/spellbook.dm
МЫ ДЕЛЕГАЛИЗОВАЛИ ЯДЕРНЫЕ БОМБЫ (в эксту)
ну и теперь призыв гостов требует 60 опасности
> заклинания привязанные к уровню угрозы динамика нельзя юзать в эксту

- code/game/machinery/porta_turret/portable_turret.dm
- modular_bluemoon/kovac_shitcode/code/modules/antagonists/raiders.dm
Турели Синдиката теперь не будут стрелять по владельцам ID карт Синдиката, даже если они не принадлежат данной фракции (главное носить их на видном месте).
> Турели Синдиката и карты

- code/modules/mob/living/carbon/human/innate_abilities/customization.dm
Убирает возможность изменять размер персонажа через упомянутый квирк.
Причины:
1. Квирк нейтральный и даёт при этом существенное преимущество в связи со следующими пунктами.
2. Размер персонажа влияет на ход боя - больше спрайт, больше ХП, возможность задавить (со сверхтяжёлым, ещё и с дополнительными бафами). Это не косметическое изменение, которым оно является на сплюрте. Более того, не соответствует тематике сервера с гибридностью.
3. Изменение происходит мгновенно, позволяя обойти ограничения нормалайзера (скорость надевания, занерфленную для баланса применения размера в бою).
4. В конце-концов, квирк не выглядит как что-то, что должно давать возможность кардинально изменять свой подход к бою.
5. Bug: при изменении размера через квирк, нанесенный персонажу урон не изменяется.
Баланс.
> Убираем возможность изменять размер персонажа через нейтральный квирк "изменятель тела"

- code/modules/food_and_drinks/drinks/drinks/drinkingglass.dm
Опустошенные стаканы возвращают свое прежнее название.
> Фикс названий пустых стаканов

- code/modules/mob/living/carbon/human/human.dm
- code/modules/movespeed/modifiers/mobs.dm
- modular_sand/code/game/objects/items/robot/robot_upgrades.dm
- modular_splurt/code/modules/mob/living/living_signals.dm
1. У всех living мобов появился боевой индикатор. Теперь киборги его имеют в т.ч., что позволяет применять к ним соответствующие части правил.
2. Модули expand для киборгов теперь дают умеренное замедление. Замедление от модуля shrink слегка усилено.
> Боевой индикатор всем living мобам, а также замедление от модулей expand и shrink для киборгов

- modular_sand/code/game/objects/items/fleshlight.dm
- modular_sand/code/modules/vending/kinkmate.dm
- По заявкам телезрителей была реализована возможность коннектить несколько портальных фонариков к одним портальным трусам. Хоть 10 штук сразу. 
- Теперь портальные фонарики можно "отвязывать" от трусов по аналогии с "привязыванием".
- В розовых автоматах можно купить портальные трусы и фонарики по отдельности.
> Портальные трусы: один ко многим.

- code/modules/client/preferences_savefile.dm
Everything in title.
sanitize_integer makes the target number round itself, which doesn't fit the case and returns default number (which is 0.25).
Replaced the proc with sanitize_num_clamp, which does the same and doesn't round.
Smiley, maybe you ough to send it to splurt also.
> Penis girth now saves itself

- code/__DEFINES/dcs/signals.dm
- code/modules/mob/living/living_movement.dm
- modular_sand/code/datums/components/riding.dm
Теперь катания на спинках правильно обрабатывают отображение слоев и позиций спрайтов персонажей при разворотах.
> Фикс покатушек на спинке

- code/modules/mob/living/simple_animal/hostile/headcrab.dm
- Хедкрабы при паунсе на голову должны убивать цель и зомбировать её. Т.к. зомбирование происходило слишком рано, цель была технически жива и **находясь внутри зомби**, начинала бить его оружием, чтобы снять с себя зомбификацию.
- Этот фикс заставляет цель умирать после того, как хедкраб её зомбифицирует.
> Фикс хедкрабов

- code/__SANDCODE/DEFINES/sizecode.dm
- modular_bluemoon/size_tool/size_tool.dm
- modular_sand/code/modules/resize/sizechems.dm
- Максимальный размер, доступный для повышения размера персонажа, 300%, а не 600% (3 тайла в высоту против 6).
- Слегка изменено описание у size tool для большей наглядности и раскрытия механик. Осуждаю девелопера, что убирал это.
> Обновление для heigh medipen

- code/datums/traits/good.dm
Окей, это не в полевых ситуациях сервера не проверить, но если проще для понимания зачем
ночное зрение работает, но есть один плот твист в том, что он работает только после обновления зрения
на сервере из-за большого пролага это обновление зрения не срабатывает и челам с ночным зрением нужно сперва обновить его (нацепить пожарным шлем) и тогда всё заработает.
поэтому ВТЕОРИИ этот фикс решает проблему с ночным зрением (сколько локалка из-за отсутствия пролага так и так работает)
> Возможный фикс ночного зрения

- code/modules/vehicles/mecha/mecha_defense.dm
Теперь при попытке ремонтировать мех сваркой пилоту будет выводиться сообщение, что он не может добраться до повреждённого оборудования изнутри.
_P.S. Возможно, есть другое решение проблемы, но пока сгодится и такое_
:cl:
fix: Убрана возможность ремонтировать мехи сваркой изнутри
/:cl:
> Убрал возможность варить мех сваркой изнутри

- _maps/RandomRuins/SpaceRuins/BlueMoon/space_syndicate_base.dmm
Внес небольшие изменения в ДС2, для удобства играющих там.
Изменения:
- В двух каютах заменены кровати и одеяла на двойные. Чтобы партнер не падал лишний раз на пол
- Машинфрейм и плата мехфаба переместилась ближе к РнД консоли, по причине невозможности подключения. Если ученый не идет к горе, то гора идет к ученому.
- В помещение турбины, к платам поставлены раундстартовые машинфреймы. На один шаг меньше для постройки источника энергии.
- В каюту  corporate liaison-а добавлен фотокопер заместо одного из столов. Больше документов богу документов.
Все изменения проверены и протестированы локально. Скриншоты прилагаются
> maptweak(DS2) Мелкоизменения карты для удобства

- code/game/machinery/dance_machine.dm
- code/game/machinery/dance_machine_handled.dm
- tgui/packages/tgui/interfaces/Jukebox.js
добавлена кнопка повтора около кнопки включения-выключения (работает при наличии доступа (бармена чаще всего) или 0 стоимости жукбокса (инф дормы)
каждый раз трек отправляется в конец списка, тоесть поддерживается ротация нескольких песен раз за разом по очереди
> Режим повтора плейлиста для жукбокса

- code/modules/mob/living/carbon/human/innate_abilities/customization.dm
возврат возможности изменить размер персонажа, работает вдвое дольше сайз тула (на 25 процентов роста нужно по 10 секунд), в наручниках изменить размер нельзя.
> Возврат изменения размера тела изменятелям тела

- code/modules/mob/living/carbon/human/innate_abilities/customization.dm
возврат возможности изменить размер персонажа, работает вдвое дольше сайз тула (на 25 процентов роста нужно по 10 секунд), в наручниках изменить размер нельзя.
> Возврат изменения размера тела изменятелям тела (повтор из-за мерж-конфликтов)

- _maps/map_files/generic/CentCom.dmm
- _maps/templates/apartment.dmm
- _maps/templates/apartment_1.dmm
- _maps/templates/apartment_2.dmm
- _maps/templates/apartment_3.dmm
- _maps/templates/apartment_bar.dmm
- _maps/templates/apartment_sauna.dmm
- _maps/templates/apartment_syndi.dmm
- _maps/templates/hilbertshotel.dmm
все вендоматы (167 так-то штук на цк слое) с начала раунда имеют выключенный динамик, так-же и с вендорами в инфинити отеле, сколько на деле это вообще ничего не привносит, а крайне мешает и, что не удивительно, ещё и засоряет сервер без логичной на то причины.
> Молчат вендора (на цк и инф-отеле)

- modular_bluemoon/vlad0s_staff/code/synth_drinks.dm
В процессе работы над синтонапитками пару недель назад потерялась важная строчка, я её вернул. Теперь напитки не будут применять свои специальные эффекты на органиков.
> Маленький багофикс напитков

- code/game/atoms.dm
- code/modules/clothing/neck/_neck.dm
- code/modules/mob/living/carbon/human/examine.dm
Отображается рядом с именем при осмотре персонажа или наведении курсором.
> Имя на ошейнике

- code/modules/ambitions/ambition_objective.dm
Не все заходящие в игру являются людьми по персонажу, что могло вызывать рантаймы (из-за боргов, дронов и другой дичи, что рантаймит список).
> Фикс амбиций

- code/modules/vending/_vending.dm
А так-же не переводят персонажей в 1д если те были на турфе с боргом в этот момент
> Вендоматы не взрывают боргов при падении

- code/controllers/subsystem/job.dm
- code/datums/mind.dm
- code/datums/traits/negative.dm
Аксессуары и некоторые другие лодаутные предметы, работающие через post_equip не могли делаться реликвиями. Также семейные реликвии, падающие под ногами, становились реликвиями без хозяина.
Пофиксил обе проблемы.
> Фикс лодаутных реликвий

- _maps/map_files/MetaStation/MetaStation.dmm
прямое окно из техов в виро заменено на стену, под некоторыми окнами были добавлены полы.
> meta-viro-maint-windowsfix

- code/modules/mod/mod_clothes.dm
Теперь PCU / ПОУ / Portable Cooling Unit, нужный для существования синтетикам-космонавтам и синтетикам-шахтёрам, можно повесить на нагрудник МОД-сьюта (в самый левый слот инвентаря, если кто не в курсе).
QoL.
> Добавил возможность повесить кулер на МОД

- code/modules/client/preferences.dm
Regex к хэдшотам устарел, дискорд иначе хранит ссылки на изображения.
> Проблемы с установкой артов персов

- code/modules/clothing/under/syndicate.dm
- code/modules/jobs/job_types/research/expeditor.dm
униформы тактикуул (одежды синдиката без брони) имеют датчики (ибо они красивые, но при этом за это приходилось платить лишением брони) (ну и для камо (если нужно - выключат))
униформа экспедитора имеет датчики - они всё ещё станционный персонал и у всех станционных проф должны быть оные
> Датчики на тактикуул униформы и одежду экспедитора

- code/modules/clothing/under/miscellaneous.dm
- modular_sand/code/modules/clothing/under/miscellaneous.dm
- modular_splurt/code/game/objects/items/lewd_items/genital_equipment/condom.dm
- modular_splurt/code/modules/clothing/under/miscellaneous.dm
- tgstation.dme
Главный реворк - появилась возможность цеплять на gear harness заполненные презервативы - прямо как в тех самых артах/хентаях! (можно и пустые, но зачем...) Их количество будет видно ВСЕМ осматривающим вашего персонажа. Работает как дефолтное вместилище для вещей, ну разберетесь, не тупые.
(Это чистый механ. Я его дам. Спрайтов на персонажей нет. Спрайты я не дам.)
Еще появилась возможность на alt+click прикрывать или оголять срамные места.
А также: устранение конфликтов в коде, микроправки.
> Gear Harness: Улучшайзинг

- code/datums/components/pricetag.dm
- code/game/machinery/civilian_bountys.dm
- code/modules/cargo/exports/civilain_bounty.dm
было: 99% за куб получает карго, 30% получает сделавший куб, 10% получает отсканировавший куб на шаттле
стало: 80%(85%) за куб получает карго, 15% получает сделавший куб, 5% получает отсканировавший куб на шаттле
в дополнение к этому теперь скоростная доставка даёт +20% к выплате за куб (начисляется до срезов сделавшему и доставившему)
> Фикс баунти кубов и разделение платы за отсканирование товаров

- code/datums/components/storage/concrete/_concrete.dm
- code/modules/clothing/under/miscellaneous.dm
Shi Scot оформил шустрый багрепорт через атикеты, и по выделенной линии личных сообщений это дело дошло до меня. Ковыряясь в микротрабле, я обнаружил просто КЛАДЕЗЬ ПИЗДЕЦА. 
Ну вот просто шок, у нас, оказывается, просто убиты аксессуары вообще, типа ты можешь снимать/надевать аксессуар на одежду, которую ты держишь в руках, а эффекты ношения будут применяться/сниматься с тебя (roflanpizdec). 
И даже пузырьки разговора над башкой персонажа сломаны, найдено было через значок адвоката (который не фурычит офк). 
А одежда не понимает, надета ли она на кого то или нет. Типа ты будешь в руках держать = носить. (ну или что-то типа того). А потом костыли придумывают для хардсьютов, где опосля носителя находят. мдаааа. 
Ах да.. заплаточку на gear harness оформил...
> Микробаг вскрыл подводные камни

- modular_bluemoon/FlaurosStuff/code/game/objects/items/devices/PDA/PDA_types.dm
- modular_bluemoon/FlaurosStuff/code/game/objects/items/devices/PDA/cart.dm
- modular_splurt/code/game/objects/structures/ghost_role_spawners.dm
- tgstation.dme
Персоналу отеля теперь выдаётся КПК с возможностью просматривать рецепты, как в КПК бармена, но без доступа к манифесту станции. QoL для отеля, достаточно сказано.
> Добавляет список рецептов напитков в КПК персонала отеля

- code/controllers/subsystem/statpanel.dm
Отныне последние режимы игры показываются под текущим. Сделано для тех, кто хочет заранее знать о возможном форсе какого-либо режима после окончания голосования.
> Выводит последние режимы игры в статпанель

- code/__DEFINES/sound.dm
- code/modules/client/preferences.dm
- code/modules/client/preferences_savefile.dm
- code/modules/mob/living/emote.dm
Теперь можно в преференсах выбрать не только текст эмоута *deathgasp, но и его звук из небольшого списка.
> Выбор звука для deathgasp

- code/modules/food_and_drinks/food/snacks.dm
Added bonus reagents to reagents list
В еде, как в /reagent_containers/ есть два списка: list_reagents и bonus_reagents. В /code/modules/food_and_drinks/food
/snacks.dm есть комментарий по этому поводу: list_reagents для реагентов, которые соответствуют ингредиентам, а bonus_reagents - прибавка, за объединение реагентов в блюда. Проблема в том, что ни гриндер не воспринимает бонусные реагенты (если попытаться передробить еду получишь только то что в list_reagents), ни кукла (когда ест, насыщается только тем, что занесено в list_reagents).
Фикс вышеозначенного бага.
:cl:
fix: fixed bonus_reagents in snacks
/:cl:
> Fix bonus reagents in snacks

- modular_splurt/code/game/objects/items/lewd_items/chastity_hypno/chastity_hypnosis.dm
Для Hypnotic Chastity Magazine, Hypnotic Chastity Watch, изменены атрибуты в Chastity Hypno (Edging-Only) с EDGING на CHASTITY
сделано это потому что EDGING используется только в Chastity Hypno (Edging-Only)
> Chastity Hypno - с EDGING на CHASTITY

- code/modules/mob/living/emote.dm
- code/modules/mob/living/say.dm
/me и несколько эмоутов теперь можно использовать в софткрите
Теперь речь в софткрите автоматически превращается в шёпот, слышно его на один тайл дальше, чем раньше (итого два тайла). 
При хардкрите раньше персонаж, попытавшись что-то сказать, умирал, прошептав это на своём последнем вздохе, теперь перед этим у игрока спрашивают подтверждение.
Теперь *help можно юзать будучи мёртвым
> Изменение речи и эмоутов в крите

- code/datums/components/twohanded.dm
offhand используемый для двуруча при крайне специфичных условиях (удаление двуруча и выбрасывания offhand в один момент (например во время взрыва) приводил к тому, что offhand дропался на пол
> offhand DROPDEL

- code/datums/martial/_martial.dm
- code/datums/martial/cqc.dm
- code/datums/status_effects/debuffs.dm
слэм теперь парадизует на 12 секунд
пинок теперь работает так - если цель лежит, в сознании и ей выбили больше 100 стамины - происходит мощный удар который оставляет цель без сознания на 10 секунд, потом ещё 10 секунд цель не сможет ничего делать + урон по мозгу
во всех остальных случаях наносится урон по формуле как и был раньше + отпинывает на один тайл от себя, дополнительно нанося 45 урона по стамине если цель лежит + в сознании
граб граб теперь станит на 10 секунд, если во время этого сделать дизарм вместо немоты кинет в сон на 40 секунд
в планах хотелось бы ещё сделать при успешном блоке в мили стан атакующему в 4 секунды и усилить броски в стену и в людей
+ теперь есть таймер на комбо в 6 секунд
> Make CQC Great Again

- code/modules/clothing/gloves/miscellaneous.dm
- code/modules/uplink/uplink_items/uplink_dangerous.dm
> Теперь являються неснимаемыми
> Дают возможность жить в софткрите
> По аналогии с пластиковой маской, при включении КИ вводят по 10 юнитов ресторативных и регенеративных нанитов(примерно 4-5 хп всего урона в секунду + лечат урон мозгу и восстанавливают кровь) с перезарядкой в 5 минут
> Все так же дают трейт толстых пальцев
> Для СБ, БЩ и Капитана особый эффект при надевании
> Теперь стоят 10тк
> Mauler Gauntlets buff

- .github/workflows/ci_suite.yml
- .github/workflows/compile_changelogs.yml
- .github/workflows/generate_documentation.yml
- .github/workflows/make_changelogs.yml
Пробую починить `Generate documentation` Workflow + обновил версии, чтобы убрать предупреждения.
А [`Compile changelogs`](https://github.com/BlueMoon-Labs/MOLOT-BlueMoon-Station/blob/77d6dd330db21aef287a57562cf91b3f944f3a2c/.github/workflows/compile_changelogs.yml#L55) вечно падает из-за, кажется, отсутствия разрешения на запись у `secrets.GITHUB_TOKEN`. Надо бы либо пофиксить разрешения токена, либо убрать/выключить этот Workflow, а то смысл 7 месяцев на каждый PR запускается, отрабатывает и падает в конце...
> Чиним workflow

- code/modules/movespeed/_movespeed_modifier.dm
- code/modules/projectiles/gun.dm
- code/modules/projectiles/guns/ballistic/automatic.dm
- modular_bluemoon/krashly/code/game/objects/items/weaponry.dm
1. Пофикшено отсутствие КД у всего оружия. что не имеет бёрст фаера, но имеет автоматический режим стрельбы
2. Выставлена максимальная скорость в игре - 10 тайлов в секунду
3. Максимальную скорость для спринта нужно трогать в конфигах. Она перегружает этот параметр.
У бульдого теперь скорострельность боевого дробовика.
Калаш стреляет со скоростью ВТ (кроме розового, он как магнитка)
Хз на что ещё повлияло
> Всякое с оружием и мувспидом

- code/datums/components/ntnet_interface.dm
- code/modules/integrated_electronics/core/printer.dm
- code/modules/modular_computers/file_system/programs/ntmonitor.dm
- modular_sand/code/modules/integrated_electronics/subtypes/manipulation.dm
- tgui/packages/tgui/interfaces/NtosNetMonitor.js
Этот ПР делает интегральный компонент адвактиватор зависимым от станционного NTnet-а и доступов. Теперь нельзя раундстартом получать полный доступ и проникать куда не следовало бы. 
Отныне, **улучшенным** принтером интегральных плат могут пользоваться только ученые или гост роли. Это зависит от роли в переменной mind, а значит, что нельзя устроится с ассистента на ученого через ГП и познать интегральные платы. Обычный принтер, без продвинутых компонентов, доступен каждому.
Ветка запроса с обсуждением этого нерфа: https://discord.com/channels/875735187449847830/1219030790550196224
Сделаны задатки под блокирование любого NTnet устройства по ID. Я плохо разбираюсь в UI, поэтому пока что лишь наброски, которые никак не мешают.
> Нерф адвактиватора интегралок и доступов принтера

- code/modules/client/preferences.dm
- modular_bluemoon/code/modules/client/preferences.dm
Тупой бесячий баг из-за неожиданной мной странной реализации хендлинга обновления браузера.
В общем, теперь при нажатии на кнопку установки хедшота, поле ввода не будет закрываться лодаутом.
> Fix browser refreshing before input is closed

- Build.bat
- code/__BLUEMOONCODE/_DEFINES/traits.dm
- code/datums/components/edible.dm
- code/modules/food_and_drinks/food/snacks.dm
- code/modules/mob/living/carbon/human/species.dm
- code/modules/surgery/bodyparts/_bodyparts.dm
- modular_bluemoon/heavy_and_superheavy_quirks/traits.dm
- modular_sand/code/modules/mob/living/living.dm
пофиксил эксплоит с нормалайзером для трейта пожиратель, дополнительно убрал лишние приколы с математикой и потиковые проверки, заменив их на действие.
> fix: devourer trait fix

- code/game/objects/items/devices/fee_terminal.dm
- code/game/objects/structures/ghost_role_spawners.dm
- code/modules/jobs/job_types/medbay/paramedic.dm
- code/modules/modular_computers/file_system/programs/card.dm
1. Теперь при переводе через id консоль должен изменяться оклад
2. Гост роли ЦК получили стандартный набор ЦКшника и печати
3. Парамедик получил обычный гипо (очень просили по причине того, что парамеды их собирают сами, но при этом мусорят)
4. Добавлена проверка на минимальную сумму штрафа для терминала
> fix: исправлен ряд мелких недочётов

- code/game/objects/items/storage/boxes.dm
- code/modules/clothing/outfits/ert.dm
- code/modules/clothing/outfits/standard.dm
- modular_bluemoon/kovac_shitcode/code/modules/clothing/outfits/ert.dm
1. ОБР инкивизиции снаряжено святой водой и прочим снаряжением аналогичным янтарному.
2. ОБР АВД снаряжено аналогично ОБР зелёного кода (по оружию и имплантам)
3. Эскадрон смерти получил импланты ОБР красного кода и некоторое улучшенное снаряжение.
4. Centcom Official получил минимальный набор имплантов и пистолет ОБР.
> tweak: поправлено снаряжение вторичных ОБР

- code/modules/mob/mob_helpers.dm
AssignQuirks принимает в себя датум, а не строку названия профы
> фикс рантайма при превращении в мага при помощи кубика

- code/game/objects/effects/spawners/lootdrop.dm
- Стимулятор из аплинка дает 25-40 минут (поправка на лаги, там 0.1 потребление в тик, а тик 2~ секунды или 5 с учётом лагов).
- Космический скафандр халявный без серьезного замедления и с броней
- Нослипы просто предмет для манча по причине МАНЧ
- Слип пены могут очень серьезно испортить игру
- Кластербенг то же самое. Во время погони это не 1 мыло.
- Сигареты с омнизином, халявный хил
По итогу убраны все причины идти туда манчеров. Оставлены референсы на синдикат и интекью, дающие возможность внести ролевое событие в раунд.
> убираем манчерские вещи из техов

- code/datums/character_profile.dm
- code/datums/dna.dm
- code/datums/elements/flavor_text.dm
- code/modules/client/preferences.dm
Теперь тройной хедшот, сделанный Юджином, снова привязан к ДНК.
Лобби говнокрадов победило, теперь ООС заметки тоже привязаны к ДНК...
Теперь IC -> Manage Flavor Text экшуалли работает, будучи переделанным с нуля под новые реалии. Только новые флаворы нельзя добавлять, лишь изменять и удалять. Ещё вроде синтофлаворы там можно менять (они теперь привязаны к майнду), но я не тестил :trollface:
> Ремонт флаворов, акт второй

- code/datums/character_profile.dm
- code/datums/elements/flavor_text.dm
- code/modules/mob/living/carbon/human/examine.dm
- code/modules/mob/living/living_defines.dm
- code/modules/mob/living/silicon/examine.dm
- code/modules/mob/living/silicon/robot/examine.dm
- code/modules/mob/living/silicon/robot/robot.dm
- tgui/packages/tgui/interfaces/CyborgProfile.tsx
Перелопатил экзамайн боргов, теперь у них есть урезанная версия хумановского профиля. А ещё на русский перевёл для не самых умных робототехников.
Починил для них Manage Flavor Text. Наверное. Может быть.
Для умных: почти окончательно отказываюсь от компонента flavor_text, переводя всё на свойства майнда/самого моба/ДНК. Возможно, это не самое лучшее решение, но копаться в этом дерьме, намешанного с кучи билдов, у меня не так много сил.
> Фикс флаворов, акт третий

- code/modules/jobs/job_types/service/clown.dm
- html/changelogs/AutoChangeLog-pr-843.yml
- modular_bluemoon/clown_pie_book/clown_pie_book.dm
- modular_citadel/code/modules/client/loadout/__donator.dm
- tgstation.dme
Дарк, не делай больше /:cl: в своих ПРах пожалуйста.
Мим и клоун при наличии аплинка могут за 1(!) ТК выдавать себе книги, позволяющие сделать любому абилку на закидывание пирогами. В теории, должно вызывать проблемы у СБ и командования, отвлекая от ролей. Да и просто silly war.
Клоун получает эту абилку раундстартом.
А по теме сабжа с выпилом книги из лодаута:
<details>
1. Арбзуная штука, которую можно (и которую применяют) во время задержания или робаста. Роняние на пол заставляет чела мыть низкомобильным достаточное количество времени, чтобы подбежать и предпринять действия, пока он не носится как гоночный боллид.
2. Пироги повышают сытость персонажа, что вызывает особенную фрустрацию из-за переедания. И как бы, с этим не было проблемы, т.к. их не было так много раньше.
3. Халявная …
> Даём клоуну спелл на создание пирогов, пироги в алинк для клоуна и мима, удаляем книгу для пирогов из лодаута

- code/modules/mob/living/silicon/robot/robot_modules.dm
Раньше при выборе ММеки у peacekeeper модуля выбирался фелин, а при тыке на фелина ничего не происходило. Чиним.
> Починил выбор MMеки и фелина у пискипер боргов

- code/modules/mob/living/carbon/human/human.dm
Персонажей с квирком "Лёгкий" теперь можно брать на ручки/плечи даже если они стоят. Уменьшил время поднимания персонажей буквально на 1 секунду.
> Хвать за жопь и в дормы!

- code/controllers/subsystem/autotransfer.dm
- code/controllers/subsystem/persistence/recent_votes_etc.dm
- code/controllers/subsystem/ticker.dm
- code/controllers/subsystem/vote.dm
- code/game/world.dm
- modular_bluemoon/vlad0s_staff/code/midround_record.dm
- tgstation.dme
Теперь при первом воуте за шаттл, вне зависимости от его результата, карта и режим записываются в SSPersistence и будут учитываться в общем счёте, как учитывались бы при нормальном завершении раунда.
Теперь раунд имеет пометку, завершился он нормальным ребутом или крашем. В последнем случае после перезагрузки будет произведено голосование за карту, после которого сервер будет снова перезапущен, но уже на новой карте.
> Изменил систему ротации карт и режимов в связи с крашами

- _maps/RandomRuins/SpaceRuins/BlueMoon/forgotten_ship.dmm
- modular_bluemoon/SmiLeY/inteq_ghostrole/forgottenship.dm
Неправильно прописанные пути зон стали причиной того, что АПЦ не заряжались. Этот ПР решит это. Я надеюсь.
(+602 -616) потому что все зоны пришлось переделать)
> Фикс АПЦ Гострольки Интекью

- code/modules/arousal/organs/breasts.dm
Реагент молоко суккуба рантаймил, ведь максимальный размер у груди был строкой. Т.е, игра не могла сравнить G и цифру 7, выдавая рантайм. На выходе мы имели то, что грудь не увеличивалась. Я пофиксил это, теперь все работает как надо
> Починил увеличение груди

- code/datums/character_profile.dm
Теперь обнажённый флавор зависит не от наличия / отсутствия джампсьюта, а от покрытия одеждой гроина и груди. То бишь теперь в трусах и в лифчике его не увидеть, а в альткликнутом гир харнессе - вполне.
> Изменение видимости нейкед флавора

- code/game/objects/items/handcuffs.dm
- code/modules/cargo/packs/armory.dm
- code/modules/projectiles/guns/ballistic/automatic.dm
- code/modules/projectiles/guns/energy/energy_gun.dm
- code/modules/projectiles/guns/energy/laser.dm
- code/modules/projectiles/guns/energy/stun.dm
- code/modules/projectiles/projectile/beams.dm
- code/modules/projectiles/projectile/bullets/smg.dm
- code/modules/reagents/chemistry/reagents/medicine_reagents.dm
- modular_bluemoon/SmiLeY/blastwave_outfits/code/cargo_packs.dm
- modular_bluemoon/kovac_shitcode/code/modules/guns/weapons.dm
Даное изменение затронет как обычных игроков, так СБ и антагонистов
Оружие:
Большинство энергетического и лазерного оружия в игре получило размер BULKY(что значит что теперь офицер не сможет ходить с половиной арсенала), не касается антикварки, мультифаза и драгнетов
ВТ550
Скорость стрельбы в автоматическом режиме снижена, и чуть быстрее стрельбы одиночными выстрелами
обычные пули на ВТ имеют сниженые показатели wound-а
АП пули на ВТ получают сниженый урон но выше бронепробитие
15.5 => 14
40% => 50%
Будет стоить 3000 в карго вместо 2500
Лазган
По аналогии с ВТ снижена скорость стрельбы в автоматическом режиме и теперь чуть быстрее чем одиночными выстрелами
Стоимость в карго снижена до 10000
(офк так же получает размер BULKY что не позволит носить в рюкзаке)
Урон по стамине от дизейблеров …
> balance update

- _maps/map_files/Deltastation/DeltaStation2.dmm
Поварята, как и полагается, теперь имеют доступ к шлюзам ботаники, увеличено количество точек спавна ассистентов, дабы те не появлялись на лобби скрине, а так же комната пыток обрела свой кинкомат.
Все упомянутые изменения затронуты только Дельтестейшен.
> Исправление доступов ботаники и кинкомат в комнату пыток на Дельтастейшен

- code/modules/client/preferences.dm
- modular_bluemoon/code/modules/clothing/suits/poly_cape.dm
- modular_citadel/code/modules/client/loadout/_loadout.dm
- modular_citadel/code/modules/client/loadout/head.dm
Теперь в лодауте можно видеть иконки предметов.
К сожалению, всякие губные помады и серёжки отличаются только цветом, поэтому иконки у них выводит одинаковые.
~~Спизжено~~ вдохновлено [этим](https://github.com/ss220-space/Paradise/pull/4507)
> Превью иконок в лодауте

- code/modules/recycling/disposal/bin.dm
- code/modules/recycling/disposal/outlet.dm
- code/modules/shuttle/supply.dm
При сдвиге мусорного бака, входа или выхода (к примеру с помощью драконьей формы), они оставались связанными с мусорными трубами даже находясь далеко от трубы. Фикс исправляет это недоразумение и теперь при сдвиге объекта они перестают быть соединёнными.
Также в чёрный список шаттла был добавлен мусорный выход, поскольку с его помощью можно было попасть на ЦК через транспортный шаттл.
> Fix disposals teleports

- code/modules/clothing/under/_under.dm
- code/modules/clothing/under/accessories.dm
- code/modules/clothing/under/bodycam.dm
- modular_sand/code/modules/mining/lavaland/necropolis_chests.dm
- modular_splurt/code/game/objects/items/weapon_permits.dm
Теперь аксессуары, влияющие на боевые возможности персонажа (на броню джампсьюта, например) имеют свой отдельный лимит, равный трём (то есть можно носить 3 боевых и 4 обычных аксессуара в одно время).
Также некоторые аксессуары ограничены в возможности стакаться с похожими на себя.
> Изменил систему лимита аксессуаров

- code/modules/jobs/jobs.dm
Было бы логично, чтобы игра за личную горничную капитана и того, кто в нынешних условиях постоянно подменяет главу персонала, давала опыт для его разблокировки.
> Теперь опыт за офицера мостика идёт также в счёт для разблокировки ГП

- modular_citadel/code/modules/client/loadout/_security.dm
- modular_splurt/code/modules/client/loadout/glasses.dm
Просто позволяет авиаторам, голографическим HUD и СБ HUD быть доступными для миротворцев в loadout. Не знаю, почему это не было сделано раньше.
Первый PR. Если сделал что-то не так, бейте меня по голове ботинком.
> Больше вариантов HUD для миротворцев.

- code/datums/status_effects/buffs.dm
Небольшой рефакторинг статус эффекта клятвы Гиппократа для подстановки под компонент ауры исцеления.
К сожалению из-за невозможности компонента лечить клеточный урон, аура была лишена этой возможности (если компонент не будет переработан позднее).
Остальное осталось без изменений.
> Рефакторинг эффекта клятвы Гиппократа

- code/__BLUEMOONCODE/_DEFINES/traits.dm
- code/modules/surgery/surgery_step.dm
- modular_bluemoon/maintenance_quirk/maintenance_quirk.dm
- tgstation.dme
Квирк, дающий 4 очка в замен на то, что операции на синтетике могут проводить только роботехники, РД и антагонисты.
Если его возьмет обычный член экипажа, с его квирками случится смешное.
Желание кечиться в ИЦ, какие дорогие в ремонте протезы + ролевая игра, что протезы может обслуживать только специалист.
Фикс
> Квирк синтетикам: "Сложное техобслуживание"

- modular_splurt/code/game/objects/items/lewd_items/rope.dm
Обычного персонажа (без квирка - Cверхтяжёлый) нельзя было привязать веревкой к предмету и таскать за собой, хотя по коду приходит сообщение, что персонаж слишком тяжелый. (related commit: https://github.com/BlueMoon-Labs/MOLOT-BlueMoon-Station/issues/554)
Тогда как сверхтяжёлых - можно.
Fixed
fix: 
Логическая ошибка
/:cl:
> Fix: Cверхтяжёлых персонажей можно было таскать за собой

- code/game/objects/items/robot/robot_upgrades.dm
- code/modules/mob/living/silicon/robot/robot_movement.dm
- code/modules/mob/living/silicon/robot/robot_sprint.dm
Уменьшение модификатора скорости силиконов при спринте (с 1 до 0.5)
Уменьшение модификатора скорости силиконов при активном VTEC (с 1.25 до 0.75 во втором режиме,  1.75 до 1 в третьем режиме)
Также было снижено потребление энергии батареи при спринте (с 25 до 15 на клетку)
Киборги перестанут молниеносно передвигаться по станции, но всё ещё остаются быстрее среднестатистического космонавтика без химии. А снижение потребления энергии при спринте не даст разрядится стандартной батареи слишком быстро.
> Изменение скорости силиконов

- code/modules/mob/dead/crew_manifest.dm
Небольшой баг-фикс, который ранее блокировал киборгам возможность использовать манифест экипажа.
> Cyborg Manifest bug-fix

- code/__DEFINES/antagonists.dm
- code/game/objects/effects/contraband.dm
- modular_bluemoon/Fink/code/datums/components/demoraliser.dm
- modular_bluemoon/krashly/code/game/objects/items/item.dm
Касается постеров и флагов InteQ.
- Теперь намного меньше боятся пропаганды: Капитан, СБ, главы, имплантированные майндшилдом и капеллан. Чем ближе ролька к началу списка, тем слабее на неё действуют эффекты.
- Теперь пропаганда интекью даёт очень сильный дебафф к муду у обычных ребят, более слабый у вышеперечисленных, а также очень хороший бафф к муду у самих интекьюшников.
- Эффекты сменены на менее доставучие. Теперь не будет криков REALAGONY от того, что кто-то заметил бумажку на стене, но настроение микрочелам будет портить знатно.
- Теперь не антагонисты, не члены интекью и не гострольки слишком бояться вешать плакаты и флаги.
> Сделал пропаганду интекью менее доставучей

- modular_bluemoon/Ren/Code/staff/plasma_weapon.dm
В данный момент свет исходящий от плазменной косы, а также от плазменного топора, слишком сильно сливается с освещением станции.
Данное изменение делает освещение от плазменной косы более заметным и зловещим, скриншоты для сравнения прилагаются.
До:
После:
> Небольшое визуальное изменение освещения плазмокосы

- code/modules/mob/living/silicon/robot/robot_modules.dm
По неизвестной причине "(Service) Meka" не была добавлена в список действий при выборе конкретной модели, но теперь всё на своих местах :)
> Bug fix выбора сервисной Меки

- code/modules/clothing/spacesuits/hardsuit.dm
Фиксит юбки, которые были видны через скафандры из-за неправильного указания флагов у хардсьютов.
Было:
> Fix: Юбки видны сквозь хардсьюты

- modular_splurt/code/modules/projectiles/boxes_magazines/ammo_boxes.dm
- modular_splurt/code/modules/projectiles/boxes_magazines/external/pistol.dm
fix: исправил цену расширенного заряженного магазина на энфорсер, сейчас патрон в нём стоит в ~2,5 дешевле чем в коробке
add: добавил пустой магазин на энфорсер и расширенный пустой магазин на энфорсер во взломанный автолат. Чтобы сб не сорило патронами и при надобности печатало себе пустые для заполнения с коробок.
> tweak: снова энфорсер и магазины

- _maps/map_files/BoxStation/BoxStation.dmm
- _maps/map_files/PeaceSyndicateStation/PeaceSyndicateBoxStation.dmm
- _maps/map_files/PubbyStation/PubbyStation.dmm
Исправляет это недоразумение. Это действительно заслуживает отдельного пулл-реквеста
Дополнительно убраны переменные pixel_x/pixel_y и dir, которые были присвоены кабелям на картах, так как они ни на что не влияют
> Fix: Кабель на Пабби

- code/modules/mob/living/living.dm
Если человек прожимает succumb, в чат выдаётся сообщение, что он сдался.
Нужно для предотвращения ситуаций, когда человека пытаются взять живым, а он дерётся до смерти и по итогу прожимает сдачу, выставляя кого-либо как убийц.
> Сообщение, что человек прожал succumb

- code/game/objects/items/tools/crowbar.dm
1. Урон тяжёлого лома снижен с 20 до 14 единиц.
2. Потому что у другого менее доступного оружия урон ниже. Например, у копья при броске урон 40, но в двух руках 18. У кортика урон 14. У заточенного ножа сколько не считал.
3. Потому большой размер оружия компенсирует его лёгкое получение.
> Нерфим тяжёлый лом

- code/_onclick/hud/hud.dm
- code/_onclick/hud/human.dm
Добавляет оверлей видимости в темноте (который позволяет видеть своего персонажа при нулевом освещении) всем существам
До:
После:
Такая особенность была только у людей. Теперь она будет у простых мобов
> Tweak: Оверлей видимости в темноте 

- code/modules/research/designs/autolathe_desings/autolathe_designs_sec_and_hacked.dm
Добавлена возможность печатать патрон 7.62x38R для револьвера Наган во взломанном автолате, поскольку нет каких-либо способов приобрести или напечатать патроны для данного оружия отдельно.
_Сделано по просьбе игрока kiro6882_
> Револьверный патрон для Нагана во взломанный автолат

- code/game/objects/items/RCD.dm
Теперь, при попытке сборки/разборки чего либо с помощью Rapid Construction Device и его вариаций, проверка, достаточно ли в RCD материи для выполнения этого действия, будет происходить до запуска анимации и ожидания, а не после, как это было раньше. Проверка теперь производится два раза: первый раз - перед началом сборки, второй раз - когда сборка завершена и нужно "использовать" материю. Если при первой проверке материи будет недостаточно, RCD сразу выдаст ошибку "low ammo".
https://github.com/user-attachments/assets/6b546cf1-870d-49ee-89dc-085a38dbcf8f
Изменено описание и название combat RCD.
QOL чендж. Неприятно, когда ты десять секунд разбираешь шлюз только для того чтобы обнаружить, что тебе не хватило одной единички материи. Такое крутое устройство как RCD наверняка должно уметь …
> [FIX] RCD теперь проверяют количество материала ДО запуска doAfter

- code/__DEFINES/sound.dm
- code/game/machinery/dance_machine.dm
- code/game/machinery/dance_machine_handled.dm
- modular_bluemoon/Fink/code/items/moniq.dm
Одновременное проигрывание трэков у нескольких жукбоксов "ломает" другие жукбоксы, не давая их использовать и создает рантайм.
Исправление заключается в "расширении" диапазона доступных каналов у проигрываемых треков и дополнительных проверках.
Не ломает жукбоксы. Жужж.
N
> Fix: Неработающие жукбоксы

- modular_splurt/code/modules/awaymissions/mission_code/AGRComplex.dm
Убирает возможность спавнить мобов-культистов с помощью золотого экстракта слайма
Данные мобы предназначены только для задействования на гейтвей-уровне "AGR Complex", наверное такая возможность была допущена по невнимательности разработчика?
Их спавн через экстракт приводит к тому, что может заспавниться моб-культист (который нужен лишь для наследования для других типов мобов-культистов) без спрайта и "фракции", атакующий всех, а возможность спавна "выжившего культиста с комплекса" через ксенобиологию не выглядит логично...
> Removal: Мобы-культисты с золотого экстракта

- _maps/map_files/generic/CentCom.dmm
Играют только в одной зоне (чтобы не шуметь в "главное меню")
Убрана требование по доступу (наконец их можно включить)
Диско шары прицеплены к полу
Емаг с джукбоксов убран
> Фикс Джукбоксов на цк слое

- _maps/map_files/BoxStation/BoxStation.dmm
- _maps/map_files/MetaStation/MetaStation.dmm
- _maps/map_files/PeaceSyndicateStation/PeaceSyndicateBoxStation.dmm
- _maps/map_files/PubbyStation/PubbyStation.dmm
- code/game/area/Space_Station_13_areas.dm
Затрагивает карты BoxStation, PeaceSyndicateStation, MetaStation и PubbyStation
1. Убирает большое количество сеток под стенами:
2. Исправляет тег у камер в офисе НТР, чтобы оно обозначалось как "NTR Office", а не как "Chapel Crematorium"
3. Убирает лишние зоны nearstation, располагающиеся не на положенном месте
Мелочь, а приятно.
> Незначительные исправления карт

- code/modules/mob/living/carbon/human/emote.dm
- code/modules/mob/living/carbon/human/examine.dm
Первое теперь работает, а второе выделяется на фоне полотна однообразного текста.
> Починил автовиляние хвостом для фелинидов. Изменил цвет описания клетки на её носителе.

- code/modules/surgery/bodyparts/_bodyparts.dm
А также фикс нанесение пятикратного единовременного урона оружия в конечность при достижении порога урона.
Развёрнуто:
- Исправлен пятикратный мгновенный урон.
- Добавлен переход 65% урона с поврежденной конечности в торс.
> Переход урона с одной конечности на грудь при превышении максимального

- code/modules/reagents/chemistry/reagents/other_reagents.dm
- modular_bluemoon/code/modules/arousal/arousal_robot.dm
- modular_sand/code/datums/interactions/lewd_definitions.dm
- modular_splurt/code/datums/interactions/lewd/_lewd.dm
- tgstation.dme
В связи с тем, что большая часть ЕРП механик завязана на системе органов и гениталий, которые ни с логической, ни с механической частью не подходили для боргов, часть механик была переведена на новые рельсы без нарушения функционала. Что позволит в будущем проще вводить новый эротический функционал ориентированный на силиконов.
В "Robot Commands" были введены три новые кнопки:
Climax — Уже всеми знакомая кнопка доступна и юнитам, борги также получили возможность кульминировать не только текстом, но и механом, близким к механу карбонов.
Liquit — Теперь борги могут выбирать чем именно они будут осеменять и переполнять своих жертв, в любое время!
Set Liquit Amount — Устанавливает количество жидкости, которое борги смогут использовать за раз.
Также, был добавлен новый реагент "Synthetic …
> Улучшение ЕРП механик для киборгов

- code/modules/reagents/chemistry/reagents/drink_reagents.dm
- code/modules/reagents/chemistry/reagents/other_reagents.dm
- Красная королева и серум роста повышали размер персонажа не по механу сплюрта, а по механу сэндшторма, что приводило к игнорированию любых дополнительных эффектов от изменения размера (800% персонажа без замедления, доп ХП и т.п.).
- Выставлен максимальный возможный размер в более привычный, ровно как и актуализировано как они увеличивают рост.
-
> Фикс размера и исправление легаси кода для красной королевы и серума роста

- _maps/map_files/FestiveBall/FestiveStation.dmm
Основываясь на запросе с последней игры от игроков, ксенобиология была изменена под современные нужды.
Были добавлены:
Скруберы в камерах и ксенобиология была подключена к основной системе трубопровода.
Дробилка мартышек.
БЗ канистра и соответствующие трубы для неё, всё по современым технологиям
Скриншот изменения:
:cl:
add: Скруберы в камеры и ксенобио, дробилка мартышек, БЗ канистра и стандартная мелочёмка как "air alarm" на стены
/:cl:
> Изменение ксенобиологии

- code/modules/mob/living/carbon/human/species.dm
- modular_sand/code/modules/mob/living/carbon/human/species_types/zombies.dm
- У обычных зомби нет необходимости использовать обезболивающее при хирургии. Но ромерольные зомби берут обычных зомби, переписывают их трейты и теряют часть данных свойств. Этот ПР фиксит это.
- Мазохисты больше не должны ОКАНЧИВАТЬ, когда они без сознания (например, присмерти при получении дамага или на хирургическом столе).
> Фикс хирургии для ромерольных зомби и мазохистов

- modular_splurt/code/game/objects/items/storage/wallets.dm
Теперь пачки сигарет (любых) можно засунуть в tailbag. 
В xl tailbag тоже. 
Коробки сигар нельзя.
> Пачки сигарет мне в tailbag!

- code/modules/clothing/under/jobs/engineering.dm
Добавил защиту униформе атмостеха, услышал, что много раз  просили.
Защита от радиации убрана, компенсировано повышенной защитой от огня. В описании это указано, зеркально к описанию рад. защиты униформы инженера. Защита перенесётся и на вариант-юбку.
> Atmos uniform protection

- code/modules/clothing/head/hardhat.dm
Фиолетовая каска а.к.а. workplace-ready firefighter helmet `/hardhat/red/upgraded` скрывала причёску и уши куклы, спрайт каски при этом выглядит как модифицированная незакрытая hardhat каска. 
Удалил ей изначальные флаги. Дал ей игнорирование флагов от родительской `/hardhat/red` (Шлем пожарного), чтобы отображалось корректно.
И вот обычная hard hat `/hardhat` каска, для сравнения фиолетовой и обычной версий.
> Отображение причёски и ушей у каски

- code/modules/admin/banjob.dm
- code/modules/mob/dead/observer/logout.dm
- code/modules/mob/dead/observer/observer.dm
- config/splurt/autocryo.txt
- modular_splurt/code/controllers/configuration/entries/splurt_autocryo.dm
- modular_splurt/code/controllers/subsystem/afk.dm
Фикс пары рантаймов при попытке удалить госта
Удаление госта теперь чистить его клиента и отправляет его в лобби (теперь можно удалять гостов и это реально будет работать)
Автокрио теперь корректно удаляет гостов и они удаляются из любых список (да, боле без мёртвых душ)
> реальное удалением гостов при помощи автокрио

- code/datums/datacore.dm
- code/modules/jobs/job_titles.dm
- modular_splurt/code/modules/jobs/job_types/_job_alt_titles.dm
убраны дубликаты названий проф и теперь стандартное имя профы отображается в манифесте
> фикс дублей альт проф и манифеста

- code/modules/mob/living/brain/MMI.dm
до этого "душа" оставалась в мми после вытаскивании мозга от чего по итогу получалась болванка в виде мозга и душа запечатанная в MMI
> При вытаскивании мозга из ММИ душа переходит в мозг

- code/game/machinery/doors/airlock.dm
Добавил возможность сорвать бумажку с аирлока обычной рукой, граб интентом, не используя кусачки (Чем их таким клеят, что их рукой отодрать нельзя?!)
Падает сразу в руку, со звуком срываемого постера.
Применение кусачек не убирал
> GrabToRemovePaper

- code/modules/reagents/chemistry/machinery/chem_dispenser.dm
Выставил `chem_dispenser/drinks` слой-layer как у, например, автолата, чтобы прислоняющиеся к столику бармены не стояли с ними "на плечах".
> Layer machinery fix

- modular_bluemoon/kovac_shitcode/code/modules/vehicles/mecha.dm
Оба меха с предустановленным вооружением имели  отрицательное количество доступных слотов
заменил увеличив количество слотов и впаяв часть оборудования в неснимаемое
> Фикс отрицательного количества слотов у 2 мехов

- modular_bluemoon/code/game/objects/items/fleshlight.dm
- tgstation.dme
Портальные трусики и портальный фонарик теперь через ctrl + клик позволяют послать эмоут на другую сторону
(ну а так-же через *fleshlight (так надо)
Портальные трусики посылают эмоут всем держащим сопряжённые фонарики
Портальные фонарики посылают эмоут на портальные трусики (конкретные), но только если они надеты.
Если на другой стороне нет держащего фонарика или трусики ни на кого не надеты, то изначально не даст написать эмоут.
(в дополнение эмоут ещё и виден всем в радиусе 1 тайл от написавшего эмоут (но не рядом с принимающим эмоут)
> Кастомные эмоуты через портальные трусики

- modular_splurt/code/modules/jobs/job_types/_job_alt_titles.dm
Новый альт нейм для детектива, AC Recon Agent - "Агент АС по разведке" (У всего состава брига, кроме детектива, были альтнеймы тематики АС).
Оговорено с Они, как автором этой кеткринской ЧВК.
> Альтнейм: AC детектив

- _maps/RandomRuins/SpaceRuins/BlueMoon/infested_frigate.dmm
- _maps/shuttles/bluemoon/ftu_tradeship.dmm
- code/modules/vending/wardrobes.dm
- modular_bluemoon/Ren/Code/FTU/loot.dm
- modular_bluemoon/fingerprinter/fingerprinter.dm
- modular_bluemoon/station_agents_cards/cards_id.dm
- modular_citadel/code/modules/client/loadout/__donator.dm
Карта синдиката из лодаута:
- заменяет старую карту.
- копирует свойства предыдущей карты.
Карта синдиката из раздатчика больше не может копировать доступ.
Расширен лор карт синдиката.
- Меньше абуза карт на уровне "ГСБ раздаёт свой доступ всему отделу из донатеров", плюс оставляет только одну карту персонажу, убирая "запаску", которую можно кому-нибудь отдать.
> Карта синдиката из лодаута:

- code/modules/clothing/under/_under.dm
Изменение стиля ношения костюма теперь правильно обрабатывает гениталии, не вызывая проблем с оверлеями и прочими тонкостями. Этот фикс касается не только gear harness но и любого костюма, который изменяет их видимость при альт-клике по ним.
> [BLUEMOON] Фикс gear harness (и еще чего-нить)

- code/__DEFINES/radio.dm
- code/modules/mob/living/say.dm
- modular_bluemoon/SmiLeY/inteq_ghostrole/forgottenship.dm
- Исправлены спрайты наушника/headset гост-интекью. Раньше он не отображался в руке, на земле и на кукле, не имел уникального звукового эффекта рации. Подробнее смотреть по изменению в файле.
- Добавлены хоткеи :й и :ц для ДС-1 и ДС-2 соответственно. Теперь работает :w хоткей для ДС-2 канала.
К сожалению, я не смог заставить воспринимать хоткей для ДС-1 в английской раскладке (:q не работает). 
Более того, оно не работало даже при смене клавиши q (Занятой Каарен в файле `\code\__DEFINES\say.dm` и отелем в `\code\__DEFINES\radio.dm`) на другую (:a в моём случае).
Работает русский аналог, что я, считаю, тоже хорошо.
> Double fix

- modular_bluemoon/station_agents_cards/cards_id.dm
Карты синдиката из лодаута больше не заменяют собой карты игрока, если карта уже обладает свойствами синдикарты (или принадлежит заключенному).
> Защита от невнимательности (дурака)

- code/_onclick/hud/alert.dm
Передача предмета из рук в руки могла спровоцировать бесконечный спам текста для получателя. Исправлено.
> [BLUEMOON] Фикс передачи вещи

- code/modules/clothing/glasses/_glasses.dm
фикс, что при перемещении cybernetic eyepatch в инвентаре (в сумку и из неё) персонаж ловил урон по глазам
теперь только в момент снятия (уничтожения) cybernetic eyepatch
> Cybernetic eyepatch blindness fix

- modular_splurt/code/game/objects/items/stacks/tiles/tile_reskinning.dm
Фикс рескина плитки когда ту держит борг.
1) пофикшено расположение меню (теперь оно всегда на персонаже)
2) пофикшено превращение плитки в сломанный модуль, от чего плитка застревала в модулях борга мёртвым грузом
> Фикс рескина тайлов в гриппере боргов

- code/game/objects/buckling.dm
- code/game/objects/structures/beds_chairs/bed.dm
- code/modules/mob/living/silicon/robot/robot.dm
- code/modules/mob/living/silicon/robot/robot_mobility.dm
Сверхтяжёлых персонажей снова нельзя укладывать на объекты, которые для них не предназначены
> Фикс попыток посадить сверхтяжа

- code/datums/skills/modifiers/job.dm
- code/datums/wires/_wires.dm
- code/datums/wires/airalarm.dm
- code/datums/wires/airlock.dm
- code/datums/wires/apc.dm
- code/datums/wires/autolathe.dm
- code/datums/wires/emitter.dm
- code/datums/wires/mod.dm
- code/datums/wires/mulebot.dm
- code/datums/wires/particle_accelerator.dm
- code/datums/wires/robot.dm
- code/datums/wires/vending.dm
- code/modules/jobs/job_types/command/chief_engineer.dm
- code/modules/jobs/job_types/command/research_director.dm
- code/modules/jobs/job_types/engineer/atmospheric_technician.dm
- code/modules/jobs/job_types/engineer/station_engineer.dm
- code/modules/jobs/job_types/research/roboticist.dm
- modular_sand/code/datums/wires/firealarm.dm
Трейты `TRAIT_KNOW_ENGI_WIRES` и `TRAIT_KNOW_CYBORG_WIRES` теперь задействованы в коде и позволяют видеть значения цветов проводов раундстарт/прилетевшим инженерам, робототехникам. Теперь **квалифицированные** специалисты действительно обучены.
- Mulebot, MOD, cyborg - для робототехника и РД;
- Airlock и куча машинерии - для инженеров и СЕ.
Для этого этим профессиям добавлен соответствующий трейт через `mind_traits =`. 
В `/datum/skill_modifier/job/level/wiring` теперь добавлены градации скилла `trained` и `master`, поскольку есть машины, требующие для видимости проводки таких значений (Микроволновка для trained, например; master для киборга и АПЦ). 
- Теперь атмосферный техник обучен проводке на уровне `trained`, обычный инженер как `expert` и СЕ как `master`. Basic нет ни у кого …
> Навыки проводки и видимость проводки инженерам и робототехникам

- code/modules/mob/living/living_defense.dm
- modular_splurt/code/modules/mob/living/living.dm
- Теперь минимальное количество брони, которое получает персонаж размером более 175%, составляет 25% от изначальной. 
- До этого, броня умножалась на отрицательный размер (т.е. 200% броню удаляли, т.к. это по сути уже 100% брони).
- Пофикшен рантайм, который выскакивал при попытке дважды привязать элемент голоса от размера, когда он уже привязан при попытке изменения размера персонажа.
- ?? Смайли говорит, так лучше.
- Меньше рантаймов.
- Теперь минимальное количество брони, которое получает персонаж размером более 175%, составляет 25% от изначальной.
> Изменения подсчёта брони больших персонажей и фикс рантаймов при изменении размеров

- code/modules/mob/living/carbon/human/examine.dm
- code/modules/vending/wardrobes.dm
- modular_bluemoon/phoenix404/modules/vending/wardrobes.dm
- modular_bluemoon/station_agents_cards/cards_id.dm
- modular_citadel/code/modules/client/loadout/__donator.dm
Замена кард агентов из лоадута и автомата на карты с позывным.
От кард агентов отличаются тем, что имеют отличительный путь, не имеют доступа синдиката, не могут копировать доступ.
Могут изменять свой позывной (НЕ ИМЯ) и внешний вид.
https://discord.com/channels/875735187449847830/1310986350668939274
> Карты с позывным вместо гражданских кард агентов

- code/modules/mob/living/carbon/carbon.dm
Цветок не одежда, но на голове = прок прерывался из-за этого и не шёл дальше. пофиксил чтобы всё работало и теперь  ночное зрение включается когда цветок на голове
Багфиксы круто
> Фикс ночного зрения + цветка на головке

- code/game/objects/structures/ghost_role_spawners.dm
- code/modules/awaymissions/corpse.dm
- modular_splurt/code/game/objects/structures/ghost_role_spawners.dm
1) Переработана система выдачи банк аккаунта гост роли, прок выдачи банкаккунта переехал из униформы в сам спавнер и у спавнера появилось 2 новые переменные позволяющие быстро создать аккаунт и количество на нём денег (при желании можно оставить гост роли кучу денег на банк аккаунте, но не выдать карту)
2) В память гостролей имеющий банк аккаунт добавлен номер их аккаунта
3) Гостроли имеющие карту со своим банковским аккаунтом получают аккаунт на своё имя, а не на случайное имя
4) Посетители отеля лишаются кейса с деньгами и их деньги сразу переезжают на карточку 
Багфиксы, упрощение создание гостролей и выполнение [запроса](https://discord.com/channels/875735187449847830/1296558261650063381)
> Банкаккаунты для гостролей

- modular_splurt/code/game/objects/items/weaponry/melee.dm
Бейсбольная бита придавала импульс даже если бить этой битой самого себя, из-за чего в космосе из-за этого у моба накапливался бешенный импульс который мгновенно меняется в зависимости от того в какую сторону смотреть и бить, сверху этого добавляя то, что со стойким деревянная бита не наносила урон, позволяя преодолевать космос за считанные мгновения
Багфиксы
> Фикс бага с бейсбольной битой

- code/datums/elements/flavor_text.dm
Теперь при выборе изменения ООС-заметок в Manage Flavor Text подставляются старые ООС-заметки, а не лор расы.
Багфикс https://discord.com/channels/875735187449847830/1322946806002221159/1322946806002221159
> Исправил плейсхолдер текст в менеджменте ООС-заметок

- _maps/templates/shelter_6.dmm
Тряпочка чтобы чистить микроволновку в капсуле с гидропоникой и кухней
Чтобы всё работало из коробки (капсулы)
> Добавляем тряпочку для чистки микроволновки в капсулу шахтёров

- modular_bluemoon/shower_trait/shower_trait.dm
1) Внутренне теперь у зон есть переменная используемости в душе, а тоесть для других зон легко можно добавить правильность для душа
2) Добавлен блок на генерацию загрязнения если сидеть и не двигаться (состояние комфорта, которая и так блокирует жажду и голод (читать как два других квирка)
Упрощение взаимодействия с кодом и упрощение рп составляющей игры
> Обновление нужды в душе

- code/modules/mob/living/carbon/human/examine.dm
- modular_splurt/code/modules/clothing/sizeaccessories.dm
Переписал код нормалайзеров и убрал лишние строки
Кольцо нормалайзер можно запихнуть на перчатки (перчатки получают время снятия и надевания как кольцо нормализатор)
Кольцо нацепленное на перчатку теперь отображается при осмотре персонажа
Багфиксы
Возможность нормально использовать кольцо нормализатор с любой одеждой
Больше информации при осмотре других персонажей
> Кольца нормалайзеры теперь можно запихнуть на перчатки и это работает

- code/modules/surgery/bodyparts/parts.dm
- modular_splurt/code/modules/paperwork/pen.dm
Исправлен код нанесения надписей на  теле и гениталиях. …
> Чиним надписи на теле (6 часов)

- code/datums/elements/flavor_text.dm
- code/modules/admin/verbs/pray.dm
- code/modules/client/preferences_toggles.dm
- code/modules/client/verbs/ooc.dm
- code/modules/emote_panel/emote_panel.dm
- code/modules/mob/mob_movement.dm
- code/modules/mob/say.dm
- code/modules/mob/say_vr.dm
- modular_bluemoon/code/modules/mob/living.dm
- modular_bluemoon/modules/anti_ghost_indicatored/anti_ghost_indicatored.dm
- modular_citadel/code/modules/client/preferences_toggles.dm
- modular_sand/code/modules/client/preferences_toggles.dm
- modular_sand/code/modules/mob/living/living_movement.dm
- modular_splurt/code/modules/mob/say_vr.dm
Добавление Say в меню справа сверху в котором находятся всевозможные вариации say и me вербов.
Разделение меню IC на раздел кнопок для изменения положения персонажа на слоях отображения и на z слоях.
Разделение Preferences на раздел для гостов, всё связанное со звуками и с OOC.
Упрощение жизни
> Менюшка Say и разделение verb'ов по разделам

- code/game/objects/items/toys.dm
1) теперь одиночные карты при складывании в руку карт складываются в порядке, что карта которая держится в руке отображается первой (упрощает игру в Unum и другие подобные карты с закидыванием карт на стол)
2) Изменение апдейт спрайта у руки карт, теперь все вариации плэйсхолдера для карт отображаются и не вызвает рантаймы
Фикс рантайма, упрощение игры в унум и дурака
> Фикс рантаймов с картами и небольшие передлки

- code/modules/cargo/exports/materials.dm
- code/modules/mob/living/simple_animal/bot/bot.dm
Боты во время получения лечения имел шанс пролить масла, теперь нет. (Особенно ярко это происходит при лечащей ауре)
Багфикс
> Фикс проливания из бота масла во время личения

- code/datums/components/fantasy/prefixes.dm
- code/modules/unit_tests/chain_pull_through_space.dm
Данный аффикс вызывает рантаймы, собственно при этом никак не работает. 
Не ну былоб круто если-бы получилось это пофиксить, но это проклятая часть кода и навряд-ли кто-то пофиксит
Вызывает рантаймы  на этапе тестов если на тестируемой карте выпадет ивент на рпг систему и собственно в самой игре.
Нет, я не знаю как это пофиксить и да, повторюсь - оно не работает
> rpg_loot_items "фикс" рантайма связанного с тактичными вещами

- _maps/splurt_maps/map_files/4Nalstation/4NaL_Station.dmm
- code/game/objects/items/weaponry.dm
Это просто ренейм с особым спрайтом, проблема, что спрайта нет
(ну и мимоходом фикс ещё одного рантайма связанного с 4налом (выпилите его уже наконец)
Чистка кода от неработающих вещей
Фикс рантаймов
> Удаление cricket bat

- _maps/RandomRuins/SpaceRuins/BlueMoon/forgotten_ship.dmm
- _maps/RandomRuins/SpaceRuins/BlueMoon/sol_ship.dmm
1) На сол версии базе использовались тайлы с воздухом в колбах с майнерами
2) На сол версии и интек версии были включены сифоны из токсинной, приводящее к утечке газа
Уменьшение утечек плазмы на каждой из баз
> Фикс газмайнеров на Интек базе и Сол версии

- _maps/map_files/Deltastation/DeltaStation2.dmm
Даже тут попилили бюджет и вместо цокола с лампой дали просто корпус без проводов и лампы
Да будет свет у парамедиков
> Фикс света у парамедиков на дельте

- _maps/map_files/PeaceSyndicateStation/PeaceSyndicateBoxStation.dmm
- _maps/map_files/SyndicateStation/SyndicateBoxStation.dmm
Вырезание спавнера угроз из 3 дормы на синди станции (на обычном боксе уже вырезано)
Уменьшение кринжовых ситуации с упавшим на голову когтём секса
> Вырезание спавнера на синди станции

- modular_sand/code/modules/pixel_shift/pixel_shift.dm
Баг с остаточным пиксельшифтом, конечно, из-за ограничений, сохраняется, но теперь нельзя подвинуть камеру при пиксельшифте больше допустимого
Костыли против багоюзеров
> Фикс возможности бесконечно менять положение при помощи пиксельшифта

- modular_bluemoon/code/game/objects/items/fleshlight.dm
1) Теперь при использовании портального фонарика через эмоуты первоначально придётся выбрать прозвище которое будет отображаться вместо имени.
2) Если прозвище не будет выставлено - оно выставится из случайного цвета + названия случайной планеты.
Люди жаловались, что им неуютно
> Прозвища во время использования портального фонарика

- _maps/map_files/BoxStation/BoxStation.dmm
- _maps/map_files/MetaStation/MetaStation.dmm
Мелкие изменения карт.
1. Бокс переделан снова: кабинет СМО расширен, улучшен офис парамедов. Исправлены зоны у турбины. Рации с КПП отделов перенесены на столы, добавлена консоль с камерами, отсутствовавший вендор одежды и шкафчик.
2. На Мете исправлены зоны у турбины.
Шлифовка
> Box&Meta Station фиксы 

- _maps/map_files/MetaStation/MetaStation.dmm
Один из столов до этого был закрыт мусоркой и компом, теперь оно так не делает и можно спокойно взять игрушку
Уменьшение багов маппинга из-за недоступных для использования столов
> Обновление офиса кма для избежание недоступных турфов

- _maps/map_files/generic/CentCom.dmm
Часть деревье на цк слое не отображалось, сколько там пытались использовать конкретные деревья, добавляя к этому случайное число и по итогу делая спрайт невидимым.
Теперь те деревья на цк слое видимые, хоть и случайные
Невидимые преграды на цк в виде деревье, теперь они видимы
> Фикс деревьев на цк слое

- _maps/map_files/generic/CentCom.dmm
Из-за ленивого копипаста они назывались медбеем
Вип камеры теперь вип камеры
> Ренейм вип комнат для заключённых у слейверов

- _maps/map_files/BoxStation/BoxStation.dmm
- _maps/map_files/Deltastation/DeltaStation2.dmm
- _maps/map_files/MetaStation/MetaStation.dmm
- Фиксы мусоропровода согласно [отчёту ](https://discord.com/channels/875735187449847830/1136948085923270676/1329200401475440660)в блок-маппинга.
- Гидропоника получила расширение и реновацию интерьера. Подробнее по посту победившего [голосования](https://discord.com/channels/875735187449847830/1214898953275834418/1329153764279713802). 
Из не показанных изменений:
- Биогенератор и гриндер смещёны вправо, на их месте вендоматы ботаника.
- В подсобке выше смещён напротив шлюза кеммастер ботаника, что удобнее. 
- В расширенном участке добавлен огнетушитель и статус-дисплей для красоты.
- Заменены укреплённые окна на обычные в: ассистентской, меде, у инфинити дорм, в техах, аналогично другим картам.
- Изменения виро согласно [багрепорту](https://discord.com/channels/875735187449847830/13295358 …
> Реновированная гидропоника Дельты + фиксы карт

- code/modules/uplink/uplink_items/uplink_bundles.dm
Теперь контрактор кит требует 50 игроков (Что дозволит режиму быть или лайтом с большим количеством игроков, или медиумом с околоминимальным для него) для появления в аплинке, вместо 25.
Соответствующая [предложка](https://discord.com/channels/875735187449847830/1329888659922751568/1329888659922751568) по ограничению кита в лайт (Собрала 10 лайков и 0 дизлайков за почти сутки).
Лично обжёгся о то, что при полтора инвалидах на СБ, те не смогли отреагировать и спасти меня от контрактора в лайт, которому по контракту надо заниматься той или иной резнёй, для лайта недопустимой. Игроку админы пояснили, что так не надо, но ПР будет профилактикой подобного в целом.
> Ограничение contractor kit в динамик лайт

- _maps/map_files/BoxStation/BoxStation.dmm
Шлюз ксенобио теперь закрывается. Должно было идти к крупному фиксу карт, не успел докоммитить перед мерджем.
> Фикс шлюза

- _maps/map_files/PeaceSyndicateStation/PeaceSyndicateBoxStation.dmm
- _maps/map_files/SyndicateStation/SyndicateBoxStation.dmm
-1 спавнер угроз в дормах
+2 спавнера угроз в техах
перенос спавнера дженерик ивентов из дорм в аркадную
Лучше не трогать тех, кому это не сдалось
> Перенос спавнеров ивентов чуть в более ликвидные места на синди бокс станции

- code/modules/food_and_drinks/drinks/drinks.dm
После попадания пули (поцелуя или чего-то такого) по бутылке она теперь реально крошится на разбитую бутылку, сколько до этого оно это делало без удаления бутылки
Багфикс
> Удаление бутылки при выстреле

- code/datums/ruins.dm
- code/modules/mapping/ruins.dm
- modular_splurt/code/datums/ruins/space.dm
К map_templates/ruin было добавлено свойство variants
variants - список названий файлов возможных вариантов карты
При генерации forced руин, если список вариантов определен, выбирается один из них или сама изначальная карта.
Части карт обычных руин могут выбираться динамически при генерации, forced руины же в процессе выбора не участвуют, а иногда хотелось бы.
> Вариация карт forced руин

- modular_splurt/code/modules/reagents/chemistry/reagents/other_reagents.dm
1) Водка у персонажа с русским духом не метаболизировалась (тоесть находилась в организме до ближайшего диализа)
2) Травма божественного говора не покидала персонажа даже после окончания наличия водки в организме
Багфиксы
> Фикс Русского духа и водки

- _maps/map_files/Deltastation/DeltaStation2.dmm
- code/datums/weather/weather_types/radiation_storm.dm
1) Общественный принтер теперь на столе в библиотеке в открытом месте, а стеклянная дверь ведущая до него до этого теперь на доступе библиотекаря (теперь его "рубка" вновь закрыта со всех сторон)
2) Камера во второй операционной теперь есть (ваши грязные делишки теперь видно.
3) В техах комнаты (см 1) теперь имеют защиту от радшторма
4) Just in case перепроверена работа шатлла на лаваленд у сб, теперь оно точно не врезается в комнаты заключённых
Багфиксы и добавление непродуманных моментов
> Фиксы Дельта Станции

- _maps/map_files/BoxStation/BoxStation.dmm
- _maps/map_files/CogStation/CogStation.dmm
- _maps/map_files/Deltastation/DeltaStation2.dmm
- _maps/map_files/KiloStation/KiloStation.dmm
- _maps/map_files/LambdaStation/lambda.dmm
- _maps/map_files/MetaStation/MetaStation.dmm
- _maps/map_files/PeaceSyndicateStation/PeaceSyndicateBoxStation.dmm
- _maps/map_files/PubbyStation/PubbyStation.dmm
- _maps/map_files/SyndicateStation/SyndicateBoxStation.dmm
1) Теперь реквест консоли в чекпоинтах сб отсылают к отделу для которого они чекпойт, а не просто Security
2) на части карт были пофикшены совсем конченные расстановки реквест консолей (не с той стороны стены, внутри стены, за 2 тайла от стены) 
Багфиксы и упрощение восприятия игры
> Фикс реквест консолей на чекпоинтах сб

- _maps/map_files/BoxStation/BoxStation.dmm
1) Кнопка управления ставнями в гейте теперь на доступе глав как на других станциях (Рд может эти ставни открыть)
2) Кнопка сауны в дормах теперь запирает двери
Фиксы неправильных кнопок
> Фиксы на бокс станции

- _maps/RandomRuins/SpaceRuins/BlueMoon/space_syndicate_base.dmm
- _maps/RandomRuins/SpaceRuins/listeningstation.dmm
- _maps/map_files/Mining/Lavaland_novaya.dmm
1) Фикс невозможности перетащить раздатчики на ДС-1 ДС-2 и станции прослушки
багфиксы
> Фикс невозможности переставить раздатчики на синдибазах

- _maps/templates/apartment_prison.dmm
- modular_splurt/code/game/machinery/research_table.dm
1) Секс стол в инф дормах (тип: тюрьма) заменён со слейверского на обычный
2) Секс стол находясь на цк слое (гост кафе) не даёт очки при оргазме (если не слейверский)
Фикс абузов
> Фикс абуза секс стола в гост кафе

- _maps/map_files/Deltastation/DeltaStation2.dmm
- _maps/map_files/MetaStation/MetaStation.dmm
1) Убрана гермодверь в ксенобиологии стоящая непойми как и не закрывающая вообще ничего
2) Изменён доступ в комнату парамедиков с техов на мед доступ (был доступ на генетика (да))
3) Изменён доступ в медбей через теха на мед доступ (был доступ мед, генетика и теха (теперь нельзя зайти в мед без доступа через теха)
4) Изменён доступ в офис сб через главные двери на доступ охраны и детективов (было на "бриг" (оно нужно для пермабрига и камер) и детективов)
5) Дверь в офис юриста на непрозрачную версию (для ликвидности использовать приватных створок) (так-же это сделано и на Дельте)
Изменение доступов на более подходящие и сопутствующие фиксы карты
> Фиксы карты Мета

- _maps/RandomRuins/SpaceRuins/listeningstation.dmm
- code/modules/ruins/lavaland_ruin_code.dm
- modular_bluemoon/Ren/Code/mobs.dm
- modular_splurt/_maps/RandomRuins/SpaceRuins/syndielistenspace.dmm
1) имел шанс быть заспавниться интековец вместо слипера агента прослушки синдикека
багфиксы
> Фикс спавна интековца вместо синди слипера для гостроли

- _maps/RandomRuins/SpaceRuins/BlueMoon/space_syndicate_base.dmm
1) У всех апц доступ переставлен на синдикатский (теперь их не нужно взламывать)
2) Кухня переделана в более удобной компановке и убраны 2 дипфраера (серьёзно 3 дипфраера при 1 микроволновке)
3) В рнд добавлена створка для окон
4) Мостик и офисы адмирала и (второго чувака от него) передизайнены в понимании, что комнаты устроены для удобства
5) Клёвый пингвин в шляпе с текилой, в шляпе и с текилой!!
6) Столовая переделана в бар и диско шар заменён на приогрыватель (ибо диско шар был оверкилом)
7) в карго в одним из ящиков лежит куча кустов которые расставлены на дс-2
8) переработка дорм дс-2
9) добавление под капсулы заключённых вр слиперов
10) добавление диктофона и кассет для неё в допросную
Редизайн ДС-2 с целью сделать его более приятным для пребывания не требующим ежераундового …
> Частичный ремап ДС2

- code/game/objects/items/storage/boxes.dm
- code/modules/food_and_drinks/food/snacks_other.dm
1) Обычная жвачка теперь обычная (до этого вместо неё спавнилась бублёвская жвачка)
2) Почищен нерабочий код жвачки бубли (галлюцинации в принципе не работали)
3) Кровь в жвачке бубли заменена на O-
4) Есть есть жвачку бубли высокий шанс словить галюны - если-же просто есть жвать (держать в слоте маске) - такого эффекта не будет
5) Кровососы не получают галлюцинации от жвачки
Багфиксы и улучшение кода
> Фикс жвачки

- _maps/map_files/BoxStation/BoxStation.dmm
- _maps/map_files/MetaStation/MetaStation.dmm
1) переработка пола в парке Меты во избежание неразбираемого пола
2) Добавление вентиляции в парке
3) замена мусорок на мусорные баки с мусоропроводом
4) огнетушители с пожарной тревогой в парке Меты и Бокса
5) Добавление пожарных створок на двери в парке Меты и Бокса
Интеграция парка в экосистему станции и мапфиксы
> Ремап парка на Мете

- code/game/objects/structures/ghost_role_spawners.dm
- modular_bluemoon/Fink/code/items/summon_chalk.dm
- modular_bluemoon/code/game/objects/structures/ghost_role_spawners.dm
- modular_bluemoon/vlad0s_staff/code/ghost_role_antag_datums.dm
- modular_sand/code/game/objects/structures/ghost_role_spawners.dm
- tgstation.dme
1) Возможность призвать посетителей гост кафе с квирком призываемый
2) Данное действие отрубает все гост кафешные абилки, убирает  маскировку и так убирает возможность слышать гостов
3) Возвращение на руне возвращает все абилки обратно если они до этого были
4) Теперь возможность дегостокафецировать, убрав у поситителя гост отеля все его абилки от спавна на данной роли (для админов)
Призываемый - ерп квирк, призываемый даже из гост кафе с собой вещей иметь не будет и вреда это никому не причинит, особенно в эксту в которую квирк и работает
> Возможность адекватно призывать персонажей из гост кафе с квирком призываемый

- code/modules/mod/mod_theme.dm
В соответствии с предложкой https://discord.com/channels/875735187449847830/1329547561232633947 Были улучшенны МОДы Капитана/ГСБ/СБ/Синдиката (В том числе и элитный) что бы иметь возможность хоть как то конкурировать с их аналогами ввиде РИГов и других элементов брони которые легко можно получить другими путями в отличие от МОДов. Которые требуют больше усилий  и предлагали меньше защиты.
Данные МОД костюмы имели незаслуженно низкий показатель брони что делает их бесполезными в сравнении с их аналогами которые легче достать и которые являлись более эффективными в бою.
> Buffed Mods

- code/modules/food_and_drinks/kitchen_machinery/microwave.dm
1) Из-за отсутствия у мобхолдера icon из-за использования вместо неё appearance отображение микроволновки ломалось
Багфиксы
> Фикс отображения микроволновки и моб холдеров

- code/modules/mob/living/carbon/human/species.dm
1) Недышащий Регенерирующий персонаж в крите не умирает от крит урона
Изменение связано с тем, что регенерирующий персонаж легче выходит из крита чем недышащий регенерирующий 
Синергия для квирков
> Бафф синергии Регенерирующего и Недышащего 

- code/datums/components/twohanded.dm
Фикс безвредного рантайма завязанного на двойном выкидывании оффэнхда двуручного оружия при уходе в крит
Фикс рантайма
> Фикс рантайма при выпадении вещей из двух рук если это двуручное оружие

- code/game/machinery/autolathe.dm
- code/modules/research/destructive_analyzer.dm
1) пофикшен баг невозможности за борга (из-за отсутствия интента дизарм) разобрать аутолат и анализатор
2) требование выборать дизарм нужно только для анализатора из всех научных штук (протолат, принтер плат и тд)
Багфиксы
> Фикс невозможности за борга разобрать рнд оборудование

- modular_citadel/code/modules/reagents/chemistry/reagents/fermi_reagents.dm
1) При отсутствии у моба mind не рантаймит и не генерить котов из кукол
2) Если кот был в руках или вовсе в сумке на момент превращения обратно в хумана - появляется в турфе где находился, а не удаляется из реальности 
Багфиксы
> Фикс secretcatchem и удаление из-за него из реальности

- _maps/RandomRuins/SpaceRuins/BlueMoon/space_syndicate_base.dmm
1) Случайные постеры изменены на выставленный относительно зоны (и добавлены кучу постеров тут и там)
2) Офис мастера по оружия расширен, добавлена камера слежки за станцией и добавлен всякий флафф на антуража
3) "Казарма" офицеров брига уменьшена, но добавлены кровати и помещение теперь более вписано и не остаётся мёртвым местом когда криокапсулы будут удалены после захода за них
4) В комнату фитнеса добавлен колор-мэйт
5) Комната адмирала расширена за счёт холодильника меда и куска волта, меж тем вернулся контроллер турелей, но теперь рабочий
Переработка пространства ДС-2 и увеличение антуражных вещей и мелочей
> ДС-2 ещё больше ремапа

- _maps/map_files/MetaStation/MetaStation.dmm
1) Инжектор не был рабочим из-за отсутствия энергии сколько он был в зоне космоса
Мапфикс
> Фикс неработающего инжектора

- code/modules/client/preferences.dm
Актуализатор не чистил старые арты персонажа из-за чего при переносе с префов оны добавлялись поверх, вызывая по 6 артов и так далее
Багфиксы
> Фикс арта персонажа и актуализатора

- modular_splurt/code/modules/mob/living/simple_animal/friendly/mouse.dm
Перенёс взрывомышь в спавн АГРЕССИВНЫХ мобов (Ибо мирные мобы уж точно не должны взрываться С ПЛАЗМОЙ тем самым нанося огромный вред отделу)
Это не логично? Сплюрты опять натворили откровенной дичи? Мобы которые появляются из жёлтого экстракта при использовании воды в априори не может являться опасными или агрессивными 
---
> Фикс взрывоопасной мыши

- _maps/map_files/MetaStation/MetaStation.dmm
1) Доступ через тека в холодильник повара теперь на доступе повара
2) Доступ на выход из сервисного холла в теха теперь и с доступом уборщиком
3) Стекло около микроволновок заменено на тряпочку
4) Молоко со стойки бармена перенесено к раздатчикам
5) Выключатель света коморки клоуна и мима теперь внутри их комнаты (до этого можно было выключить с техов) 
6) а ещё дверь на кухню заменена со стеклом
Мапфиксы
> Фиксы сервиса на Мете

- code/datums/components/omen.dm
- code/game/objects/items/fireaxe.dm
1) У проклятых прок их проклятья был каждое изменение кнока (очень часто особенно когда в теле медецина его меняющая), баг вызванный мёржом с апстримом (место с удалением сигнала было как-раз на подскальзывание)
2) У energized топора не было спрайта до взятия в обе руки
Багфиксы и играбельный проклятый
> Фикс проклятого и energized топора

- _maps/map_files/Mining/Lavaland_novaya.dmm
1) Убран второй стол на 1 тайле у дс-1
2) Добавлен пол в переходе между моргом и медом на дс-1
3) Стёкла заменены на спавнеры стёкл на дс-1
4) чуток перемаплен ксеноарх и убраны пара лишних декалей
5) На ксеноархе прибавилось вентиляции
Мапфиксы и украшательства
> Мапфиксы и ремаппинг на Лаваленде

- code/modules/mob/living/carbon/human/innate_abilities/coiling.dm
- code/modules/mob/living/carbon/human/species.dm
Дает персонажам с taur body == Naga (coiled), способность обвивать других, которая есть у обычного Naga варианта.
Для Naga туловища, ничего не поменяется, оно все так-же будет скручиваться при активации и раскручиваться, при отпускании.
Для Naga (coiled) туловище меняться не будет.
https://discord.com/channels/875735187449847830/1343580064989843577/1343580064989843577
Не очень логично, что выбор альтернативного скина хвоста наги, отнимает эту способность
> Персонажи с Naga (coiled) телом, могут использовать способность coiling

- _maps/RandomRuins/SpaceRuins/BlueMoon/space_syndicate_base.dmm
- code/game/objects/structures/fireaxe.dm
- code/modules/clothing/head/hardhat.dm
- code/modules/clothing/suits/utility.dm
Короче, сделал Атмос Фаерсьюты более полезными. Их можно складывать в сумку и носить с собой. Так же они теперь защищают от космического холода. Надеюсь они перестанут бесконечно и бесполезно лежать в шкафчиках.
Ну и на DS-2 добавил дальномерный газоанализатор и атмос водяной танк в шкаф к энерготопору.
Viva la Atmosia!
Атмос Фаерсьюты никто не носил никогда.
> Usefull Atmos Firesuit

- code/modules/mob/living/simple_animal/hostile/dark_wizard.dm
- modular_splurt/code/modules/mob/living/simple_animal/hostile/crazysci.dm
Теперь мобы удаляются, не давая экспедиторам дюпать себе по 20+ сабель и свитков
Теперь мобы удаляются, не давая экспедиторам дюпать себе по 20+ сабель и свитков (при помощи лазаруса)
Эти два предмета довольно имбовые и могут знатно подпортить людям динаму/эксту 
Нету
> Удаление мобов сумасшедшего учёного и тёмного мага при убийстве

- code/modules/mob/living/carbon/carbon_defense.dm
1) Пацифисты не ловят скрут рук от поглаживаний и бупов Отстраненных
привязано к пацифизму чтобы не делать точечную привязку на перчатки северных поглаживаний (перчатки для обниманий)
Загладить недотрог, хихишно
> Пацифисты и Отстраненность

- _maps/templates/apartment_3.dmm
- _maps/templates/apartment_beach.dmm
- _maps/templates/apartment_jungle.dmm
- _maps/templates/apartment_winter.dmm
1) Камни для заточки в инф дормах заменены на сточенные
Использование инф дорм ради бесплатного лута который должен быть ограничен в доступе
> Замена камней для заточке в инф дормах на использование

- code/modules/jobs/job_types/research/expeditor.dm
1) Именование главы было неправильным, вызывало баги у кровососателей на цели из рнд
багфикс
> Экспедиторы имели неправильное написание для рд

- _maps/RandomRuins/SpaceRuins/listeningstation.dmm
Мапер залепил на прослушку в космосе слипер офкома с Дюны. Не круто. Вообще не круто.
Поставил прослушников которые должны быть
> Поставил на посту прослушки правильные слиперы

- code/controllers/subsystem/ticker.dm
- strings/round_start_sounds.txt
https://github.com/tgstation/tgstation/pull/43836 основа откуда взято
1) сделал файлы заглушки чтобы сохранялись папки куда и скидываются тайтл скрины и музыка в лобби
2) вернул стандартную музыку в лобби если не было установлено ничего в config/title_music/sounds
фикс провалов юнит тестов и "прятки от законов"
поясняю 
музыку в лобби кидается в папку config/title_music/sounds
тайтлскрин в лобби кидается в папку  config/title_screens/images
> Смайли хватит трогать что-либо ничего не проверяя, ты удалил важные строки (unit-test fix PRIORITY MERGE)

- code/modules/jobs/job_types/service/chaplain.dm
Всё просто и крайне нужно. Теперь строчка с Религией может менять полностью название для Библии. Комментарии излишне
> Религия = Библия, без дополнительных

- code/__BLUEMOONCODE/_DEFINES/surgery.dm
- code/__DEFINES/traits.dm
- code/game/objects/structures/ghost_role_spawners.dm
- code/modules/jobs/job_types/brig/brigdoc.dm
- code/modules/jobs/job_types/command/chief_medical_officer.dm
- code/modules/jobs/job_types/medbay/chemist.dm
- code/modules/jobs/job_types/medbay/medical_doctor.dm
- code/modules/jobs/job_types/medbay/paramedic.dm
- code/modules/mob/living/carbon/carbon.dm
- code/modules/mob/living/carbon/human/human.dm
- code/modules/projectiles/projectile/bullets/pistol.dm
- code/modules/surgery/surgery.dm
- code/modules/uplink/uplink_items/uplink_roles.dm
- code/modules/vehicles/mecha/mecha_defense.dm
- modular_bluemoon/code/game/objects/structures/ghost_role_spawners.dm
- modular_bluemoon/code/modules/antagonists/ert/ert.dm
- modular_bluemoon/code/modules/research/designs/weapon_designs.dm
- modular_bluemoon/fluffs/code/melee.dm
- modular_splurt/code/modules/projectiles/projectile/bullets/smg.dm
1. Медроли: парамедик, медик, бригмедик, химик получили связанные с профессией трейты. СМО получил трейты парамедика и химика.
- Медики и бригмедики имеют пул операций, доступных раундстарт: тенд вундс адвансд + боди реджув.
- Парамедики быстрее затаскивают на спину лежачее тело даже без нитриловых перчаток.
- Химики различают реагенты без научных очков.
2. Бафф нитрилок и латексных перчаток: на полсекунды быстрее подъём на спину.
- 1.5 секунды нитрилки, 2.5 секунды латеекс, 2 секунды парамедик.
3. Бафф экспансивок 10-мм и гидрашоков .45-мм: бронепробитие. Для гидрошоков и урон тоже.
- 10 мм ХП: брнепробитие -50 стало -25.
- .45 гидрашок: бронепробитие -65 стало -20, урон повышен до 30, было 15.
4. Эмиттер карабин повысился в цене. Было 5, стало 13.
5. Фикс абуза инстапочинки мехов. …
> Квирки медбея + балансное

- code/modules/clothing/spacesuits/miscellaneous.dm
1. Риги инженеров ОБР (Синий код + ОБР инжей) имеет, за счёт небольшого штрафа брони, защиту от огня 100 и огнестойкость уровня рига СЕ.
2. Риги ОБР медиков получили медХУД как у рига медиков.
Логика для ОБР, особенно если инженеры были заказаны за 240 тысяч.
Не нужно. Слишком мелочные чейнджи, я протестил.
> ОБР Риги инженеров теперь устойчивы к огню; ОБР медиков имеют медхуды

- code/__DEFINES/traits.dm
- code/modules/jobs/job_types/command/research_director.dm
- code/modules/jobs/job_types/research/roboticist.dm
- code/modules/vehicles/mecha/mecha_defense.dm
- modular_bluemoon/code/game/objects/structures/ghost_role_spawners.dm
- modular_bluemoon/code/modules/antagonists/ert/ert.dm
- modular_splurt/code/game/objects/structures/ghost_role_spawners.dm
Создал и добавил трейт на быструю починку мехов. 
- Трейт даёт при починке сваркой меха КД на руки 1, у всех остальных 2. Обычный КД на руки равен 0.8 секунды.
- Трейт получил робототехник, РД, инженеры ОБР и гостроль учёного ДС-2.
Дополнение логики, что мех-related роли должны быть квалифицированными для работы с ними.
Мелкое изменение, не требуется.
> Трейт для быстрой починки

- code/datums/martial/krav_maga.dm
БИ Крав Мага:
- Добавлен стан-паралич (Как у slam CQC) на 1.2 секунды при подсечке.
- Баффнут оксиурон от приёма дыхалки с 5 до 10.
Попытка баффа крав-маги, оговорено с СА. 
Попытка сделать их более привлекательным выбором за счёт стана и оксиурона.
Без надобности. Нужен плейтест игроками.
> Бафф крав-маг

- code/modules/reagents/chemistry/reagents/medicine_reagents.dm
Криоксадон больше не лечит, если цель не спит. Лучше тест-мержем.
Запрос СА. Балансная мера для антагов, против криоксадоновых одетых в MOPP СБ офицеров.
Было в админчате.
> Ребаланс криоксадона

- code/datums/ert.dm
- code/modules/antagonists/ert/ert.dm
- code/modules/security_levels/security_levels.dm
- modular_bluemoon/code/datums/ert.dm
- modular_bluemoon/code/modules/antagonists/ert/ert.dm
1. ОБР ролям добавлено контекстное окно с информацией вместо нагромождения строк, как у экипажа по прилёту/спавну раундстарт на станции.
3. Эта информация была локализирована. От меня добавлена информация про канал ЦК в наушнике.
4. В ряде мест подправил капитализацию, где она мешала и исправил ряд локализаций.
5. Включил ролям-лидерам ОБР переменную leader для if условия описаний.
Огромный QoL срочникам и визуальная эстетика любителям ОБР ролей.
[Тут](https://discord.com/channels/875735187449847830/1053678815714484384/1365524099589476394)
> Окно информации для ОБР 

- code/datums/mood_events/generic_positive_events.dm
- code/game/sound.dm
- modular_bluemoon/code/datums/mood_events/generic_positive_events.dm
- modular_bluemoon/code/datums/traits/neutral.dm
- Переход с системы псевдорандома на таймеры: лучше контролируемость, меньше нагрузки на сервер.
- Фикс воспроизведения завывания сквозь стены. У нас, оказывается, 95% звуковых эмоутов не проходит сквозь стены.
- Развернутое описание важных деталей работы кода.
- Перенос части кода в модульные файлы.
Тестовый морж.
> [BLUEMOON] Фикс квирка "Неконтролируемый вой"

- modular_splurt/code/modules/projectiles/guns/ballistic/automatic.dm
Больше нельзя нацепить глушитель на Old FTU rifle (,308), чтобы не пропадал спрайт.
[Багрепорт](https://discord.com/channels/875735187449847830/1364954490477744128/1364954490477744128)
Не нужно
> Old FTU suppressor fix

- code/game/objects/effects/decals/decal.dm
1) фикс того, что декали поворачиваются за турфом при спавне
Фикс кривых декалей когда при маппинге всё окей
> Фикс декалей на турфе

- code/_rendering/atom_huds/data_huds.dm
Медхуд полоской ХП не показывается при условии 100% здоровья и выше.
Фильтрация ненужной интерфейсной информации медикам при условии, что они будут обращать внимание на раненых благодаря раздражающей зелёной полоске. Полностью здоровые же будут без неё вовсе.
> MedHud HP полоска не видна при 100% здоровья 

- _maps/map_files/BoxStation/BoxStation.dmm
- _maps/map_files/MetaStation/MetaStation.dmm
- _maps/map_files/SyndicateStation/SyndicateBoxStation.dmm
- Добавлены флажки доступа изнутри комнаты для шлюзов, чтобы спавнящиеся раундстарт внутри игроки могли выйти из комнаты.
- Хирургия и клонёрка тоже получили эти флажки, чтобы люди не застревали в комнатах.
- Гравген Меты теперь требует инженерные общие доступы. Для доступов инженеров к гравгену.
Люди спавнились, орали, плакали что их замуровали демоны, и писали атикеты.
> Общие доступы изнутри сервисхолла Бокса

- code/_onclick/hud/screen_objects.dm
- modular_bluemoon/code/modules/mob/say_vr.dm
- Починка бинда для "Subtler Anti-Ghost Emote (with indicator)"
- Починка сплюртовского неправильного применения функций. Ломало пару предметов.
> [BLUEMOON] Микрофиксы

- modular_bluemoon/code/modules/client/loadout/backpack.dm
- modular_sand/code/game/objects/items/fleshlight.dm
- modular_splurt/code/modules/client/loadout/donator/first_tier.dm
Вместо полной замены имени у портального фонарика/дилдо и трусиков/маски теперь используется функция replacetext()
Портальный фонарик добавлен в общий лодаут.
Все, что мне только пришло в голову, проверено на локальном сервере.
> Portallight in loadout and replacetext update

- code/controllers/subsystem/autotransfer.dm
- code/controllers/subsystem/vote.dm
- modular_bluemoon/code/controllers/subsystem/vote.dm
- modular_bluemoon/code/modules/mob/mob.dm
- tgstation.dme
Добавлена система веса у игроков в голосованиях в зависимости от роли игрока в раунде. Взято с [TauCeti](https://github.com/TauCetiStation/TauCetiClassic) + адаптированно.
0.5 - Призраки (+ мертвецы, мышки, микродрончики, недавно появившиеся персонажи)
1 - Обычные игроки
2 - Антаги и главы
Работает на PLURALITY_VOTING (выбор одного) и APPROVAL_VOTING (мультивыборка).
Пока что включено только на автоголосовалку для вызова шаттла.
Тестмерж обязателен.
> [BLUEMOON] Vote power difference

- modular_bluemoon/code/game/objects/items/summon_chalk.dm
1) призываемый, призванный из инфинити отеля возвращается в турф где находится сфера отеля, вместо отправки в космос сколько в момент покидания последнего персонажа из комнаты, та сворачивается
2) призываемый теперь не раздевается автоматически при телепортации, а вместо этого его пояс и рюкзак прячутся в руну, а остальные предметы помечаются, и при возврате персонажа при помощи руны возврата, с того снимаются все вещи, которые не были на нём до телепортации и вместе с тем все вещи, которые были с ним до телепортации оказываются у того под ногами вместе с рюкзаком и поясом.
Багфиксы и дополнительные фичи для взаимодействия и отыгрыша
> Ещё больше улучшений призываемого

- modular_splurt/code/datums/traits/neutral_quirks/headpat_hater.dm
Иконка теперь будет меняться на другую при активации, что бы сразу видеть активность квирка, не шифткликая и не активируя повторно.
> headpat hater icon QOL

- code/datums/elements/strippable.dm
- code/modules/clothing/neck/_neck.dm
- modular_bluemoon/code/game/objects/items.dm
- modular_bluemoon/code/game/objects/items/fleshlight.dm
- modular_bluemoon/code/modules/clothing/neck/_neck.dm
- modular_sand/code/game/objects/items/fleshlight.dm
- modular_splurt/code/game/objects/items/lewd_items/genital_equipment/chastity/chastity_belt.dm
- modular_splurt/code/modules/mob/living/carbon/carbon.dm
- tgstation.dme
- Одежда, закрывающаяся на замок, могла быть снята другими игроками через интеракривное меню снимания предметов, а также через срыв одежды с помощью панельки. Теперь эта одежда имеет статус NO_DROP, закрывающий данную проблему.
- Была разработана механика применения предметов к избранной одежде, которую носит другой игрок, чтобы, например, открывать ключом замок на одежде другого игрока.
- На данный момент механ и данная правка касаются только: ошейника к замком, портальных трусов, пояса верности. Также ошейник и трусы можно закрывать заранее перед надеванием на игрока, после экипирования предмета замок закроется.
Тестмерж обязателен.
> [BLUEMOON] Фикс одежды с замком

- code/modules/mob/living/living.dm
- modular_bluemoon/code/datums/interactions/interaction_datums/lewd/tail.dm
- modular_sand/code/datums/interactions/_interaction.dm
1) переписан (опять) код проверки на хвост, все тавры считаются хвостатыми, а хвост проверяется правильно (не будет фантомных хвостов)
2) добавлены сердечки при обнимания хвостом и сплетении хвостами, а сам текст теперь розовенький
багфиксы и доработки
> Доп фикс проверки на хвосты и чуток доделка взаимодействий

- code/_rendering/atom_huds/data_huds.dm
- code/modules/research/designs/machine_desings/machine_designs_medical.dm
- Платы для хим штук теперь свободно печатаются в РНД. Обговоренно с администрацией, по задумке НРП они всегда имели право это делать. "Code issue" - исправлено.
- Исправлена полоска здоровья на мед худах после применения различных множителей к здоровью.
> [BLUEMOON] Микроправки

- code/modules/research/techweb/nodes/bluespace_nodes.dm
- code/modules/research/techweb/nodes/medical_nodes.dm
- code/modules/research/techweb/nodes/tools_nodes.dm
- code/modules/research/techweb/nodes/weaponry_nodes.dm
- modular_sand/code/modules/research/techweb/nodes/all_nodes.dm
- modular_splurt/code/modules/clothing/suits/heavy.dm
1. Дополнен порядок исследования инструментов:
- Ноды инструментов: меда, инженеров и уборщика требуют ноду basic_tools (С обычными инструментами из автолата).
- Первая нода оружия с тренировочными пинами требует sec_basic ноду с болами и наручниками.
2. Блюспейс лампозаменитель перешёл в ноду Advanced Janitoring. Упомянутая нода требует practical_bluespace ноду для исследования.
3. Правка порядка путей id в CBRN ноде.
1. "Мы можем изучить дрель, не зная, как печатать отвёртку". Также это правит порядок в списке крафтов протолата и простые инструменты никогда не будут под продвинутыми.
2. Логика: лампозаменитель и обычный спрей есть в базовой ноде инструментов уборщика, в адвансд есть спрей, но без блюспейс-лампозаменителя. К тому же теперь блюспейс потребует блюспейс-ноды, как это и …
> Ревизия нод исследования: инструменты

- code/modules/reagents/chemistry/reagents/drink_reagents.dm
- code/modules/reagents/chemistry/reagents/food_reagents.dm
Ряд напитков из вендоматов получили влияющее на муд куклы качество (`quality`): 
- Dutch Hot Coco (Качество 1 уровня), 60 кредитов
- Royal Forest Tea (Качество 2 уровня), 100 кредитов.
- Shambler's Juice (Качество 2 уровня), 100 кредитов
Попытка сделать затраты экипажа на горячий шоколад (Который греет хуже чая в вопросе метаболизма, но дороже кредитами) и прочие напитки более рентабельными механически.
Для понимания, уже были напитки вроде Nuka Cola за 100 кредитов, что имели качество 2-го уровня для повышения муда. Теперь их будет чуть больше.
Не требуется.
> Присвоение ряду вендомат-напитков mood-качества  

- modular_splurt/code/datums/genitals/genitals_interface.dm
Теперь можно не только вставлять игрушки в Genitals menu при режиме "Всегда доступно", но и доставать. Что логично собственно
> Get out sex toys

- code/modules/paperwork/paper.dm
Это позволяло недобросовестным игрокам переименовать бумажку в какой-нибудь неправильный хтмл запрос который крашит чат при любом упоминании бумажки (даже поджигание её)
багфикс
> Фикс возможности запихнуть в название бумажки хтмл

- _maps/RandomZLevels/away_mission/ihategordon.dmm
Удалил пилоны зена с карты
Слишком имбалансная фича для мобов, которая работала слишком некорректно и мешала прохождению гейта
> Удаление пилонов зена с гейта чёрной мезы

- code/controllers/subsystem/vote.dm
Список карт в голосне перетасовывается. Никаких боксмет в начале списка. Больше вариативности карт когда игроки на похуй протыкивают первую карту в списке.
> [BLUEMOON] Карты в случайном порядке

- code/controllers/subsystem/research.dm
- code/modules/research/server.dm
1) количество рнд серверов теперь влияет на количество генерируемых очков, базовая конфигурация 2 сервера генерирует 28 очков, каждый последующий сервер делает общий модификатор серверов по sqrt(100 / (количество серверов)), от чего эффективность сильно падает вниз с каждым новым сервером, однако это балансируется тем, что сервера можно улучшить, с тир 4 деталями при конфигурации 2 сервера выходит 50 очков
(ранее генерировалось ровно 35 и точка)
2) рнд сервера потребляют энергию (500 ватт)
фиксы кода (система не работала) и доработка кода и фич
> Сервера теперь работают (в рнд)

- code/datums/diseases/advance/symptoms/sneeze.dm
- code/datums/status_effects/debuffs.dm
- code/modules/events/fake_virus.dm
- code/modules/mob/living/emote.dm
- code/modules/vore/eating/living.dm
- modular_bluemoon/SmiLeY/code/serverside/emote_panel.dm
- modular_bluemoon/code/modules/mob/living/emote.dm
Добавил новый эмоут snuffle (Шмыгать носом). Эмоуту sniff прописал действие "Нюхает".
Все авто эмоуты sniff в контексте "Шмыгает" (при болезнях), заменил на snuffle. Добавил snuffle в панельку.
При обнюхивании из Vore панельки теперь будет эмоут sniff.
При облизывании из Vore панельки теперь будет звук, как при облизывании языком. А так-же задержка.
Эмоут sniff  в большинстве случаев юзается как "Нюхать", а не как "Шмыгает носом", второе лишь автоматически при болезни. Адекватный перевод, что бы звучало красиво, подобрать у меня не получилось, так что добавил его вариацию, как посоветовали. Добавил в Vore панельку, ибо логично + визуально помечает действие, а не только мелким шрифтом в чатике
> snuffle add + vore updt

- code/__DEFINES/say.dm
Повышает лимит на флавор вкуса/запаха в vore панельке. Точнее уравнивает лимиты.
В описании при установке указано 400 символов, дефайн в vore файле стоит 400, а дефан при сохранении на 40. Фиксим баг
> vore flavor fix

- modular_sand/code/modules/surgery/organs/augments_arms.dm
Продвинутый имплантат инструментов давал Т5 алиенки, не адванседы. Исправляем это под репликацию технологии абдукторов.
Хороший человек уведомил, дошлифовываем переделку Т5.
Не думаю, что нужно.
> Advtools implant фикс

- code/modules/ambitions/ambition_objective.dm
Теперь амбиции на локалке и при одном игроке на сервере не рантаймят. Возможно.
Исправление редкого бага. Почему бы и нет.
> Убираем рантаймы в амбициях

- code/__BLUEMOONCODE/_DEFINES/traits.dm
- code/datums/brain_damage/imaginary_friend.dm
- code/modules/awaymissions/corpse.dm
- modular_bluemoon/code/datums/brain_damage/imaginary_friend.dm
- modular_bluemoon/code/datums/traits/neutral.dm
- tgstation.dme
- tgui/packages/tgui/interfaces/SpawnersMenu.js
1) добавлен квирк на воображаемого друга
2) пофикшен баг, что воображаемый друг видел от своих глаз (мог смотреть за стены)
3) теперь вместо предложения сыграть гостам за воображаемого друга появляется гост слот который можно выбрать через меню спавнеров
4) за воображаемого друга можно зайти за своего персонажа
5) ну и дабавлен таб в спавнер меню для травм (может кто решит ещё и сплит персоналити так-же сделать)
Круто прикольно и вообще Mrowl платный запрос висящий непойми сколько
> Квирк на воображаемого друга

- _maps/RandomZLevels/away_mission/TheBeach.dmm
- _maps/map_files/MetaStation/MetaStation.dmm
- _maps/splurt_maps/map_files/4Nalstation/4NaL_Station.dmm
Пляж:
1) гейт пляж не делает дублирование сообщений в рацию
Мета:
1) чуток подправлен кабинет психолога, добавлена лампочка в его спальню
2) переставлены вендоматы чтобы не делать неказистую пустоту в прибытии
3) добавлено пара ламп в прибытии ибо там темень
4) теперь створки на кухню можно закрыть (был прописан неправильно доступ на них)
4нал:
1) переставлены барные знаки чтобы они глупо не выпирали из стены (у нас нет диров чтобы они были боком)
мапфиксы
> Ещё пачка фиксов по картам

- code/modules/arousal/arousal.dm
- modular_sand/code/modules/arousal/arousal.dm
- Менюшки в IC -> Climax переделаны под радиальные
- Теперь учитывается, если у органа стоит признак всегда доступен.
- Интеракции теперь не требуют граба, достаточно быть рядом.
- Уменьшил КД до секунды, ибо с радиальными меню, спамить не получится
- Остальную логику я не трогал.
- Протестировано на локалке, на 3х клиентах. **Но пускай в тестмердже повисит денек-два.**
https://discord.com/channels/875735187449847830/1394154862765412475
> climax updt

- code/game/objects/items/devices/radio/electropack.dm
- code/game/objects/items/robot/robot_items.dm
- code/modules/arousal/arousal.dm
- code/modules/mob/living/carbon/human/species.dm
- code/modules/vore/eating/living.dm
- modular_splurt/code/_onclick/observer.dm
- modular_splurt/code/datums/traits/positive_quirks/bloodfledge.dm
- modular_splurt/code/game/objects/items/lewd_items/genital_equipment/chastity/estim_chastity_cage.dm
- Трейт мазохизм теперь дает lust при уроне, а не заставляет кончать с рандомным шансом
- Трейт мазохизм теперь дает lust при ударах по заднице, а не заставляет кончать с шансом 10%
- Пофикшена E-Stim клетка, она корректно накапливает lust при стимуляции, и в зависимости от мазохизма при шоке
- Трейт мазохизм теперь дает lust от шокового ошейника, по аналогии с E-Stim клеткой
- Небольшой рефактор префов на запах/вкус, перенес проверку в общий прок.
> maso and trait updt

- _maps/map_files/BoxStation/BoxStation.dmm
1) у кнопки в переговорной была привязка к шаттерсом кма (упс)
2) поправлены зоны около телекомов
мапфиксы
> Бокс фикс шаттерсов в переговорной на боксе

- code/game/objects/items/miscellaneous.dm
- modular_bluemoon/code/modules/vending/games.dm
- Перевел выбор из любого маяка призыва (включая коробку игрушек) на TGUI
- Для коробки с игрушками добавил на ALT радиальное меню (вообще, можно и всем прикрутить его, вопрос нужно ли).
- Добавил 5 простых коробок с игрушками в премиум сегмент FUN вендора (по логике, что 5 коробок, игрок может залутать из 5 инфинити комнат, а так просто купить)
Круто и удобно. Можно посмотреть все игрушки за раз и выбрать.
> plushes box menu updt

- code/game/machinery/porta_turret/portable_turret.dm
Древнее зло было побеждено
Этому багу 4 года, начиная с коммита f2343b3
*На скринах английская локализация ибо я шаманил с отрывками кода, в ПР'е перевод остаётся*
> Быстрый фикс бага с починкой турелей

- code/game/objects/items/storage/bags.dm
Пофиксил отображение предметов в мусорном мешке. Раньше он показывал только последние 3/5 предметов и без счетчика кол-ва предметов внутри. Из-за чего вообще не понятно, сколько всего предметов и какие там они.
Мешком тупо не удобно было пользоваться, я ХЗ зачем это добавили, причем это единственный предмет, где такое используется. Ингейм, выглядит вообще как сломанный механ.
Было:
Стало (Предметов одинаковое кол-во):
> trash bag fix

- code/__SANDCODE/DEFINES/lewd.dm
- code/modules/arousal/arousal.dm
- modular_bluemoon/code/modules/arousal/arousal_robot.dm
- modular_bluemoon/code/modules/mob/emotes.dm
- modular_bluemoon/code/modules/mob/living/carbon/human/damage_procs.dm
- modular_sand/code/datums/components/interaction_menu_granter.dm
- modular_sand/code/datums/interactions/interaction_datums/lewd/self/breasts.dm
- modular_sand/code/datums/interactions/lewd_definitions.dm
- modular_splurt/code/datums/interactions/lewd/lewd_definitions.dm
- modular_splurt/code/game/objects/items/sucking_machine.dm
- modular_splurt/code/modules/arousal/arousal.dm
- tgui/packages/tgui/interfaces/CharacterProfile.tsx
- Теперь при Lust < 55% и последнем climax больше 8и минут назад, женский персонаж при lewd интеракциях будет издавать тихий softmoan, а не громкий moan. Т.е. при всяких поглаживаниях, поцелуях, ударах по заднице и прочем, персонаж будет тихо стонать. На ЕРП влияет только в начале, потом обычные стоны, до 8и минутного перекура.
- Пофикшен трансфер реагентов у одной интеракции vagina to vagina
- Юзлесс переменная заменена на last_climax, не работающие задержки (после перехода на круговое меню) вырезаны.
- Все get_lust_tolerance() * 3 заменены на общий прок get_climax_threshold()
- Пофиксил момент, на что ругался контекст VScode из [ПРа headshot naked](https://github.com/BlueMoon-Labs/MOLOT-BlueMoon-Station/pull/2096). На работоспособность не влияет, но фиксит CI проверку.
> Lust soft moan + fixes

- code/modules/research/designs/weapon_designs.dm
Оболочки для химических гранат убраны из СБ фабрикатора. Убрано ограничение для печати только с синего кода.
Это пустые оболочки для создания кастомных химических гранат из бикеров и желешек слаймов с особыми свойствами нагревания/охлаждения реагентов внутри. Эти шутки сами по себе не имеют никакого отношения к СБ.
> [BLUEMOON] RnD chem grenades

- code/game/objects/structures/flora.dm
Теперь в кустиках с достаточно малым шансом будут спавниться: героин, звездочка, грибы пендосовка, плюшевый мишка, лабебиум, шизогрибы, гандоны, вкусные и очень полезные конфетки, анальная пробка, обдроченный пончик, банка спермы, наручники для ХРП ЕРП. 
- [х] Изменения были проверены на локальном сервере
На сервере не хватает бомжей, которые будут рыться в кустах. Так называемая гача, где тебе могут предложить пятизвездочную зависимость.
> Больше гемблинга

- code/game/objects/items/apc_frame.dm
- code/game/objects/structures/tables_racks.dm
- code/game/turfs/simulated/walls.dm
Установка настенных механизмов и конструкций учитывает конкретное место клика игрока на объект, что позволяет точечно устанавливать их в конкретное место клика. Убрано ограничение на 1 конструкцию на стену за ненадобностью.
Позволяется устанавливать конструкции на стол (прямо как на стену) в желтом GRAB интенте -> игроки могут ставить кнопочки и выключатели на стол и даже сразу несколько.
Тестмерж на недельку.
> [BLUEMOON] Precise wallframes placement

- code/__SPLURTCODE/DEFINES/lewd.dm
- code/modules/arousal/genitals.dm
- modular_splurt/code/modules/arousal/arousal.dm
- modular_splurt/code/modules/arousal/organs/breasts.dm
- modular_splurt/code/modules/arousal/organs/penis.dm
- modular_splurt/code/modules/arousal/organs/vagina.dm
- Минорное, добавлен общий прок для выбора оверлея cum на куклу, старый код отрефакторен _(который частично не работал, ибо переменные местами перепутали)_
- Поставлено ограничение в 10 оверлеев cum на куклу, иначе может упереться в лимит по оверлеям общий
> Cum overlay fix

- modular_sand/code/datums/elements/holder_micro.dm
- modular_splurt/code/modules/mob/living/simple_animal/hostile/deathclaw/funclaw.dm
- Агресивных фанклавов больше нельзя тянуть, прятать в ящики и катать на стульях. _(Вся логика уже прописана в весе, поэтому я просто воткнул им сверхтяжелый, так что технически их можно перевозить на сверхтяжелых каталках или сверхтяжелыми персонажами, другие бонусы фанклавы не получают, т.к. они не карбоны)_
- Легкие персонажи получали задержку, при поднятии других персонажей, если их размер был больше 50% (Короче когда легкие были гигантами), теперь если цель тоже легкого веса, задержки не будет
Писали про кейсы, когда агрессивных факнлавов вытаскивали с техов, например на шаттл, что бы те напали на персов. Считаю, раз ты отказываешься от контента с фанклавами, ввиду префов, то нефиг их трогать и портить другим игру, не для тебя сделаны.
> funclaw weight updt + lightweight pick up delay

- code/game/machinery/cryopod.dm
- code/game/objects/structures/window.dm
- Консоль крио нельзя разобрать инструментами
- Теперь окошко с набором для электрохромофикации, будет выкидывать его плату не только при уничтожении, но и при разборе инструментами
- Больше никаких "Я достал вещи всех, кто ушел в крио с помощью одной отвертки, еще и сломал консоль до конца смены"
- Оч. странно, что окно выкидывало плату только при уничтожении, а при нормальном разборе - нет.
> cryo nodeconstruct and electrochromatic kit drop

- code/__DEFINES/economy.dm
- code/game/objects/items/cards_ids.dm
Теперь с ID карт бюджета отделов нельзя снимать кредиты.
По приказу главнокомандующего https://discord.com/channels/875735187449847830/875757279230701628/1406858571395895379
> departmental card no withdraw

- modular_splurt/code/modules/mob/femclaw.dm
Фикс к [этому](https://github.com/BlueMoon-Labs/MOLOT-BlueMoon-Station/pull/2186) ПРу. У маммиклавов был переписан один прок, поэтому они класть хотели на префы _(но только, если им заехать по морде)_
Проверил на локалке, всех дочерних фан, фем и прочих клавов, включая питомцев
> femclaw fix

- code/game/objects/items/RCD.dm
картридж СЖАТОЙ материи пополняет РСД на 160 материи, а стак не сжатого металла на 200 стоковый и на 600 индустриальный рсд, но места в рюкзаке занимают одинаково (????) при этом картридж на 3/5 из металла и состоит
Из металла можно крафтить предметы, а картридж даже в техфаб обратно не засунуть. Менее функциональный + содержит меньше материи == абсолютно невыгодный, бесполезный. Он должен иметь преимущество перед более функциональным стаком металла, или вовсе исчезнуть из техфаба.
> бафф картриджей RCD

- code/modules/mining/machine_vending.dm
Вендор шахты можно было улучшать, а смысла от улучшения - мало. 
Влепил скидку товара за каждый бин, 2.5% за каждую градацию выше Т1. 
- 15% скидки при трёх Т3 бинах.
- 22.5% скидки при трёх Т4 бинах.
- 30%, почти треть, при Т5 бинах.
Теперь его имеет смысл улучшать. Как сказал в блоке кода:
`так будет проще новичкам, что только изучают ассортимент, и приятнее всем. "Копейка рубль бережёт" или типа того.`
Прелесть процентных величин в том, что дешёвые вещи сильно не подешевеют, а дорогие может и заставят попинать учёных, чтобы ваш вендор улучшили.
Справа-налево: Т3, Т4, Т5.
:cl:
balance: Улучшение вендоров шахты теперь даёт скидку на товары вендора.
/:cl:
> Обновление шахтёрского вендора 

- code/modules/surgery/brain_surgery.dm
- code/modules/surgery/implant_removal.dm
Радиальное меню при изъятии имплантов, повторение операции по восстановлению мозга.
Операция по изъятию имлантов работала очень криво, позволяя вытащить лишь последний вколотый. Операцию по восстановлению мозга нужно было проворачивать с самого начала по нескольку раз, например после лоботомии. 
:cl: 
qol: brain fix, implant removal. better. sosiski.
/:cl:
> Хирургия QOL

- modular_splurt/code/modules/clothing/underwear/boxers.dm
Все maebari (трусы - наклейки, ХЗ как назвать, для женских персонажей) теперь собственно, закрывают органы.
Не знаю по какой причине, у всего подтипа был вырезан этот флаг, но с моей точки зрения, это не логично. Накладки и прочее, по оверлею перекрывают органы, некоторые с сильным запасом, но при этом почему-то в описании или при возбуждении (когда меняется спрайт) органы вдруг видны, что втройне кринжево, т.к. оверлеи накладываются друг на друга.
> maebari fix

- code/__DEFINES/mod.dm
- code/modules/mod/mod_control.dm
Ускорено время активации каждой части с 2х секунд до 1 (общее время активации стало 5 секунд, как на ВМ)
Ускорено время раскручивания и время извлечения батареи.
Добавлена быстрая замена батареи, работает как перезарядка оружия кликом батареи по раскрученному моу, старая выпадает на пол. По тестам ощущается в темпе бм
> Улучшение времени активации и обслуживания МОДа

- code/__HELPERS/radiation.dm
- code/datums/components/radioactive.dm
- code/game/machinery/rechargestation.dm
- code/modules/mod/mod_control.dm
- code/modules/power/cell.dm
- code/modules/reagents/chemistry/machinery/chem_dispenser.dm
- code/modules/vehicles/mecha/_mecha.dm
- modular_splurt/code/modules/power/cell.dm
1. Изменения датум/компонентов.
- Добавлен новый прок `is_radiation_blocked()` для проверок на структуру с `RAD_PROTECT_CONTENTS`.
- Теперь радиация останавливается, если есть защита от радиации от таких структур как: `contamination bodybag`, crate от радиации и т.д.
2. Рефакторнут код радиации батареек. Код теперь сделан более компактным.
3. Реакторная батарея будет фонить меньше.
1. Это глобальное изменение, которое теперь позволит надетой одежде и лежащим в инвентаре вещам - корректно фонить, если они сильно облучены.
2. GIIIIT GUUUD (C) Hornet
3. Балансная полировка.
Не думаю, что нужно.
:cl:
balance: Реакторная батарея теперь фонит меньше.
code: Ревертнуты изменения компонента радиации.
code: Добавлен новый прок is_radiation_blocked()
refactor: Код irradiate батареек сделан более …
> Полировка обновления реакторок + обновление радиации

- code/game/objects/structures/tables_racks.dm
Боргики не имеют половины интентов, поэтому не могли включать баллон с анастезией. Подача анастетика теперь на alt-click, остоединение баллона и маски на ctrl-click. Также расширение описания и микрофиксы.
> [BLUEMOON] Смена кнопок для операционного стола

- _maps/RandomZLevels/away_mission/spacebattle.dmm
В гейте, на одной из точек спавна, в баре под раздатчиком бухла не было тайла. 
Положил гардероб капитана в ящик, что раньше был ящиком капитана.
> Починил потерянный мапером тайл, положил гардероб кэпа 

- _maps/archive/IceTaxi/Smexistation/bluemoonsmexistation.json
- _maps/archive/IceTaxi/Smexistation/smexistation.json
- _maps/icemoonstation.json
- code/modules/admin/verbs/randomverbs.dm
- code/modules/station_goals/bsa.dm
- code/modules/station_goals/shield.dm
- code/modules/station_goals/station_goal.dm
- modular_bluemoon/code/modules/station_goals/bfl.dm
- Админ панелька для станционных целей переехала во вкладку Admin-Events (называется Station Goals) и отображает цветовой индикацией какие цели действительно выполнены.
- Цель Щиты: выявлена и устранена проблема нереальных процентов покрытия от каждого отдельного саттелита. Повышен порог для выполнения цели. Не должна выдаваться на планетарных картах.
- Цель БСА: устранена проблема, что любая существующая бса в мире засчитывала выполнение цели. Теперь для выполнения цели необходимо сделать хотя бы один выстрел из построенной БСА.
> [BLUEMOON] Station goals update
