BlueMoon-Labs/BlueMoon-Station

code/modules/admin/whitelist.dm

Спам из-за ВЛа

---

tgstation.dme

На офф сплурте не захотели включать обратно эту деталь, так как у них вообще отключены интегралки, хоть тут будет.
:cl:
fix: Вернули одну пропавшую деталь интегралок
/:cl:

Возвращаем пропавшую деталь интегралок

---

code/modules/mob/living/carbon/human/species_types/vampire.dm

Теперь вампиры не сразу превращаются в пепел, а медленно умирают.
Есть чутка больше времени найти следующую жертву. А если и нет - то ждать в техах пока мимо-ассистент не откроет твой гроб...
:cl:
/:cl:

Мини-фикс вампиров

---

code/modules/clothing/head/helmet.dm
code/modules/events/_event.dm
code/modules/events/anomaly.dm
code/modules/events/anomaly_flux.dm
code/modules/events/anomaly_grav.dm
code/modules/events/communications_blackout.dm
code/modules/events/electrical_storm.dm
code/modules/events/false_alarm.dm
code/modules/jobs/job_types/cook.dm
code/modules/jobs/job_types/shaft_miner.dm
modular_bluemoon/SmiLeY/all_in/shaft_miner.dm
modular_sand/code/datums/interactions/interaction_datums/lewd/handjob.dm

Батя у меня был электриком.

---

code/game/gamemodes/objective.dm
code/modules/clothing/head/helmet.dm
code/modules/events/_event.dm
code/modules/events/anomaly.dm
code/modules/events/anomaly_flux.dm
code/modules/events/anomaly_grav.dm
code/modules/events/communications_blackout.dm
code/modules/events/electrical_storm.dm
code/modules/events/false_alarm.dm
code/modules/events/operative.dm
code/modules/jobs/job_types/cook.dm
code/modules/jobs/job_types/shaft_miner.dm
modular_bluemoon/SmiLeY/all_in/shaft_miner.dm
modular_sand/code/datums/interactions/interaction_datums/lewd/cursed/eyefuck.dm
modular_sand/code/datums/interactions/interaction_datums/lewd/handjob.dm

Корректировал Антагонизм.

---

code/modules/events/vent_clog.dm

Удаляем из списка реагентов разукрашивающий всё вокруг реагент и кислоту.
Меньше раздражающих окружающих событий, не привносящих в игру достаточно ценного взамен.

Убираем некоторые химикаты из ивента с засорением вентиляции

---

_maps/map_files/SyndicateStation/SyndicateBoxStation.dmm

Вырубает сглаживание углов на Синдистанции.

Smooth = 2

---

_maps/map_files/SyndicateStation/SyndicateBoxStation.dmm

Reverts SmiLeYre/BlueMoon-Station-13#22

Revert "Smooth = 2"

---

code/game/objects/items/devices/PDA/PDA.dm
code/game/objects/items/devices/PDA/cart.dm
code/modules/mob/living/simple_animal/bot/secbot.dm

Crew Manifest for крутых, фикс Робототехника.

Crew Manifest for крутых, фикс Робототехника.

---

code/modules/research/designs/comp_board_designs/comp_board_designs_sci.dm
code/modules/research/designs/comp_board_designs/comp_board_designs_sec.dm
code/modules/research/techweb/nodes/computer_hud_nodes.dm
code/modules/research/techweb/nodes/mecha_nodes.dm
code/modules/research/techweb/nodes/robotics_nodes.dm

Удаление возможности печатать важные ключевые платы.
Придаёт ценность такому понятию и месту как хранилище запасных плат, а также не даёт создать 100500 консолей для вызова и отмены шаттла.
Нет
:cl:
balance: Невозможность печатать важные платы в печатнике плат.
/:cl:

Печать важных плат невозможна

---

modular_bluemoon/phenyamomota/code/modules/cargo/packs/engineering.dm
modular_splurt/code/game/objects/items/circuitboards/miner_circuitboards.dm
tgstation.dme

Добавляет в карго возможность заказать и собрать газ-майнер, не без помощи аномального ядра
Расширяет границы для атмостехов
Нет
:cl:
add: Gas miners in cargo requests
/:cl:

Газовые майнеры в заказах

---

code/modules/admin/verbs/ak47s.dm
code/modules/admin/verbs/secrets.dm

Добавляет выбор перед прожатием кнопки спавна ак для всех между всеми и только теми, кто в зоне Арены цк (доков тоесть).
Перенос всех звуков и текста только для тех, кто получает ак.
Перевод сообщений при спавне ак.
Теперь админы могут хоть дообжиматься этой кнопкой и не будет вопросов (если они не смертники жать "Для всех")
нет
:cl: Winter Schock
tweak: AK-47s for everyone have choice between arena mobs and really everyone 
/:cl:

ak-74s not for everyone

---

code/modules/events/pirates.dm

реальный фикс, который не вызывает варны у IDE, А НЕ У ИГРЫ
Оно нормально работало
Нет
:cl:
fix: анонсы пиратов теперь содержат наименование корабля, КАК ОНО И БЫЛО
/:cl:

реальный фикс, который не вызывает варны у IDE, А НЕ У ИГРЫ

---

code/_globalvars/lists/flavor_misc.dm
code/datums/accents.dm
code/modules/language/tajaran.dm
code/modules/language/vulpkanin.dm
code/modules/surgery/organs/tongue.dm
tgstation.dme

Вульпы и Таяры вспомнили свои языки.
Ящерки делают "ссс"
Моль делает "ззз"
Собачки научились делать "ррр"
Авто-акценты теперь работают с кириллицей 
Добавлен новый орган "canine tongue" для собачьего акцента
Добавлен авто-акцент для нового языка
Добавлен язык таяр Siik'tajr
Добавлен язык вульп Canilunzt

Языки и Акценты

---

code/modules/projectiles/boxes_magazines/ammo_boxes.dm

Клипсу с дробью можно класть в плитник

---

config/dynamic.json
config/entries/general.txt

Изменяем шансы на спавны некоторых ролей.
Также повышаем время до старта с 4 минут до 5. Раунды идут по 2-4 часа и не все успевают перезайти и прожать реди.
Меньше раздражающе-частых ролей.

Робкие попытки трогать динамик

---

_maps/RandomRuins/LavaRuins/bluemoon/lavaland_surface_syndicate_base1_bluemoon.dmm
_maps/RandomRuins/SpaceRuins/BlueMoon/space_syndicate_base.dmm
_maps/map_files/LambdaStation/dorms.dmm
_maps/map_files/LambdaStation/lambda.dmm

Доступ, провода и трубы. Всё по классике.

Зафиксил Лямбду, ДС1 и ДС2

---

code/modules/reagents/reagent_dispenser.dm

(Теперь код не выглядит как кусок аморфной массы).

Фикс взрыва фуелтанков в нормальном виде

---

_maps/shuttles/bluemoon/ruin_lifeweb_haron.dmm
tgstation.dme

Хуе мое, добивочная блять.
Доделал шаттл и вернул свои усы, которые Куши удалил.

lfwb-patch4

---

modular_splurt/code/modules/jobs/job_types/stowaway.dm

Воруем у заключенных последние строки кода

Фикс сломанных раундстартов

---

code/modules/integrated_electronics/core/assemblies.dm
code/modules/integrated_electronics/subtypes/weaponized.dm

По быстрому в свободное время решил набросать прикол
:cl:
/:cl:

Минификс интегралок

---

code/modules/mining/machine_vending.dm

Adding Kinkmate refill for miners/ghostroles.
Госторолям не нужно воевать за один вендор, и шахтёры могут делать их себе, если с карго всё совсем плохо.
Нет.
:cl:
add: Рефилл KinkMate'а был добавлен в раздатчик шахтёров за 12000 очков.
/:cl:

Добавление Kinkmate'а в шахтёрский вендор.

---

code/modules/integrated_electronics/subtypes/weaponized.dm

Вообщем, некоторое время на сервере было так, что единственное эффективное интегральное оружие завязано на гранатах и взрывах... Сейчас я постарался это исправить нёрфом и альтернативами, пока сервер не превратился в 11ое сентября.
Изменил:
-Станнер теперь станит не только в руках, но и на ближнем расстоянии, что делает его менее бесполезным. Однако он всё ещё не выбивает предметы из рук;
-Лазерные пушки не стреляли и рантаймили. Теперь стреляют;
-Гранаты взрываются раза в 2 дольше, больше времени реакции на взрывного дрона;
:cl:
/:cl:

Доделывание интегралок х2

---

code/game/objects/structures/fireplace.dm
modular_bluemoon/0451/_maps/shelter_510.dmm

1)Значительно продлевает время горения камина, убирая нужду заправлять его каждые 3 минуты.
2)Капсула за 15к изменена - убраны бургеры, убраны обычно игнорируемые кегли. Убран раздатчик големов. Убран автолат.
A QoL update
No
:cl:
tweak: fireplace has much *better* capacity.
tweak: 15k capsule is revamped a bit.
/:cl:

Minor update

---

.vscode/launch.json
modular_bluemoon/SmiLeY/aesthetics/sauna/sauna_oven.dm
tgui/packages/tgui/interfaces/AntagInfoInteQ.tsx
tgui/packages/tgui/interfaces/ChastityRemote.tsx
tgui/packages/tgui/interfaces/CommandReport.tsx
tgui/packages/tgui/interfaces/GenitalArousalPermission.tsx
tgui/packages/tgui/interfaces/Jukebox.js
tgui/packages/tgui/interfaces/PaperSheet.tsx
tgui/packages/tgui/interfaces/Photocopier.js

Linter fixes

---

modular_sand/code/datums/interactions/lewd_definitions.dm

Переводы. Хз почему не было, но почему бы и нет

Translate two messages to russian

---

code/modules/power/turbine.dm

Чтоб не приходилось турбину вращать на 360 перед тем как она заработает

Fix turbine breaks on initialization

---

code/modules/events/portal_storm.dm
code/modules/events/travelling_trader.dm
code/modules/events/wisdomcow.dm

Мобы больше не должны спавниться в недосягаемых местах (стенах или местах с опасной атмосферой, например).
Больше динамики в раунд. Джаггернаут посреди коридора имеет больше смысла, чем джаггернаут в окружении 4 стен в аплоуде.
Мобы в некоторых ивентах больше не должны спавниться в недосягаемых местах (стенах или местах с опасной атмосферой).

Исправление спавна мобов в портальный шторм, мудрой коровы и странствующего торговца

---

code/game/objects/items/fluff.dm

- Теннисный мяч, сунутый в рот, заставляет говорить аля без языка - ломает речь
- Меняет барк на рандомное сквиканье каждое предложение

Make tennis ball squeak

---

code/__HELPERS/_extools_api.dm

Добавляет поддержку выполнения выражений на брейкпоинте

Add auxtools debugger support

---

code/modules/mob/living/simple_animal/friendly/drone/_drone.dm
tgui/packages/tgui-panel/chat/constants.js

Снова фикс
Фикс пм и менторсей
Менторам удобно

Fixed PM,MSay HP for drones

---

code/modules/clothing/suits/_suits.dm
modular_bluemoon/kovac_shitcode/code/solfed.dm

Исправлен один символ. У хьюманов и всех причастных с "mam_tail" == "None" теперь не должны появляться поджопники.

фикс хвостов

---

_maps/map_files/generic/CentCom.dmm
modular_bluemoon/kovac_shitcode/code/modules/antagonists/raiders.dm

Люто переделал нюкобазу.

---

code/controllers/subsystem/vote.dm
code/modules/reagents/chemistry/holder.dm

Ща попроходим юнит-тесты, посмотрим чегось там...

Combo check fix-alike

---

_maps/RandomRuins/SpaceRuins/BlueMoon/space_syndicate_base.dmm
_maps/map_files/BoxStation/BoxStation.dmm
_maps/map_files/PeaceSyndicateStation/PeaceSyndicateBoxStation.dmm
_maps/map_files/SyndicateStation/SyndicateBoxStation.dmm
_maps/shuttles/lambda_code.dmm

- На боксе убрано по 2 принтера в кабинетах
- На боксе и синди поправлены шлюзы в космос в бриге
- Немного изменен шаттл-оружейная
- На ДСах доступ к турелям такой же, как и у шлюзов (т.е. его по сути нет)

правки карт

---

_maps/map_files/Deltastation/DeltaStation2.dmm
code/game/objects/items/storage/backpack.dm
code/modules/clothing/under/miscellaneous.dm

- убран табурет в консоли на дельте
- возвращен antro_icon для одежды славянина
- описание дуфли

фиксы ошибок

---

_maps/map_files/BoxStation/BoxStation.dmm
_maps/map_files/BoxedInStation/BoxedInStation.dmm

- Тир теперь находится восточнее офиса ГСБ.
- Допросная была перемещена на место тира.
- Комната с EVA-ми была перемещена на место старой допросной

Перемещение комнаты для допросов и стрельбища

---

code/datums/character_profile.dm
tgui/packages/tgui/interfaces/CharacterProfile.tsx

Hide profile art when mask is weared

---

code/game/machinery/computer/camera.dm
code/modules/events/electrical_storm.dm
code/modules/events/meteor_wave.dm
code/modules/modular_computers/file_system/programs/secureye.dm
code/modules/station_goals/shield.dm

- Добавлена камера. Теперь в них могут смотреть. Радиус - на зону обстрела.
- Зона обстрела увеличена с 14 до 20 тайлов (поднимается до 30 при наличии апгрейда из РНД).
- Слабый взрыв при уничтожении.
- Оповещения в рацию об уничтоженных метеоритах (каждые 6, чтобы избежать спама).
- Оповещения об уничтожении самого спутника.
- Расширение экзейма сателлитов.
- Оповещения в главный канал о количестве сбитых метеоритов за раунд по окончанию метеоритного дождя.
- При электрическом шторме, выходят из строя (пока что, просто взрываются как петарда).
Новые механики. Спутники стали полезнее. Появилось платное средство против любителей лазать в космосе.

Обновление спутников (противометеоритных и не только)

---

code/game/atoms.dm
code/game/objects/items/storage/book.dm
modular_splurt/code/modules/mob/living/emotes.dm

Бог накажёт того подонка, который посмеет прожать *fart рядом с книгой.

Механ Библии с Пары

---

code/game/objects/effects/spawners/lootdrop.dm
modular_bluemoon/kovac_shitcode/code/sprite_update.dm

- фикс плюшевой игрушки
- порезан лут в техах

нерф подарков от синдиката

---

code/modules/reagents/chemistry/reagents/medicine_reagents.dm

Теперь криоксадон лечит внутренние органы, в том числе и мозг, около 0.5 в тик, в зависимости от температуры

Бафф криотрубы, а именно лечение органов от криоксадона

---

code/modules/mob/living/silicon/robot/robot_modules.dm

фикс спрайта медбота интекью

---

code/datums/components/embedded.dm
code/datums/mood_events/generic_negative_events.dm
code/datums/status_effects/wound_effects.dm
code/datums/wounds/_scars.dm
code/datums/wounds/_wounds.dm
code/datums/wounds/bones.dm
code/datums/wounds/burns.dm
code/datums/wounds/pierce.dm
code/datums/wounds/slash.dm
code/game/objects/items/stacks/medical.dm
code/modules/mob/living/brain/brain_item.dm
code/modules/mob/living/carbon/human/human_defense.dm
code/modules/surgery/bodyparts/_bodyparts.dm
code/modules/surgery/bodyparts/head.dm
code/modules/surgery/bodyparts/parts.dm
code/modules/surgery/organs/appendix.dm
code/modules/surgery/organs/ears.dm
code/modules/surgery/organs/eyes.dm
code/modules/surgery/organs/heart.dm
code/modules/surgery/organs/liver.dm
code/modules/surgery/organs/lungs.dm
code/modules/surgery/organs/organ_internal.dm
code/modules/surgery/organs/stomach.dm
code/modules/surgery/organs/tails.dm
code/modules/surgery/organs/tongue.dm

Первые потуги к тому, чтобы избавить эту часть от мешанины между русским и английским. Завтра (или ближе к выходным) доделаю вторую.

Перевод механа повреждений персонажа #1

---

_maps/RandomRuins/LavaRuins/bluemoon/lavaland_surface_syndicate_base1_bluemoon.dmm
_maps/RandomRuins/SpaceRuins/spacediner.dmm
_maps/map_files/generic/CentCom.dmm
code/game/objects/items/storage/belt.dm

- на пояс секов можно теперь вешать проектор, на пояс уборщика тоже
- флажки на цк
- апц в космическом кафе
- правки косяков на дс-1

правки карт и поясов

---

code/datums/wounds/bones.dm
code/datums/wounds/burns.dm
code/datums/wounds/pierce.dm
code/datums/wounds/slash.dm
code/game/objects/items/devices/scanners.dm

Частичный перевод анализатора здоровья, правки предыдущего

перевод механик повреждений #3

---

code/modules/projectiles/boxes_magazines/internal/shotgun.dm
code/modules/projectiles/guns/ballistic/shotgun.dm
modular_bluemoon/kovac_shitcode/code/modules/guns/weapons.dm

- количество патронов в трубке снижено до 4
- у дробовика вардена уменьшена задержка между выстрелами
- у пистолета-дробовика ХоСа теперь 6 патронов в барабане, а не 4

пробуем минимально балансить боевой дробовик

---

code/__DEFINES/admin.dm
code/controllers/subsystem/security_level.dm
code/game/machinery/_machinery.dm
code/game/machinery/computer/_computer.dm
code/game/machinery/computer/communications.dm
code/modules/admin/verbs/pray.dm
code/modules/power/lighting.dm
code/modules/projectiles/ammunition/energy/laser.dm
code/modules/projectiles/projectile/beams.dm
tgui/packages/tgui/interfaces/CommunicationsConsoleInteq.js

Консоль Инцеловцев.

---

code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
code/modules/reagents/chemistry/reagents/drink_reagents.dm
modular_sand/code/datums/interactions/interaction_datums/lewd/breasts.dm
modular_sand/code/datums/interactions/interaction_datums/lewd/nipsuck.dm
modular_sand/code/datums/interactions/interaction_datums/lewd/self/breasts.dm
modular_splurt/code/modules/reagents/chemistry/reagents/other_reagents.dm

Теперь выключенная в настройках перса лактация не позволяет выдаивать содержимое из грудей (логично же). Также +/- (тудой/сюдой) возбуждение от жмаканий грудей. А еще чутка уменьшен шанс мурчания феленидов от некоторых жидостей (никак не связано с лактацией... возможно... или же связано... хм...)

Фикс лактации

---

code/modules/paperwork/paper.dm

Никто не уйдет от бюрократии! Теперь можно наводиться на глаза и показывать бумажку с надписями собеседнику.

Тыкать бумажкой в лицо

---

code/modules/food_and_drinks/drinks/drinks/drinkingglass.dm
code/modules/reagents/reagent_containers/glass.dm
code/modules/reagents/reagent_containers/spray.dm

Фелиниды будут шипеть, если на них прыскать из спрея или обливать жидкостями из стаканов и тп.

Пшик-пшик = Хссс!

---

_maps/map_files/MetaStation/MetaStation.dmm
_maps/map_files/generic/CentCom.dmm
modular_bluemoon/krashly/code/game/area/Space_Station_13_areas.dm
tgstation.dme

Ну типа люти обнова Меты

---

code/modules/client/preferences.dm

Фикс префов

---

code/__DEFINES/is_helpers.dm
code/datums/status_effects/debuffs.dm
code/game/objects/items/pet_carrier.dm
code/game/objects/structures/crates_lockers/closets/cardboardbox.dm
code/game/objects/structures/tables_racks.dm
code/modules/reagents/reagent_containers/glass.dm
modular_splurt/code/datums/interactions/lewd/lewd_datums.dm

Игромеханических изменений нет. ПР правит проверку для приведения её к общему виду (как в других проверках на расы), а еще это положительно сказывается на чистоте кода - убирает лишние вводы переменных.

Фикс проверки "iscatperson"

---

code/datums/bark.dm
code/modules/mob/dead/new_player/sprite_accessories/Citadel_Snowflake.dm
code/modules/mob/dead/new_player/sprite_accessories/hair_head.dm
code/modules/mob/living/carbon/human/examine.dm

Сплюрты любили закрывать контент в разных местах. Нашли и открыли еще кусочек, например барк "nya" (втф опять контент для фелинидов?) и какие-то части тела. А еще немного "трудностей перевода".

Кусочек открытого контента и трудности перевода.

---

code/__SPLURTCODE/DEFINES/cit_defines.dm
code/modules/arousal/genitals.dm
code/modules/client/preferences.dm
modular_splurt/code/datums/genitals/genitals_interface.dm
modular_splurt/code/modules/client/preferences.dm
tgui/packages/tgui/interfaces/GenitalConfig.tsx

Нигде не сказано об этом, но один и тот же флаг "allow egg stuffing" отвечает также за возможность по аналогии использовать игрушки на выбранных органах. Теперь об этом сказано.

Расширенное пояснение опции "egg stuffing"

---

code/modules/projectiles/projectile/beams.dm

1) Лазеры эмиттеров пробивали генераторы щита (СМОТРИТЕ НА ВАШИХ СЫНОВЕЙ)

Иммитеры более не пробивают генератор щита

---

code/datums/emotes.dm
code/game/objects/structures/crates_lockers/closets/cardboardbox.dm
code/modules/mob/living/carbon/carbon_defense.dm
code/modules/mob/living/carbon/emote.dm
code/modules/mob/living/carbon/human/emote.dm
code/modules/mob/living/emote.dm
modular_bluemoon/code/datums/traits/neutral.dm
modular_bluemoon/code/modules/mob/bluemoon_emotes.dm
modular_citadel/code/modules/mob/cit_emotes.dm
modular_sand/code/modules/mob/emote.dm
modular_splurt/code/modules/mob/living/emotes.dm
modular_splurt/code/modules/mob/living/silicon/emotes.dm

- Калибровка тайминга эмоутов.
- Исправлена ошибка отсутствия проверки тайминга у части эмоутов. 
- Более стабильное мурчание феленидов при поглаживании (минус спам эмоутов при заглаживании). 
- Менее стабильное мурчание фелинидов в закрытых коробках. 
- Обладатели квирка "Неконтролируемый вой" воют чуть реже. 
- Убрано очень громкое оповещение о наличии кд на эмоуты.

Калибровка эмоутов

---

code/datums/emotes.dm
code/modules/mob/living/carbon/alien/emote.dm
code/modules/mob/living/carbon/emote.dm
code/modules/mob/living/carbon/human/emote.dm
code/modules/mob/living/emote.dm
code/modules/mob/living/silicon/robot/emote.dm
code/modules/mob/living/simple_animal/hostile/gorilla/emotes.dm
modular_bluemoon/code/modules/mob/bluemoon_emotes.dm
modular_bluemoon/kovac_shitcode/code/modules/mob/living/emotes.dm
modular_citadel/code/modules/mob/cit_emotes.dm
modular_sand/code/modules/mob/emote.dm
modular_splurt/code/modules/mob/living/emotes.dm
modular_splurt/code/modules/mob/living/silicon/emotes.dm

Игроки не заметят никакой разницы, могут листать дальше. 
- Разрозненные проверки задержек с разных билдов разных эмоутов в разных ипостасях теперь централизованы и находятся в одном месте. И прибавка задержки тоже. 
- Задержки части эмоутов стало регулировать гораздо проще.

Сиквел калибровки задержки эмоутов

---

code/__HELPERS/mobs.dm
code/controllers/configuration/entries/fetish_content.dm
code/datums/emotes.dm
code/modules/arousal/organs/breasts.dm
code/modules/mob/living/carbon/human/emote.dm
code/modules/mob/living/emote.dm
code/modules/paperwork/photocopier.dm
code/modules/photography/photos/photo.dm
modular_bluemoon/code/modules/mob/bluemoon_emotes.dm
modular_citadel/code/modules/mob/cit_emotes.dm
modular_sand/code/datums/interactions/lewd_definitions.dm
modular_splurt/code/datums/interactions/lewd/_lewd.dm
modular_splurt/code/modules/mob/living/emotes.dm
modular_splurt/code/modules/mob/living/silicon/emotes.dm

- Крики/стоны/смех/etc non-binary персонажей были случайными и не особо определенными (либо женскими, либо мужскими). Теперь женские/мужские звуки для небинарышей будут зависеть от телосложения (маскулинного/феминного). 
- В редакторе перса можно выбрать плоскую грудь 0 размера (функционал сохраняется).

Апдейт для небинарышей (0.1% игроков)

---

code/game/machinery/camera/camera.dm
code/modules/mob/living/silicon/ai/ai.dm
code/modules/paperwork/paper.dm

- Офишшалли можно тыкать бумажки в лицо и заставлять других вникать в вашу бюрократию. 
- Также бумажки можно тыкать в камеры иишки, и он их может читать.

Окончательный фикс бумажек в лицо

---

code/_onclick/ai.dm

ИИшка может теперь осматривать предметы через камеры.

Осмотр предметов за ИИ

---

code/game/objects/buckling.dm
code/game/objects/structures/beds_chairs/bed.dm

Фикс перемещения сверхтяжёлых персонажей

---

code/modules/arousal/arousal.dm
code/modules/arousal/organs/vagina.dm
code/modules/reagents/chemistry/holder.dm
modular_sand/code/modules/reagents/chemistry/reagents/other_reagents.dm
modular_splurt/code/modules/arousal/organs/anus.dm

- Был исправлен баг более чем 7-милетней давности (новый рекорд!). Функция возвращала первое попавшееся значение ("детей" искомого объекта, что нам не нужно). 
- Механика подтеканий из промежностей была улучшена: баттплаг теперь выполняет свою функцию.

Привет из прошлого. И продвинутое подтекание.

---

code/__HELPERS/text.dm
code/modules/mob/living/carbon/examine.dm
code/modules/mob/living/carbon/human/examine.dm
code/modules/mob/living/carbon/human/human_defense.dm
code/modules/surgery/organs/organ_internal.dm
code/modules/surgery/sew_up_the_mouth.dm

Некоторые действия на определенные части тела не работали, из-за русификации в лишних местах. Также будет чутка меньше одиноких русских слов посреди цельного текста на английском.

Фикс поломки из-за русификации

---

code/datums/traits/good.dm

Было 2, стало 1
[Тема](https://discord.com/channels/875735187449847830/1161977576248578169/1161977576248578169)

Снижение цены квирка "твёрды ступни"

---

code/datums/components/storage/concrete/bag_of_holding.dm
code/game/objects/structures/ghost_role_spawners.dm

Чтобы можно было складывать много предметов, а также туда помещались вещи из лодаута.

Всем персонажам в ГК выдаются satchel of holding

---

code/game/gamemodes/dynamic/dynamic.dm
code/game/gamemodes/dynamic/dynamic_rulesets_latejoin.dm
code/game/gamemodes/dynamic/dynamic_rulesets_midround.dm
code/game/gamemodes/dynamic/dynamic_rulesets_roundstart.dm
code/modules/antagonists/_common/antag_datum.dm
code/modules/antagonists/bloodsucker/datum_bloodsucker.dm
code/modules/antagonists/changeling/changeling.dm
code/modules/antagonists/cult/cult.dm
code/modules/antagonists/cult/runes.dm
code/modules/antagonists/eldritch_cult/eldritch_antag.dm
code/modules/antagonists/gang/gang.dm
code/modules/antagonists/revolution/revolution.dm
code/modules/antagonists/traitor/datum_traitor.dm
code/modules/antagonists/wizard/wizard.dm

1. Крики культа из BLOOD больше не слышно через стены. Об этом есть сообщение при получении роли, чтобы все знали.
2. Теперь вампиры появляются в соотношении 1 к 40.
4. Некоторые антагонисты теперь получают напоминания о том, что у них есть роль. В основном, это скрытые антагонисты или склонные играть в "мирного антагониста". Например:
- Предатель (2 раза, каждый через 12 минут с момента появления).
- Генокрад (2 раза, каждый через 12 минут с момента появления).
- Еретик (2 раза, каждый через 12 минут с момента появления).
- Вампир (2 раза, каждый через 12 минут с момента появления).
- Революционер (1 раз через 5 минут с момента появления).
- Член банды (1 раз через 5 минут с момента появления).
- Маг (1 раз через 5 минут с момента появления).

Небольшие изменения в вампире, культе и напоминания антагонистам

---

code/game/machinery/porta_turret/portable_turret.dm
code/game/objects/items/pinpointer.dm
code/modules/antagonists/bloodsucker/bloodsucker_objectives.dm
code/modules/mob/living/carbon/human/human_helpers.dm
code/modules/mob/living/carbon/human/say.dm
code/modules/modular_computers/file_system/programs/radar.dm
code/modules/newscaster/newscaster_machine.dm

Фикс ерроров с id картами.

---

modular_splurt/code/modules/mob/living/simple_animal/hostile/clockworktank.dm
modular_splurt/code/modules/projectiles/projectile/energy/laser.dm

[Тема](https://discord.com/channels/875735187449847830/1170381634219024424)

Нерф танков клоккульта

---

code/modules/mob/living/simple_animal/friendly/cat.dm
code/modules/mob/living/simple_animal/friendly/dog.dm

(хоть и кошко мать все равно их может наплодить целую гору, но хоть так)

котята и щенята не плодятся

---

code/modules/arousal/arousal.dm
code/modules/arousal/organs/vagina.dm
modular_bluemoon/Gardelin0/code/items/lewd_items/dildo_custom.dm
modular_sand/code/datums/status_effects/neutral.dm
modular_sand/code/game/objects/items/fleshlight.dm
modular_splurt/code/_globalvars/lists/lewd_content.dm
modular_splurt/code/modules/arousal/organs/anus.dm

Фикс пробок и подтеканий

---

code/modules/arousal/arousal.dm

Да-да, именно так. Сплюрты не могут пофиксить механ, который сами и ввели.

Фикс кама у женщин

---

modular_bluemoon/size_tool/size_tool.dm

на каждые 25% размера тратится 5 секунд и 1000 энергии
в гост кафе на любой размер тратится 5 секунд без энергии (да хоть без батарейки)
сайз тул даёт возможность выбрать размер от 25 до 200 (600 в гост кафе)
квирк анти-нормализатора работает и на сайз тул

Реворк сайз тула под вариацию VORE station

---

code/game/objects/structures/window.dm

Фикс мерджа плазмастекла

---

_maps/map_files/BoxStation/BoxStation.dmm

Больше костюмов, добавлена кнопка открытия EVA на мостике и кнопка аунтификации НТРа теперь не залезает в саму EVA.

Обнова ЕВЫ бокса

---

code/datums/components/crafting/glassware/glassware.dm
code/datums/components/crafting/glassware/lens_crafting.dm
code/game/objects/items/stacks/rods.dm
code/game/objects/items/stacks/sheets/sheet_types.dm
modular_sand/code/datums/components/crafting/recipes/recipes_misc.dm

Ну чё
Фикс размера для реагентов у банок стеклодувных
Фикс не траты предметов при стеклодувных работах (линз и детали для лазерной указки)
Возможность скрафтить очки за 3 железные палки и 30 секунд
Снижение цены крафта лазерной указки с 30 пластика до 3 и 30 секундами крафта
Крафт стеклодувной трубки из прутьев и помощи горелки
Крафт стеклодувных инструментов из кожи, дерева, железа, прутьев и помощи кусачек с горелкой
(Вообще этот пр я хотел на санд кинуть, но я уже 3 часа бьюсь об стену в попытках понять как мне отправить 1 конкретный коммит без всех изменений связанных с блюмуном)

glassworks

---

_maps/RandomZLevels/away_mission/undergroundoutpost45.dmm

правки андеграунд45

---

_maps/map_files/generic/CentCom.dmm

Меняем бар в госткафе на реальное кафе

---

code/datums/accents.dm

Делаем все буквы акцентов большими, если они изначально большие

---

code/modules/vending/_vending.dm

Боргики/ИИшечки/дрончики тоже хотят покупать штуки в торговых автоматах. Теперь они могут это делать (за счет гражданского бюджета станции).

Торговые автоматы и граждане силиконовые.

---

_maps/RandomRuins/StationRuins/Box/Engine/bluemoon/engine_rbmk_bluemoon.dmm
_maps/RandomRuins/StationRuins/engine_rbmk.dmm
_maps/RandomRuins/StationRuins/engine_rbmk_rocks.dmm
code/modules/power/reactor/rbmk.dm

Дёргаем некоторые переменные, меняем нарушение законов термодинамики N2O на что-то нормальное. 
Подробно:
- На все шаблоны РБМК добавлена автоматическая регулировка давления. Это минимум мер безопасности.
- На всех шаблонах РБМК ручные клапаны заменены на электронные.
- Значительно повышена эффективность стержней управления, подправлена под формулы. Старое изменение куши сделало реактор буквально неконтроллируемым даже с максимальным вводом модератора на мощностях выше 30%.
- N2O в модераторе реактора теперь не магическим способом удаляет тепловую энергию, а увеличивает фактор теплообмена с теплоносителем.
В будущем желательно переименовать RBMK на что-то менее 'смешное' как минимум потому, что ингейм мы имеем подобие реактора HTGR или GCR, а не водоканальный.
:cl:
add: На все модели …

Физика и термодинамика РБМК, Маппинг РБМК.

---

code/modules/mob/living/carbon/carbon_defense.dm

Ха, думал, это бафы? Нет, это был я, NERF!
Если персонаж  слишком высокий для пытающего погладить или бупнуть, буп не проходит.
Повышен шанс на агрессию за буп или поглаживание с 5% до 20% при квирке distant

Обновление бупов в нос и поглаживаний по голове

---

code/game/objects/structures/ghost_role_spawners.dm

Убираем обжективы у оригинальных сотрудников, т.к. они почему-то миксованы на отеле, что ебучий рак

Дофикс отеля

---

code/__SANDCODE/DEFINES/lewd.dm
code/modules/client/preferences.dm
modular_citadel/code/modules/client/preferences_savefile.dm

This reverts commit 8875022a60c22ac7dbbed29603a6cee581b0e08c.

Revert "Добавил "Can Refuse in LOOC" и "Watch the OOC-notes" в Нон-Кон."

---

code/game/objects/items/devices/taperecorder.dm

Фикс диктофона, только лучше.

---

code/controllers/subsystem/ticker.dm
code/game/gamemodes/dynamic/dynamic.dm

Speedmerge. У нас количество очков угрозы не изменяется от выбранного режима.

Фикс для уровней угрозы

---

modular_bluemoon/code/datums/interactions/_interaction.dm
modular_sand/code/datums/interactions/_interaction.dm
modular_sand/code/datums/interactions/lewd_interactions.dm
tgstation.dme

Я вам ЗАПРЕЩАЮ шлёпать по жопе (если не хотят)

---

code/game/machinery/_machinery.dm
code/game/machinery/doors/airlock.dm
modular_sand/code/modules/integrated_electronics/subtypes/manipulation.dm

Будет работать с большинством агрегатов, но не со всеми, потому что потому. Долго рассказаывать. Да. Например консольки работают по другому механизму, я бы вообще переработал этот агрегат, но меня просили починить, а не переработать, так что п+п.

Фикс адвактиватора для интегралок

---

code/modules/clothing/gloves/tacklers.dm
modular_sand/code/modules/clothing/gloves/accessories.dm

По запросу. Жоска поменял тру на фолс

боевые перчи не оставляют отпечатки

---

code/__DEFINES/say.dm
code/datums/saymode.dm
modular_bluemoon/Gardelin0/code/antagonists/qareen_abilities.dm
modular_splurt/code/modules/antagonists/qareen/qareen.dm
modular_splurt/code/modules/mob/living/living.dm

Выделил ревенантскую телепатию на отдельный поток связи. Тэг :q
Карины научились говорить, шептать и *эмоутить
Front TGUI фиксы

Qareen_talk :q

---

_maps/splurt_maps/templates/hilbertshotel.dmm
_maps/templates/apartment.dmm
_maps/templates/apartment_1.dmm
_maps/templates/apartment_2.dmm
_maps/templates/apartment_3.dmm
_maps/templates/apartment_bar.dmm
_maps/templates/apartment_sauna.dmm
_maps/templates/hilbertshotel.dmm
_maps/templates/hilbertshotellore.dmm
code/controllers/subsystem/jukeboxes.dm
code/game/machinery/dance_machine.dm
code/game/machinery/dance_machine_handled.dm

Жукбоксы в инфинити дормах теперь играют только для того номера в котором находятся (да и впринцыпе через vv поменять это и другим при желании)
(не ну серьёзно одного дурака с емагом до этого могло хватить чтобы на территории инф дорм нельзя было существовать)

Инф дорм жукбоксы играют только на свою комнату

---

code/game/objects/structures/flora.dm

потешный камушки на земле теперь проходимы

---

modular_sand/code/modules/telescience/telesci_computer.dm

Убрал остатки древнего кода, который блокировал нынешний слой ксеноархеологии от доступа телепадом.
telepad work gooder
:cl:
fix: Вернул слой ксеноархеологии в список доступных телепаду
/:cl:

Added xenoarch to available telepad layers

---

_maps/map_files/generic/CentCom.dmm
code/game/area/areas/centcom.dm

Тайлы в ГК больше не излучают конченное количество света, которое перегружает старт игры.

Фикс освещения в ГК (и сокращения времени запуска на 30 секунд)

---

code/datums/character_profile.dm
tgui/packages/tgui/interfaces/CharacterProfile.tsx
tgui/packages/tgui/interfaces/CharacterProfileForGhosts.tsx

- Призраки при осмотре персонажа видят, что написано в его заметках охраны и медбея (тех, что пишет сам игрок).
- Немного изменил порядок. Теперь описание расы стоит значительно дальше.

Призраки могут видеть база данных

---

code/game/objects/items/robot/robot_upgrades.dm
code/modules/mob/living/silicon/robot/life.dm

- VTEC теперь работает. 
- VTEC теперь не бесполезен. 
- 3 режима работы: дефолтная скорость / чутка ускоренный бег / оверклок. VTEC при оверклоке будет жрать заряд батареи (много).

VTEC: починка и улучшайзинг

---

code/game/objects/items/robot/robot_upgrades.dm
code/modules/mob/living/silicon/robot/life.dm

Микрофискы для втека

---

modular_bluemoon/Fink/code/items/implant_anchor.dm
tgstation.dme

медленно харасит, при покидании родного сектора

имплант якорь

---

modular_splurt/code/modules/antagonists/qareen/qareen_abilities.dm
modular_splurt/code/modules/antagonists/qareen/qareen_bliss.dm

Лечение заболевания более не доставит проблем
В список лекарств добавлен Spaceacillin, чтобы болезнь могли вылечить сотрудники медбея

Фикс болезни Qareen

---

modular_bluemoon/criminal_quirk/criminal_quirk.dm
tgstation.dme

- Новый нейтральный квирк - "Нарушитель закон".
- Сначала раунда выдаётся от 1 до 3 нарушений статьей 100-ой и 200-ой категории.
- С некоторым шансом, с начала смены также может уже быть статус ареста.
- Квирк нацелен на форсирование ролевого взаимодействия с охраной, ведь нужно как-то договориться, чтобы СБ не искало себе работу в виде такого нарушителя.

Квирк "нарушитель закона"

---

code/modules/ambitions/ambition_objective.dm

Теперь random_crew - это не только "Капитан"

Фикс для амбиций

---

modular_sand/code/modules/resize/resizing.dm

Персонажи с применимыми боевыми искусствами вне хелп-интента не могут быть раздавлены сверхтяжёлыми персонажами.
Если хочется, чтобы давили (или чтобы скрывать у себя их наличие), нужно быть в хелп-интенте.

Сверхтяжи не могут давить боевые искусства

---

_maps/RandomRuins/SpaceRuins/BlueMoon/space_syndicate_base.dmm
code/modules/mob/living/simple_animal/friendly/fox.dm

Теперь не придется вечно сражаться за жизнь с ящеркой, а мило её погладить. Она больше не hostile, а просто simple mob

tweak(fox.dm) Ящерка в перме ДС теперь безобидная

---

_maps/map_files/generic/CentCom.dmm

До фикса:
:cl:
fix: Исправлен диван в клубе гост-кафе
/:cl:

Фикс дивана в ГК

---

code/modules/cargo/order.dm

Больше никаких Нанифестов, только манифест

---

code/modules/paperwork/fax.dm

Слепой пиздинг с FF без код-ревью к добру не приводит.

Починил подсказки к факсу

---

modular_sand/code/modules/integrated_electronics/subtypes/manipulation.dm

Первоначальный разраб этой шайтан машины оставил пасхалочку (нагадил как кошка за диваном), которая не только некорректно команды задавала, но и даже локалку убивала на месте из-за вечного цикла. И все мне переделывать офк.

Фикс критической ошибки адвактиватора

---

code/game/machinery/_machinery.dm

я на самом деле хуй знает, наверное сработает :trollface: 
:cl: PuroSlavKing
fix: Исправлено "unвкручивать"
/:cl:

unкручивать fix

---

code/modules/mob/living/carbon/human/examine.dm

Хз шо конкретно сломалось, но пусть будет так

Быстрофикс

---

code/game/atoms.dm
code/modules/mob/living/carbon/human/examine.dm

Выявлена и исправлена доп. ошибка.

Быстрофикс 2

---

code/modules/vehicles/mecha/equipment/weapons/weapons.dm

Мех больше не стреляет сам в себя при движении

Фикс стрельбы меха в самого себя.

---

_maps/map_files/MetaStation/MetaStation.dmm
_maps/map_files/PeaceSyndicateStation/PeaceSyndicateBoxStation.dmm

Развернул "утконосов" в техах меты, чтобы они больше не смотрели в космос, подключил скраббер бримеду, в прибытии пис синдистейшена тоже пару разрывов исправлено
Ссылки на репорты:
https://discord.com/channels/875735187449847830/1191182957977809027
https://discord.com/channels/875735187449847830/1190341313569235075

Исправление багов карты по запросам из дискорда

---

modular_splurt/code/datums/dna.dm

ранее урон наносился в грудь только брут уроном, в этом пре все виды урона влияющие на здоровье (не считая окси урона) пропорционально изменяются увеличению тела (можно убрать одну проверку, чтобы урон наоборот убирался при уменьшении чтобы общий процент хп не падал)

Урон на кукле пропорционально увеличивается увеличению хп при увеличении персонажа

---

modular_sand/code/datums/interactions/lewd_definitions.dm

Ебётс, в "киску", или "попку", а почему-то кончаете не в неё _(по крайней мере по тексту, а по механу в неё)_, а на неё, как-то странно, не правда ли?
:cl: PuroSlavKing
fix: Исправлен перевод оргазма в пиздёнку, и жопу UwU.

Cum in pussy and ass

---

modular_bluemoon/Gardelin0/code/antagonists/ghost_spawner.dm

:cl: PuroSlavKing
fix: Вендиго больше не зашКварен

Вендиго не клара

---

code/controllers/subsystem/job.dm
code/modules/client/preferences.dm
code/modules/clothing/neck/_neck.dm

На ошейниках с биркой можно изменять отображаемое имя на бирке прямо из лодаута. Нет, вы не понимаете, это другое: имя ошейника и имя бирки на ошейнике это разные вещи - теперь можно изменять бирку.

Имя на бирке ошейника в лодауте

---

code/modules/antagonists/devil/true_devil/inventory.dm
code/modules/mob/living/simple_animal/guardian/types/dextrous.dm
modular_bluemoon/Ren/Code/mobs.dm

Теперь они могут выкидывать вещи из рук

Фикс сломанного выкидывания вещей у сэндмена, дьявола и рукастого галопаразиты

---

code/game/objects/items/devices/swapper.dm

Нельзя будет просто использовать инвертер и убрать линковку чтобы убежать от кого-то благодаря этому

Связь инвертера можно разорвать только когда оба устройства заряжены

---

_maps/map_files/generic/CentCom.dmm
_maps/map_files/layenia/layeniastation.dmm

repossitore Gran

---

modular_splurt/code/datums/interactions/lewd/lewd_datums.dm

Фелиниды должны мяукать, а клоуны хонкать.

Починил шлепки по попе

---

code/controllers/subsystem/processing/quirks.dm
code/modules/client/preferences.dm
modular_splurt/code/controllers/subsystem/processing/quirks.dm

починка несовместимости квирков + добавление новых несовместимостей

---

modular_bluemoon/Gardelin0/code/items/lewd_items/dildo_custom.dm
modular_sand/code/datums/components/interaction_menu_granter.dm
modular_sand/code/datums/interactions/interaction_datums/lewd/cursed/bite.dm
modular_sand/code/datums/interactions/interaction_datums/lewd/facefuck.dm
modular_sand/code/datums/interactions/interaction_datums/lewd/fuck.dm
modular_splurt/code/datums/interactions/lewd/lewd_datums.dm
modular_splurt/code/game/objects/items/lewd_items/vibrator.dm

Мне осточертело чинить за сплюртовскими бургерами сломанный ими механ. Месяцами не фиксят проблемы, скоты безалаберные.

Чиню ЕРП панель и игрушки

---

code/game/objects/items/stacks/sheets/sheet_types.dm
modular_bluemoon/code/datums/traits/neutral.dm
modular_bluemoon/krashly/code/game/objects/structures/other.dm
modular_citadel/code/modules/mob/cit_emotes.dm
modular_splurt/code/modules/mob/living/emotes.dm
modular_splurt/code/modules/mob/living/silicon/emotes.dm

Его можно крафтить из металла. Его можно прикручивать/откручивать. Можно жестко бить по нему кулаком (сломать с большой вероятностью). А еще микрофиксы.
По поводу звуков: они будут негромкими, но распространяться значительно дальше. Затрагиваются только звуки колокольчика и завывания для корректной работы квирка "Неконтролируемый вой".

Обновление настольного звоночка и распространения звуков для него (и воя)

---

_maps/templates/apartment_beach.dmm
code/modules/ruins/spaceruin_code/hilbertshotel.dm
modular_bluemoon/SmiLeY/code/hilbertshotel_ghost.dm

Новая дорма для вашего милого ЕРП теперь в виде пляжа, УРА!!

Новая инфинит дорма

---

code/modules/cargo/bounty_console.dm

Бумажка с баунти из консоли теперь работает

---

code/modules/projectiles/gun.dm

фокус с двойным использованием прока из-за чего на деле прицел включался и мгновенно выключался

Фикс прицела у снайперок

---

code/game/objects/structures/crates_lockers/closets/cardboardbox.dm
modular_bluemoon/SmiLeY/code/janitor/cool_broom.dm

Опа, опа, апдейты на чистокровные мемы. Значица, приведена в порядок продвинутая швабра. Чо она теперь может? Она может быть взломана емагом и сносить всех существ как ветром (кроме супертяжей офк, "против лома нет приема" как грицца). Ну а фелинидов будет сдувать всегда (fun allowed). Также бипски больше не агрятся на эту швабру несчастную. А еще пацифисты смогут без проблем использовать эту штуку, она же безвредная!

Гигаэнергетическая швабра 2.0

---

code/modules/clothing/head/misc_special.dm

фикс багрепорта, про пропажу ушей в сварочной маске

Ушастые сварщики

---

code/modules/cargo/bounties/assistant.dm
code/modules/cargo/bounties/botany.dm
code/modules/cargo/bounties/chef.dm
code/modules/cargo/bounties/engineering.dm
code/modules/cargo/bounties/gardencook.dm
code/modules/cargo/bounties/mech.dm
code/modules/cargo/bounties/medical.dm
code/modules/cargo/bounties/mining.dm
code/modules/cargo/bounties/reagent.dm
code/modules/cargo/bounties/science.dm
code/modules/cargo/bounties/security.dm
code/modules/cargo/bounties/silly.dm
code/modules/cargo/bounties/slime.dm
code/modules/cargo/bounties/special.dm
code/modules/cargo/bounties/virus.dm
modular_splurt/code/modules/cargo/bounties/assistant.dm
modular_splurt/code/modules/cargo/bounties/lewd.dm

все цены лучше смотреть через изменения, слишком много цифор.

Изменение цен баунти (попытка стимуляции игры через них, а не лагадромы)

---

code/modules/atmospherics/auxgm/gas_types.dm
code/modules/cargo/exports/large_objects.dm
code/modules/cargo/exports/sheets.dm
code/modules/reagents/chemistry/reagents/food_reagents.dm

продажа газов - понёрфлена (миазмы убиты в 0)
продажа ящиков разного калибра (но не базовые) - имеет снижение цены по мере продажи (цена за штуку быстро снижается)
продажа ткани и дюроткани - имеет снижение цены по мере продажи (цена за штуку медленно снижается (учитывая количество которое можно сделать руками)
гробы теперь считаются гробами (ранее давали 500 кредитов как ящик)
витамины теперь стоят 0.1 вместо 0.25

фиксы и нёрфы продажи части вещей

---

code/modules/food_and_drinks/kitchen_machinery/microwave.dm

Запихивание треем в микроволновку создаёт отображение продуктов внутри
Грязная микроволновка выплёвывает продукты из себя после завершения "готовки"

Небольшие изменения микроволновки

---

modular_bluemoon/SmiLeY/code/serverside/emote_panel.dm
modular_bluemoon/code/modules/mob/bluemoon_emotes.dm

У нас в билде были звуки synth_yes и synth_no, добавил возможность издавать их эмоутами.
**Ключи: _affirmative_ и _negative_ соответственно**

Добавил эмоуты утвердительного и отрицательного сигналов

---

code/modules/jobs/job_types/brig/brigdoc.dm
code/modules/jobs/job_types/brig/detective.dm
code/modules/jobs/job_types/brig/security_officer.dm
code/modules/jobs/job_types/brig/warden.dm
code/modules/jobs/job_types/command/blueshield.dm
code/modules/jobs/job_types/command/captain.dm
code/modules/jobs/job_types/command/chief_engineer.dm
code/modules/jobs/job_types/command/chief_medical_officer.dm
code/modules/jobs/job_types/command/head_of_personnel.dm
code/modules/jobs/job_types/command/head_of_security.dm
code/modules/jobs/job_types/command/quartermaster.dm
code/modules/jobs/job_types/command/research_director.dm
code/modules/jobs/job_types/juridical/bridgeofficer.dm
code/modules/jobs/job_types/juridical/lawyer.dm
code/modules/jobs/job_types/juridical/magistrate.dm
modular_bluemoon/phenyamomota/code/modules/jobs/job_types/research_director.dm
modular_splurt/code/modules/jobs/job_types/peacekeeper.dm

главы, сб и "законники" лишаются квирка при заходе за данную профу

часть проф лишаются квирка криминала

---

modular_bluemoon/krashly/code/game/objects/items/item.dm

перенос вещей "trollandrew" с первой страницы Донатов на вторую, и изменение название предмета "Neko Wallet"

Фикс в донатах у Крашли

---

code/modules/integrated_electronics/core/assemblies.dm
code/modules/integrated_electronics/core/integrated_circuit.dm
code/modules/integrated_electronics/subtypes/output.dm

Починил свет по багрепорту. Заодно починил экраны всех размеров, LED лампочки и прочие баги и рантаймы.

Сиквел починки интегралок

---

code/controllers/subsystem/machines.dm
code/game/world.dm
modular_sand/code/modules/mining/machine_bluespaceminer.dm

Теперь бс майнеры спавнят аномалии когда на z уровне больше или 5 майнеров (аномалии спавнятся на станции)

бс майнеры и аномалии

---

html/changelogs/AutoChangeLog-pr-1082.yml
html/changelogs/AutoChangeLog-pr-1093.yml
html/changelogs/archive/2024-02.yml
html/changelogs/archive/2024-03.yml

E621-Merge

---

code/modules/antagonists/eldritch_cult/eldritch_magic.dm

Добавляю микро стан, который выбивает предметы из рук + стамино урон ровно в половину

Бафф хватки Еретика

---

modular_bluemoon/fluffs/code/donator.dm
modular_bluemoon/krashly/code/game/objects/items/item.dm

по просьбам и с одобрения хозяина-донатера добавил флектарновые вещи слонам

fluffs update 2

---

code/game/machinery/doors/airlock.dm
code/game/machinery/doors/windowdoor.dm
code/modules/mob/living/taste.dm
code/modules/reagents/chemistry/reagents/other_reagents.dm
modular_splurt/code/datums/traits/negative.dm
modular_splurt/code/modules/reagents/chemistry/reagents/alcohol_reagents.dm

Вырезаю аппендиксы этого квирка, оставшиеся со времен, когда он был негативным и давал целых 3 поинта. Сейчас же в свете последних правок является больше наказанием для игроков, нежели возможностью отыгрыша - исправляю! 
Пацификация при нехватки кама в организме? Отменяю! Врезаюсь башкой при открытии двери рукой? Меняю механ и режу цифры! 
А еще микрофиксы бага разлития женского кама и прочие мелочи.

QoL: Квирк "Спермоприемник"

---

code/modules/client/preferences.dm

Позапихал тгуи для всех списков в преференсах персонажа

add tgui for preferences

---

modular_bluemoon/code/modules/client/loadout/shoes.dm
modular_splurt/code/modules/client/loadout/shoes.dm
tgstation.dme

Нормальные высокие ботинки в лодаут

Нормальные высокие ботинки в лодаут

---

code/modules/uplink/uplink_items/uplink_clothing.dm
code/modules/uplink/uplink_items/uplink_dangerous.dm

Теперь макаров в аплинке называется как макаров, а не как стечкин.
Цена на макаров понижена до с 7 до 4тк
Цена на риг интека понижена с 8 до 6тк

Удешевление макарова и рига интека + коректное название для макарова в аплинке

---

modular_bluemoon/SmiLeY/code/serverside/emote_panel.dm
modular_citadel/code/modules/mob/cit_emotes.dm
modular_splurt/code/modules/mob/living/emotes.dm

Похвально. Но не идельно. Восстанавливаю утерянный контент. Адаптирую под Блюмун.

Довожу работу сплюртов с мяуками до ума

---

modular_splurt/code/datums/traits/good.dm

Вернул квирк регенерации, общий размер хила сильно уменьшен и ограничен только для органиков. Добавлены скалирование от общего размера здоровья, а также уязвимость к огню.
:cl:
qol: …

feat: исправлен квирк регенерации

---

code/modules/mob/living/carbon/human/innate_abilities/coiling.dm

Улучшает хвосты наг, теперь граб не слетает при сворачивании. При нажатии на кнопку сжатия при активном грабе увеличивает степень граба (если активирован vore, поедает схваченное существо). Как граб, так и сворачивание не слетают, если жертва двигается (работает так же, как сопротивление грабу).
:cl: …

fix: исправлены хвосты наг

---

code/modules/jobs/job_types/service/bouncer.dm
modular_splurt/code/game/objects/items/miscellaneous.dm

Добавлено снаряжение согласно новому НРП, из весёлого: вышибале негде заряжать свой энергопистолет 0_0
:cl:
/:cl:

change: изменено снаряжение вышибалы согласно новому НРП

---

modular_sand/code/modules/mining/machine_bluespaceminer.dm

даже красивенько подсвечивает красным если пора вырубать майнеры

Осмотр бс майнера позволяет узнать нагрузку на бс сеть в регионе

---

code/__HELPERS/_extools_api.dm

Эта штука позволяет с помощью VSCode отлаживать билд удобнее.
Можно выполнять в Debug Console различные выражения.

Add auxtools_expr_stub

---

code/modules/mob/living/carbon/emote.dm
code/modules/mob/living/emote.dm

В нескольких эмоутах не хватало проверки, так что изгоняем чихающих и зевающих призраков из нашей уютной станции.

Микрофикс эмоутов

---

_maps/templates/shelter_3.dmm

у шахтёров нет доступа в бар который они-же и создали - глупо? глупо

убираем доступ на дверях пода-бара

---

_maps/map_files/generic/CentCom.dmm

Добавил слейвером стартовых скафов, немного тулбоксов и комнаты для рабов, а так же оснастил их бассейном.
Сделано по запросу https://discord.com/channels/875735187449847830/1218638215356092556

Обновление базы слейверов

---

code/game/gamemodes/dynamic/dynamic_rulesets_latejoin.dm
code/game/gamemodes/dynamic/dynamic_rulesets_roundstart.dm

удаляем причину бесполезной траты очков на соло антагониста в режиме для командных антагонистов.

Удаление еретика из тимбазы

---

code/modules/antagonists/bloodsucker/datum_bloodsucker.dm

Убираем зависимость увеличения силы от количества рабов.

Бафф вампиров

---

code/modules/antagonists/clockcult/clock_helpers/slab_abilities.dm

Текст при применении kindle больше не слышен через стены

беззвучный режим для kindle

---

modular_citadel/code/modules/clothing/suits/suits.dm
modular_splurt/code/modules/clothing/suits/vest.dm

Фикс баг-репорта https://discord.com/channels/875735187449847830/1220844115709788313

Фикс спрайта для униформы вардена и ГСБ, чтобы у антро она отображалась.

---

modular_sand/code/modules/jobs/job_types/_job_alt_titles.dm

**Theologist** (chaplain)
**Psychic** (chaplain)
**Thaumaturge** (scientist)
**Anomalist** (scientist)
**GEC Engineer** (station engineer)
**Fraudster** (assistant)

новые Альт Названия (6 штук)

---

modular_bluemoon/code/_HELPERS/text.dm
modular_bluemoon/jukebox/item_pagination.dm
modular_bluemoon/jukebox/machine_pagination.dm
modular_bluemoon/jukebox/random_song.dm
tgstation.dme
tgui/packages/tgui/interfaces/Jukebox.js

- Строка поиска теперь ищет идеально совпадение, а не сортирует самые подходящие
<details><summary>Сравнение</summary>
<p>
| Было | Стало |
| --- | --- |
| ![image](https://github.com/BlueMoon-Labs/MOLOT-BlueMoon-Station/assets/32931701/6e6bae78-a4f3-4983-8dae-654c383a40c5) | ![image](https://github.com/BlueMoon-Labs/MOLOT-BlueMoon-Station/assets/32931701/4ef4b0ec-c9ed-4af3-8b76-e8715fbf116f) |
</p>
</details> 
- Добавлена кнопка включения рандомного трека
- Переключатель страниц не отображается, если всего одна страница

Минус поиск, плюс рандом

---

code/modules/reagents/chemistry/reagents/medicine_reagents.dm

Stimulants
Restorative Nanites
Regenerative Nanites
Changeling Adrenaline
Changeling Haste
Muscle Stimulant
да, все они не будут попадаться в странных семенах и их нельзя будет отсканить Аддисеем.

Запрет части химикатов для синтеза и получения через странные семена

---

code/__DEFINES/paper.dm

0. Число допустимых символов на поле в документе увеличилось с 48 до 64.

tweak: расширяем число символов для ввода в поле документа

---

code/modules/client/preferences.dm

fix: цвет крови из преференсов теперь работает

---

code/datums/outfit.dm

Теперь можно прописать list с имплантами в outfit роли, что будут вставлены в неё при спавне.
Пример:
cybernetic_implants = list(/obj/item/organ/cyberimp/eyes/hud/security)

feat: прописываем импланты outfit

---

code/datums/datacore.dm
code/game/machinery/computer/security.dm
modular_bluemoon/criminal_quirk/criminal_quirk.dm

Теперь можно автоматически распечатать заполненный ордер на арест, нажав в консоли рекордсов СБ кнопку внизу "Generate Arrest Warrant". Далее уполномоченному лицу нужно будет только подписать и подтвердить печатью.
Теперь можно помечать кнопкой, за какие преступления член экипажа уже отбыл наказание.
Предъявленные члену экипажа центральным командованием преступления (при квирке "Нарушитель закона" или если супер-пупер крутой офицер ЦК из рядов админов лично выпишет) по-особому помечаются в консоли, а также их нельзя удалить, не имея доступа капитана ЦК.

Автоматическая генерация ордеров и другие приколы

---

code/controllers/subsystem/npcpool.dm

нули в списке генерируют каждый тик рантаймы

Фикс рантайма с нпс пуллом

---

code/modules/vore/eating/belly_obj.dm

-Немного костыльно?
-Да
-Работает и ничего не ломает?
-А это главное

fix: пофикшен баг, когда vore ломался при поедании персонажа из рук

---

code/game/objects/items/storage/firstaid.dm
code/modules/clothing/outfits/ert.dm
code/modules/projectiles/guns/energy/energy_gun.dm
code/modules/surgery/organs/augments_chest.dm
modular_bluemoon/sanecman/code/rabbit/ert.dm
modular_bluemoon/sanecman/code/rabbit/outfit.dm

0. ВТ больше не попадает в снаряжение кроликов
1. Исправлены статы защиты ригов кроликов
2. Исправлен размер и спрайт в руке пистолета ОБР
3. Добавлены аптечки медику ОБР
4. Хим имплант более не уходит в минус по зарядам

fix: хотфикс по снаряжению ОБР

---

_maps/map_files/BoxStation/BoxStation.dmm
_maps/map_files/Deltastation/DeltaStation2.dmm
_maps/map_files/SyndicateStation/SyndicateBoxStation.dmm

на боксе, дельте и синди станции
ну и на боксе ещё перенёс наконец книжку и тряпочку на стол бармену

холодос для еды на кухню

---

code/__SPLURTCODE/DEFINES/traits.dm
code/modules/mob/living/carbon/human/species.dm
modular_splurt/code/datums/traits/good.dm

0. Доп. ХП убрано
1.  Игнорируется урон не более 10 ед. до применения модификаторов от брони и резистов (брут/бёрн)
2.  Игнорируется урон не более 5 ед. после применения модификаторов от брони и резистов (брут/бёрн)

tweak: реворк стойкости

---

modular_bluemoon/krashly/modulars/clownfart/code.dm
modular_splurt/code/modules/mob/living/emotes.dm
tgstation.dme

Теперь клоун может с некоторым шансом напердеть конфетти, снизить уровень токсинов на 2 и уровень всех реагентов внутри на 2.

Clown Fart

---

code/modules/client/preferences.dm
modular_splurt/code/modules/client/preferences.dm

Butthole sprite -> Has anus. Потому что так оно и есть, в этом заложен и функционал.

Микрофикс переключателя органа

---

code/modules/client/preferences.dm

Теоритически, так же может пофиксить редкий баг, когда у персонажа нет маркингов, но при спавне они появляются.

QOL: Кнопка для удаления маркингов с персонажа

---

code/__DEFINES/layers_planes.dm
code/modules/escape_menu/details.dm
code/modules/escape_menu/dimmer.dm
code/modules/escape_menu/escape_menu.dm
code/modules/escape_menu/home_page.dm
code/modules/escape_menu/leave_body.dm
code/modules/escape_menu/title.dm

1. Кнопки кликабельны
2. Серые кнопки не подчёркиваются при наведении
3. Заголовок теперь Comic Sans MS

Fix and improve ESC menu

---

modular_bluemoon/shower_trait/shower_trait.dm

Shower Need Update Seven

---

code/datums/character_profile.dm

Починил флавор боргов (наверное)

---

modular_bluemoon/shower_trait/shower_trait.dm

Пробую новый тип фикса оверлея

Shower Trait Fix Eight

---

modular_bluemoon/Gardelin0/code/clothing/underwear/portals.dm
modular_sand/code/game/objects/items/fleshlight.dm

Добавление описаний, включение публичного режма трусов через alt+click, оповещение о новых публичных устройствах, микрофикс багов.

Portal panties QoL update

---

code/game/objects/structures/tables_racks.dm

Фикс потери пациента при стаскивании его со стола с последующим заклкиванием стола

Фикс оставления маски на пациента после стаскивания с хирургического стола

---

code/modules/clothing/glasses/_glasses.dm
modular_sand/code/datums/components/interaction_menu_granter.dm
tgui/packages/tgui/interfaces/MobInteraction.tsx

Все по классике: сплюрты ломают - Я чиню. Ведь кто, если не Я.
+вероятная починка welding goggles
Смайли, не забудь откатить вот это https://github.com/BlueMoon-Labs/MOLOT-BlueMoon-Station/commit/ded902333247aeb936846851b2b8afbaf1a36b53
Иначе могут быть проблемы

Fixing ERP panel, part 2

---

code/modules/mob/living/carbon/human/emote.dm
code/modules/mob/living/emote.dm

Запрещаю вам плакать и нюхать в лобби (1984)

---

_maps/map_files/generic/CentCom.dmm
code/modules/mob/living/carbon/human/emote.dm
code/modules/mob/living/emote.dm

Изменил комнату для интернов. Изменения лежат в: https://discord.com/channels/875735187449847830/1136948085923270676

Интерны теперь живут лучше

---

code/modules/paperwork/paper.dm

Теперь проще ржать всем мостиком с факсов ЦКшных интернов.

Добавил возможность подсматривать в бумажки, которые кто-то держит

---

_maps/splurt_maps/map_files/Smexistation/Snaxi_Splurt.dmm

+Кабинет НТРА
+Склад в хирургии
+Второй вход в кабинет психолога
А так же мелкие изменения карты

Кабинет НТР-а на смекси + мелкофиксы

---

code/game/objects/items/shrapnel.dm
code/modules/projectiles/ammunition/_firing.dm
code/modules/projectiles/projectile.dm
code/modules/vehicles/mecha/equipment/weapons/weapons.dm
modular_bluemoon/code/modules/projectiles/projectile.dm
tgstation.dme

Попадание по лежачим целям происходит во всех интентах, кроме help.
https://github.com/BlueMoon-Labs/MOLOT-BlueMoon-Station/assets/78963858/eeecfe5e-c94b-440e-a76b-3eda9796813b

Стрельба по лежачим

---

code/__DEFINES/research/stock_parts.dm
code/game/machinery/Sleeper.dm
code/game/machinery/autolathe.dm
code/game/machinery/bloodbankgen.dm
code/game/machinery/cell_charger.dm
code/game/machinery/spaceheater.dm
code/modules/food_and_drinks/kitchen_machinery/monkeyrecycler.dm
modular_bluemoon/SmiLeY/aesthetics/multicellcharger/code/multi_cell_charger.dm

Автолат минимум 2 года не грейдился от деталей нормально. Я уже говорил, что на сплюртах тру говнокодеры сидят? Исправил прочие проблемы с улучшением механизмов. Где-то добавил/исправил описание.

Machinery upgrade fix

---

code/modules/antagonists/eldritch_cult/eldritch_items.dm

Теперь кроме сообщения в чате о местоположении жертвы сердце еретика будет показывать его дополнительно текстом над куклой

Heretic heart now send baloon alert with chat message

---

code/controllers/subsystem/timer.dm

Данное описание не оформлено, потому что одна строчка кода.

Fix of runtime

---

code/_onclick/hud/action_button.dm
code/datums/action.dm
code/modules/keybindings/setup.dm

Вернул возможность ставить кейбиндинги на кнопки способностей

Add possibility to bind buttons(again)

---

modular_bluemoon/SmiLeY/code/hilbertshotel_ghost.dm

экстовым антагам можно в инфинити

---

code/game/objects/items/melee/misc.dm
code/modules/food_and_drinks/drinks/drinks/bottle.dm
code/modules/projectiles/gun.dm
modular_bluemoon/Fink/code/items/weapons/nullrod.dm
modular_splurt/code/game/objects/items/weaponry/melee.dm

Запрет бесконтактной ебли ружьями сквозь одежду. Буквально 1984.

Удаление ЕРП

---

tgui/packages/tgui-dev-server/reloader.js

(уркадено с тг)
Теперь можно запускать dev сервер для проверки тгуи в режиме реального времени

fixed tgui development server

---

modular_bluemoon/SmiLeY/code/nanosuit/nanosuit.dm

Чиню Hugs of the North Star. И оригинальные боевые перчатки в придачу. Объем изменений захватывает дух.

Fix hug gloves

---

_maps/RandomRuins/SpaceRuins/BlueMoon/forgotten_ship.dmm

Подправил все то, что выявилось при более детальном прохождении уже после мержа ремапа. Возможно, в будущем еще чего-нибудь найду и поправлю

Минорные фиксы ремапа Часть1

---

code/game/objects/items/storage/uplink_kits.dm
code/modules/uplink/uplink_items/uplink_bundles.dm
code/modules/uplink/uplink_items/uplink_devices.dm

Добавляем набор конвертации (наушника) InteQ
Добавлено:
Набор конвертации InteQ ценой в 1 тк
состав набора:
- ключ шифрования InteQ
- Улучшение на наушник для защиты от светошумовых гранат
Были удалены предметы по отдельности из аплинка

Add InteQ Conversion Kit

---

_maps/RandomRuins/SpaceRuins/BlueMoon/forgotten_ship.dmm

Подправил еще пару мелочей в надежде на лучшее. Больше никаких АПЦ в воздухе

Поправки конфликтов карты InteQ 

---

code/modules/mob/living/carbon/human/examine.dm

Урон по персонажу скаллируется от его максимального ХП.
Урон менее 75% - незначительный.
Урон менее 50% - тяжёлый
Урон менее 25% - очень тяжёлый
Урон менее 0% - смертельно опасный

Examine Damage Scale From Size

---

code/modules/clothing/spacesuits/hardsuit.dm

Вернул старые статы ригу СБ и ГСБ
риг СБ:
armor = list(MELEE = 35, BULLET = 15, LASER = 30,ENERGY = 10, BOMB = 10, BIO = 100, RAD = 50, FIRE = 75, ACID = 75, WOUND = 30)
риг ГСБ:
armor = list(MELEE = 45, BULLET = 25, LASER = 30, ENERGY = 10, BOMB = 25, BIO = 100, RAD = 50, FIRE = 95, ACID = 95, WOUND = 40)

decreased security hardsuit stats

---

code/controllers/subsystem/vote.dm

Если прошлым динамиком была тимбаза, то не может ролиться хард, и наоборот.
Почему? Потому что иначе у нас эффективно постоянно есть шанс, что дважды будет кровавый режим, что не особо честно относительно общего распределения.
Помимо этого, смысл тимбазы зачастую теряется из-за педального щитспавна не командных антагов или ПЕРЕщитспавна по причине "ну ведь это хард/тимбаза".

Динамик и тимбаза не могут ролиться одна после другой

---

code/modules/integrated_electronics/subtypes/lists.dm

Пока в тестмерж, надо проверить стабильность их работы "под нагрузкой"

Ускорение работы плат категории list в микросхемах

---

code/modules/awaymissions/corpse.dm

Возможно, починил выбор языков и лодаут реликвий гостролям. А может и нет, хз, мне лень проверять. :clueless:

Фиксы гостролек

---

code/modules/client/preferences.dm
code/modules/mob/living/carbon/human/innate_abilities/customization.dm
modular_bluemoon/fluffs/code/donator.dm
modular_bluemoon/size_tool/size_tool.dm

сайз тул получил пару переменных чтобы крутить максимум размера, минимум, модификатор заряда и время работы
изменятели тела могут съесть сайз тул с верхним порогом выше своего текущего и получить возможность изменять тело до порога сайз тула (с x2 временем изменения тела)
ну и поправил описание изменения тела вместо пенальти от хп именно изменение скорости и хп от размера
добавлено немного донатерского шмота

сайз тул и приписки о размерах

---

code/game/objects/structures/flora.dm

Ну и сверху возможность их "точно" расположить на турфе (для красоты и чтобы наконец их случайно не таскали из стороны в сторону)

Возможность прикрутить кусты (искусственные растения)

---

modular_bluemoon/kovac_shitcode/code/modules/guns/weapons.dm

Увеличил вместимость магазинов G-22 до 21 патрона, что бы поднять полезность пистолета в выборе оружия

Увеличил вместимость магазинов Г-22 до 21 патрона

---

code/modules/projectiles/guns/energy/laser.dm

Баф не популярного оружия СБ, поддержаный большинством голосов в дискорде.

Выдал лазерному карабину режим отсечки по два выстрела.

---

code/game/objects/structures/tables_racks.dm

На локалке почему-то не начиналась игра

Фикс удаленности хирургических столов

---

modular_bluemoon/shower_trait/shower_trait.dm
modular_bluemoon/shriek_trait/shriek_trait.dm

Фикс нажатия на кнопки крикуна и переключения режима квирка душа

---

code/game/objects/items/miscellaneous.dm
code/game/objects/items/pet_carrier.dm

Исправлен баг с воздухом в переноске.
Лимит вмещаемых размеров для фелинидов увеличен 80%-> 90%.

Pet carrier rework

---

code/modules/antagonists/revolution/revolution.dm
code/modules/cargo/blackmarket/blackmarket_uplink.dm

скидка 99% хедревам на черном рынке

Rev Blackmarket build

---

_maps/RandomRuins/SpaceRuins/BlueMoon/forgotten_ship.dmm

Посоветовался с игроками в очередной раз и исправил пару штук, которые им мешали.

Полировка карты гостроли Интекью

---

code/__DEFINES/combat/stamina_combat.dm
code/controllers/configuration/entries/combat.dm
code/modules/mob/living/carbon/human/species.dm
tgstation.dme

Теперь поднятие пкм-ом описано в конфиге как процентное значение от максимальной полученого урона от стамины(на текующий момент 20% от 200, то-есть 40, раньше было 15)

Combat changes

---

code/modules/cargo/packs/medical.dm
code/modules/projectiles/guns/misc/medbeam.dm

Портирован механ бимганов из актуального тг
Бимган на мехе теперь хилит не в 2 раза сильнее чем обычный бимган а в 2 раза слабее 
Убраны обычные бимганы из карго, теперь на их месте ослабленая версия обычного бимгана в количестве 50000 за 1 штуку
Ослабленый бимган не лечит трупы, лечит по 0.8 брута и ожогов если не в крите и по 2 брута и ожогов если в крите + 0.5 токсинов и 5 окси урона.

beamgun changes

---

_maps/map_files/FestiveBall/FestiveStation.dmm

1. Доработал изоляцию в комнатах
2. Починил окна (заменил)
3. Добавил точку посадки ксено шаттла
4. Переделал дорогу под правостороннее движение
5. Добавил телепорт в дормы
6. Удалил турбину
7. Подправил атмос
8. Добавил источники света в бриг
9. поправил отображение АПЦ на которые жаловались
10. Добавил точки спавна зекам

Фикс работы от фидбека игроков на фестив станции

---

modular_bluemoon/fluffs/code/donator.dm

Добавил сикей Алазариуса в донатайтем по просьбе.

added Ckey to donator item

---

code/controllers/subsystem/vote.dm

- При автоматическом голосовании за смену карты, происходящем после краша сервера, появился вариант "Не менять карту", который отменяет перезагрузку.
- При отсутствии голосов в этом воуте Пентагон больше не высылает опергруппу проверки демократичности и свободности выборов, ломающую запуск сервера, а перезагрузка просто отменяется.
- После отмены ротации карты время до старта снижено с 10 минут до 4.

Улучшил систему автоматической ротации карт после краша

---

modular_bluemoon/fluffs/code/donator.dm

Добавил сикей Адры в айтемы Широ и Хахуна (они дали добро на это).

Added adro Ckey to Shiro's donator item (Adro got permision to be added)

---

modular_bluemoon/fluffs/code/donator.dm

Написали мой сикей с большой буквы, в вайтлистах он должен быть с маленькой

исправил ошибку

---

modular_splurt/code/modules/mob/living/emotes.dm

divide mrrp into mrrp and mrrp2

---

code/modules/clothing/spacesuits/contractor_hardsuit.dm

Исправление бага крюка на моде контрактника, при котором агрессивный хват срабатывал только при выстреле в упор. Данное обновление исправляет данный баг, а также исправляет вызываемые runtime ошибки при взятии крюка в руки.
Контрактники теперь смогут использовать свой крюк по назначению.

Fix contractor hook

---

modular_citadel/code/modules/client/loadout/__donator.dm

фикс иконок говна

---

code/game/objects/items/storage/uplink_kits.dm
code/modules/paperwork/paperplane.dm
code/modules/uplink/uplink_items/uplink_stealth.dm

Спустя кровь и пот я смог добавить кит с оригами в аплинк.....

Origami Kit

---

modular_bluemoon/fluffs/code/donator.dm

Смнеил старый сикей Адро на новый. Добавил ещё одного человека в кастомки (С разрешения), плюс вписал Михану в кастомку Ковача (С разрешения)

added 3 ckeys

---

modular_bluemoon/heavy_and_superheavy_quirks/traits.dm

Фикс квирка пожирателя

---

code/datums/status_effects/buffs.dm

редхарт немного не туда поместил ауру лечения, исправляем ошибочку и добавляем комментарии

Fixed redheart's mistakes in pr

---

code/modules/clothing/masks/gasmask.dm
modular_bluemoon/fluffs/code/donator.dm
modular_bluemoon/fluffs/code/guns.dm

Пофиксил чужую маску + пофиксил описание модкита + вписал сикей игрока в свои айтемы.

Donator-items-fixes

---

modular_bluemoon/Gardelin0/code/clothing/underwear/portals.dm

Что нового?
У порталок теперь можно сменить иконку на любые трусики.

Порталки-Хамелионки

---

modular_bluemoon/Gardelin0/code/clothing/loadout/backpack.dm
modular_splurt/code/modules/client/loadout/gloves.dm
modular_splurt/code/modules/client/loadout/head.dm
modular_splurt/code/modules/client/loadout/mask.dm
modular_splurt/code/modules/client/loadout/neck.dm
modular_splurt/code/modules/client/loadout/suit.dm
modular_splurt/code/modules/client/loadout/uniform.dm

Докинул в лодаут одежду из гражданского синдроба.
Ну и тпа батплаги просили, их тоже докинул

Обновление лодаута

---

code/__HELPERS/mobs.dm
code/datums/datacore.dm
code/game/machinery/computer/security.dm

- Теперь большинство действий в консоли логгируется. Логи можно распечатать.
- Консоль больше не ломается, если разлогиниться во время печати, потому что разлогиниться больше нельзя (:trollface: )

Логи для консоли СБ + исправление бага печати

---

code/modules/cargo/exports/food_wine.dm
code/modules/cargo/exports/gear.dm
code/modules/cargo/exports/large_objects.dm
code/modules/cargo/exports/materials.dm
code/modules/cargo/exports/sheets.dm
code/modules/cargo/exports/weapons.dm

сильно увеличил число предметов, удешевляющихся по мере продажи

решаем рыночек

---

code/controllers/subsystem/blackbox.dm
code/modules/admin/verbs/adminhelp.dm
code/modules/admin/verbs/adminpm.dm

В данном ПРе вносятся небольшие изменения в логирование тикетов в базе данных.

Исправление логирования тикетов в БД для расчета KPI

---

modular_bluemoon/fluffs/code/donator.dm

Вписал по мелочи разные сикеи в предметы, которые просили сделать за прошлую неделю.

donator-ckeys-add

---

code/game/objects/structures/tables_racks.dm
code/modules/surgery/helpers.dm
code/modules/surgery/surgery.dm

Добавляем подсказку для экипажа, что оперировать сверхтяжелых персона…жей на операционном столе не обязательно.
Появляется при начале операции. Постепенно будет учить экипаж прямо в игре.
Алсо, фиксим ошибочный фикс.

Подсказка для хирургов насчёт сверхтяжей

---

tools/changelog/generate_cl.py

Убираем ошибку при отсутствии чейнджлогов, которые и так у нас не компилятся
:cl:
/:cl:

Крестики люблю пиздец

---

code/modules/plumbing/plumbers/pill_press.dm

пофиксил баг с невидимыми заводскими патчами

чиним патчи завода

---

code/__DEFINES/misc.dm
code/datums/components/mood.dm
code/modules/antagonists/clockcult/clock_structures/ark_of_the_clockwork_justicar.dm
code/modules/antagonists/clockcult/clockcult.dm
code/modules/antagonists/cult/cult.dm
code/modules/mob/living/carbon/human/human_update_icons.dm
code/modules/reagents/chemistry/reagents/other_reagents.dm

Исправляет баг, когда руна над головой после деконвертизации у культиста не пропадала
Помимо этого теперь нимб должен быть над персонажем, а не под ним
fix: Нимб культиста теперь пропадает при деконверте

Fix: Нимб культиста после деконверта

---

code/modules/mob/living/silicon/robot/robot_modules.dm
modular_splurt/code/modules/mob/living/silicon/robot/robot_modules.dm

я добавил только станционным чтобы умники с гпс не палили антагов боргов на спавне

добавить станционным боргам гпс

---

tgui/packages/tgui/components/Section.tsx
tgui/packages/tgui/interfaces/PaperSheet.tsx

Фиксит печати, которые можно было поставить лишь в левом-верхнем углу.
Печати работают.
N

Fix: Печати на бумагах

---

code/modules/mob/living/silicon/robot/robot_defense.dm

Добавлена возможность использовать лом (и всё что считается ломом по механике игры) для нанесения повреждений киборгам с помощью харм интента.

Харм взаимодействия ломом на киборгов

---

modular_bluemoon/fluffs/code/donator.dm

Добавил пару сикеев в кит, ничего такого *shrug

2ckeys-add

---

code/game/machinery/cryopod.dm

Фиксим телепортацию крио вещей. Теперь они перемещаются в своё хранилище и не срут оповещениями на станцию, когда перемещение вне станции.

Фиксим криосон (перемещение вещей, оповещения, запись в компьютер)

---

_maps/templates/apartment_jungle.dmm
_maps/templates/apartment_winter.dmm
code/modules/ruins/spaceruin_code/hilbertshotel.dm
modular_bluemoon/SmiLeY/code/hilbertshotel_ghost.dm

По просьбе многих ребят я решил замаппить вам зимние инфинитдормы, которые к новому году будут ещё допилены под новогоднюю тематику для вашего приятного времяпрепровождения

Новые инфинитдормы + малюсенькое исправление джунглевых инфинитдорм

---

code/modules/hydroponics/biogenerator.dm

Глаза вытекают видеть видеть 1.333333 значения. После улучшения значения эффективности становится больше единицы. Например, 4 эффективности. А формула подсчета стоимости `биомасса (15) / эффективность (4) = 2.5` и цифр после запятой может быть до тысячной.
Теперь будет так:
Кнопки перестанут расстягиваться до тысячных в значениях.
Нет.
:cl:
fix: при улучшении биогенератора стоимость товаров уменьшалась до значений с плавающей запятой
/:cl:

Округление стоимости товаров в биогенераторе

---

_maps/templates/apartment_winter.dmm

сделал всё поцивильнее, так ещё и костёр работает, ага)

Окончательный фикс зимний инфинитов

---

SQL/tgstation_schema.sql
_maps/map_files/PubbyStation/PubbyStation.dmm
code/modules/library/computers/checkout.dm

Из-за ошибки в коде было невозможно загрузить книгу в базу данных.
На Пабби дополнительно перенесено расположение сканнера книг
Поддержка творчества на Голубых Лунах
N

Fix: Книги не загружаются в БД библиотеки

---

code/modules/mining/equipment/marker_beacons.dm

Маячки, вручную поставленные на карте с определенным цветом не имеют иконки и выглядят невидимыми
Невидимые иконки у шахтерских маячков это плохо
N

Fix: Маячки

---

modular_bluemoon/Fink/code/items/implant_anchor.dm
modular_splurt/code/game/area/areas/ruins/space.dm

add: добавлен урон мозгу от якоря в размере 5 единиц в тик
add: добавлен якорь прослушке

tweak: доработка якоря

---

code/game/machinery/cryopod.dm
code/modules/client/preferences.dm

Фикс педальной кнопки отправки в крио.

admin_cryo_button_fix

---

_maps/map_files/generic/CentCom.dmm
modular_bluemoon/Gardelin0/code/antagonists/ghost_spawner.dm

Wendigo amount

---

code/modules/station_goals/dna_vault.dm

Однострочный фикс. Делает список генов у ДНК хранилища общим. Хотя я бы ещё плюсом стирал списки у ДНК сэмплеров при сдаче ДНК в хранилище.
Предотвращает реролл или манч генов через постройку нескольких хранилищ или снос с последующим возведением одного и того же хранилища.
❌
:cl:
fix: DNA Vault no longer provides the option to endlessly reroll "genes choice" by rebuilding the vault.
/:cl:

bugfix: DNA Vault static gene choice.

---

code/modules/projectiles/guns/ballistic/magweapon.dm

Повысил КД выстрела в автоматическом режиме для магпистолета, до этого это было лютым press LMB to win оружием.

magpistol-rebalance

---

_maps/RandomZLevels/away_mission/Academy.dmm
_maps/RandomZLevels/away_mission/wildwest.dmm

микрофиксы заслуженные
Olgachan исправляет свои косяки и на этом халас

патч для пары обновлённых гейтов

---

_maps/RandomZLevels/away_mission/Academy.dmm

Очередное чудо от Olgachan
И так, вторую часть переработок гейтов официально можно считать закрытой. Так что в связи со скорым началом учебного года (press F половине онлайна БМа) я переделал Академию магов. ТАК ЧТО ОНИ` СОМА СУЧКИ!
Ключевые изменения
И вот осенние каникулы совсем скоро закончатся, новые ученики прибудут, а держать их негде. Так что состав директоров заставил местных магов сделать огромную перестройку и её "редизайн"
Да, Гейт в некоторых частях будет выглядеть "незаконченным" Везде лежат инструменты и материалы. (Помогите бедному Дефендеру Академии достроить локацию) А где-то и вообще из-за невнимательности часть персонала сильно пострадала или умерла
В целом гейт был увеличен. Больше места для защитника... Теперь там не так скучно.
Из новых помещений - Дормы, медблок, …

ONI SOMA BITCHES!

---

code/datums/character_profile.dm
code/modules/mob/living/carbon/human/examine.dm
tgui/packages/tgui/interfaces/CharacterProfile.tsx

СМОТРЕТЬ ПОДРОБНО ВНУТРИ.
Отображение разрешения на ЕРП механ исправлено в плане руссификации. Смайли зачем-то написал "всяческие непристойности", когда в оригинале и по коду это влияет только на механ. Изменение одобрено.
Отображение разрешения на ЕРП механ перенесено из экзейма в ООС флавор.
Initial:

Изменение отображения разрешения на ЕРП механ

---

modular_splurt/code/datums/components/pregnancy.dm

-Теперь точно никаких яиц быть не должно

Фикс трейта на беременность

---

modular_bluemoon/fluffs/code/donator.dm

catcrin-stuff-prizrak-ckey-add

---

modular_bluemoon/code/modules/mob/bluemoon_emotes.dm

Подфиксил название эмоута + его отображение при активации.

mrrp-quick-fix

---

modular_bluemoon/heavy_and_superheavy_quirks/traits.dm

Микрофикс возврата переменных при педальном удалении сверхтяжа у игрока

---

code/modules/atmospherics/machinery/datum_pipeline.dm

Убрал лишнее логгирование, потому что оно слишком нагружает сервер

---

modular_bluemoon/code/modules/arousal/arousal_robot.dm

Крохотное исправление.
Теперь минимальное значение при выборе будет 5 как и должно быть.

little fix

---

code/__SPLURTCODE/DEFINES/quirks.dm
code/modules/mob/living/carbon/carbon_defense.dm
modular_splurt/code/datums/mood_events/dominant_events.dm
modular_splurt/code/datums/traits/negative.dm

Незначительные изменения квирка дрессированного, в том числе удаление плохого модификатора настроения при получении хорошего.

Исправления квирка дрессированного

---

_maps/map_files/Deltastation/DeltaStation2.dmm

Починил почтовые трубы на дельте. Теперь почта не будет улетать в мусорку
:cl:
add: фильтроционые трубы в бриге
fix: Почтовые трубы
/:cl:

Fix - Delta Station - Postal Pipes

---

README.md

Удаление лишнего из README после мерджа.

Чистка README

---

modular_bluemoon/code/modules/clothing/underwear/tape_underwear.dm
modular_bluemoon/fluffs/code/donator.dm

Народ хочет, донатер не был против (предмет и так в общем доступе).

Черный скотч в общий лодаут

---

code/__DEFINES/layers_planes.dm
code/_onclick/hud/plane_master.dm
code/modules/events/anomaly/_anomaly.dm
code/modules/events/anomaly/anomaly_ectoplasm.dm

А как какать?
:cl: Ghost Crystalic
fix: 200% something is fixed with admin abuse anomaly spawn and grav plane
/:cl:

Выдаем теневой бан челолюду (troubleneko17th)

---

code/modules/antagonists/cult/cult_items.dm

Накинул щиту культа вместо обычного падения - паралич. (Да, сменить одну строчку было так тяжело....)

cult_shield_rebalance

---

modular_bluemoon/fluffs/code/donator.dm

Вписал пару сикее по запросу + разрешению.

donator_items_requests

---

_maps/RandomRuins/LavaRuins/bluemoon/lavaland_surface_syndicate_base1_bluemoon.dmm
_maps/map_files/Mining/Lavaland_novaya.dmm

Визуальные и геймплейные улучшения карты аванпоста ДС-1
Удобные и красивые гострольки это крута

[QOL] Deep Space I - добработки карты

---

_maps/map_files/Mining/Lavaland_novaya.dmm

Я мальца проебался с трубами, когда заменял `visible` на обычные через "Search by prefab"
hell yeah

Фикс труб на ДС-1

---

code/game/objects/items/storage/belt.dm

РЦД и РПД лезут в туллбелт. Пог?

rcd_rpd_into_toolbelt

---

code/modules/projectiles/guns/ballistic/automatic.dm
code/modules/projectiles/projectile/bullets/smg.dm

Попытка вновь немного подбалансить урон  ВТшке.

wt550_rebalance_again

---

_maps/RandomRuins/SpaceRuins/listeningstation.dmm
_maps/map_files/Mining/Lavaland_novaya.dmm

Вернул украденные непонятно кем шлюзы на ДС-2, поправил утилизационные трубы и доступ к уборным. Убрал три миллиарда дублирующих друг друга ЛКП в одной области
Прослушка обзавелась нелетальным оружием в виде двух дубинок контрактников и коробки наручников с целью минимизации летального пресечения, а также получила два модуля хранилища и фонарика для МОДов, чтобы сделать их хоть чуточку полезными
багфиксы это харашо

[FIX] Немножко чиним гостроли синдиката

---

tgui/packages/tgui/interfaces/Techweb.js

Усё будет намальна! Но лучше тест мерж.

Enabling RnD console tooltips

---

modular_bluemoon/modules/pig_barks/pig_barks.dm
tgstation.dme

Добавлены 3 новых барка на основе эмоутов - различные тональности поросячего хрюканья.
На основании таких работ, как:
- https://github.com/BlueMoon-Labs/MOLOT-BlueMoon-Station/pull/1203
- https://github.com/BlueMoon-Labs/MOLOT-BlueMoon-Station/pull/1265
Расширение ролевого взаимодействия. Свобода в выборе и настройке персонажа. Качественный отыгрыш хряков.

Барки для хряков, кабанов, свиней, поросят, 

---

code/modules/mob/living/carbon/emote.dm
code/modules/mob/living/carbon/human/emote.dm
code/modules/mob/living/emote.dm
modular_bluemoon/code/datums/traits/neutral.dm
modular_bluemoon/code/modules/mob/bluemoon_emotes.dm
modular_citadel/code/modules/mob/cit_emotes.dm
modular_splurt/code/modules/mob/living/carbon/human/species_types/teshari.dm
modular_splurt/code/modules/mob/living/emotes.dm
modular_splurt/code/modules/mob/living/silicon/emotes.dm

Срочные фиксы к мержу

---

modular_citadel/code/modules/reagents/chemistry/reagents/enlargement.dm

Передоз суккубьим молоком, теперь, удаляет танцор
Минусы - Суккубье молоко больше не делает из человека футу
Плюсы - Суккубье молоко больше не делает из человека футу
Nova-Sector
- [Да] You tested this on a local server.
- [Да] This code did not runtime during testing.
- [Да] You documented all of your changes.
:cl:
code: Суккубье молоко, теперь, удаляет танцор при передозе.
/:cl:

Succubus milk change

---

code/modules/mob/living/carbon/human/species_types/shadowpeople.dm

QoL изменения Кошмара
Кошмар стал, косметически, чуть больше предрасположен к ролевой игре.
Nyet
- [Да] You tested this on a local server.
- [Да] This code did not runtime during testing.
- [Да] You documented all of your changes.
:cl:
qol: some QoL changes of Nightmare
/:cl:

Beautifying Nightmare

---

code/modules/mob/living/carbon/alien/emote.dm

hiss emote fix

---

_maps/map_files/BoxStation/BoxStation.dmm
_maps/map_files/PubbyStation/PubbyStation.dmm
_maps/templates/apartment_sportzone.dmm

Заного и полностью своими руками переделал систему вентеляций, сделав её более удобной для перемещения по ней.
Добавил изменения пабби, которые почему-то не замерджелись

Переделал вентеляции на бокс стейшен

---

modular_bluemoon/fluffs/code/donator.dm

Делюсь с человечком персоналкой *тык-тык пальчики*

Делюсь персоналкой

---

code/modules/mob/living/carbon/emote.dm
modular_bluemoon/code/modules/mob/bluemoon_emotes.dm

Fix emote sounds

---

code/modules/mob/living/carbon/human/species.dm
modular_bluemoon/code/datums/interactions/_interaction.dm

Теперь шлёпать по заднице ребят с квирком "стальные булки" реально страшно.

Ass we can

---

modular_splurt/code/modules/reagents/chemistry/recipes/drugs.dm

Это нужно для моего крутого плана для помощи викиделам бтв.

Починил хуйню за пиндосами

---

code/modules/mob/living/living_defense.dm

Лёгкие персонажи не получают дебафф брони из-за размера

---

code/game/objects/items/implants/implant_cqc.dm
code/modules/clothing/head/misc.dm
code/modules/clothing/outfits/ert.dm
code/modules/clothing/outfits/standard.dm
tgstation.dme

tweak: поменял форму CentCom Commander. В том числе добавил набор имплантов аналогичный Special Ops Officer
tweak: добавил имплант CQC. Выдал его ролям ЦК (Special Ops Officer, Centcom Offical, CentCom Commander) за место импланта Krav Maga ибо последний показал себя максимально бесполезным

Minor Centcom outfit fixes

---

code/modules/mob/living/carbon/carbon_defense.dm

felinid autowag fix

---

modular_bluemoon/fluffs/code/donator.dm
modular_bluemoon/oni3288/code/catcrin_stuff.dm

Пофиксил местами хуйню свою, где налажал, ничо особого.

fixing-my-shitcode

---

code/__BLUEMOONCODE/_DEFINES/slowdowns.dm
code/modules/mob/living/living_movement.dm
modular_bluemoon/modules/pull_slowdown/pull_slowdown.dm
tgstation.dme

- Добавлено замедление при пулле другого персонажа.
- Текущее замедление - 0.5. Для сравнения, замедление от пулла тяжелого персонажа 1.5
- Не складывается с другими замедлениями от пулла.
- Одобрено Смайли

Замедление от перетаскивания персонажей

---

code/datums/martial/cqc.dm
code/datums/martial/krav_maga.dm
code/modules/jobs/job_types/command/blueshield.dm
code/modules/jobs/job_types/service/bouncer.dm
code/modules/jobs/job_types/service/cook.dm

добавление банусерам вместо их боевого стиля впиздрючивания в стену уже кравмаги с ограничением на баре

баунсеры с крав магой в баре

---

modular_citadel/code/modules/reagents/chemistry/reagents/healing.dm

Цеолит теперь работает и на синтетов (Synthetic Anthropomorph и Synthetic Lizardperson) согласно логике описания: 
> Lab made Zeolite, used to clear radiation from people and <ins>**items**</ins> alike!

Zeolite flag ALL

---

config/bluemoon/discord.txt
modular_bluemoon/phoenix404/code/_HELPERS/roundend.dm
modular_bluemoon/phoenix404/code/entries.dm

[TGS] Reduce roundend embed size, add the last message to the clip.

---

code/datums/accents.dm
code/modules/awaymissions/mission_code/jungleresort.dm
code/modules/clothing/head/jobs.dm
code/modules/clothing/head/misc.dm
code/modules/clothing/masks/boxing.dm
code/modules/clothing/masks/miscellaneous.dm
code/modules/mob/living/carbon/human/species_types/dwarves.dm
code/modules/mob/living/carbon/say.dm
code/modules/mob/living/say.dm
code/modules/ninja/suit/mask.dm
modular_splurt/code/__HELPERS/text.dm

эмоуты через ! (которые ещё можно в радио писать) теперь не обрабатываются акцентами и спич модифаями языка, не коверкая эмоуты

фикс эмоутов через ! с акцентом

---

modular_bluemoon/MRSKO/code/uplink/uplink_items.dm

Убрал из стоимости мода стоимость ЕМП щита. Не видел, что бы покупали мод, а надо покупать

Уменьшил стоимость мода

---

code/game/objects/items/weaponry.dm
code/modules/mob/living/taste.dm
modular_bluemoon/code/modules/reagents/chemistry/reagents/other_reagents.dm
modular_splurt/code/datums/traits/negative_quirks/dumb_for_cum.dm
modular_splurt/code/modules/reagents/chemistry/reagents/other_reagents.dm
tgstation.dme

- Владельцы квирка "Спермоприемник" получают визуальные и прочие эффекты от потребления или нехватки сомнительной жидкости. 
- Слизанные с пола жидкости теперь потребляются организмом.
- Рефакторинг моего старого кода, устранение конфликтов.

Микрофичи для dumb4cum

---

code/game/objects/structures/crates_lockers/closets/secure/scientist.dm
modular_bluemoon/code/game/objects/items/devices/multitool.dm
tgstation.dme

мультитул с подвязанным к станционному сило в ящик рд
точно не имеет шанса вызвать сердечный приступ у игрока 1 из 100 случаев
https://discord.com/channels/875735187449847830/1314558909612167290

Мультитул с подвязанным сило в ящик рд

---

modular_bluemoon/code/modules/reagents/chemistry/reagents/other_reagents.dm
modular_splurt/code/datums/traits/negative_quirks/dumb_for_cum.dm
modular_splurt/code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
modular_splurt/code/modules/reagents/chemistry/reagents/other_reagents.dm

Закрываю багрепорт, чищу мои старые лишние наработки, исправляю конфликты, оптимизация. Лучше, чем было.

[BLUEMOON] Работа с dumb4cum 2

---

modular_bluemoon/station_agents_cards/cards_id.dm

Фикс возможности изменять имена, должности и другие характеристики ка…ртам синдиката из лодаута и вендора
Оказывается там проверка идёт на зареганное имя

Фикс карта синдиката

---

code/game/objects/items/cards_ids.dm
modular_bluemoon/Fink/code/clothing/deviant.dm
modular_bluemoon/kovac_shitcode/code/modules/clothing/misc.dm
modular_splurt/code/game/objects/items/cards_ids.dm

флафф карты теперь можно наклеить на другие карты
подменяет спрайт и ассаймент (иконку у сб)
название однако остаётся тем-же

стикерные карты

---

code/modules/events/holiday/xmas.dm

Теперь ёлка спавнится одна, as all things should be.

[FIX] Исправляет двойной спавн ёлки

---

code/modules/mob/living/say.dm

ВТОРАЯ попытка
In-round мне сказали, что кнопки не сработали. Поменял ЧЁТКО идентично клавишам, :w = :ц, :q = :й. Посмотрим, поможет ли. Если нет - не знаю, что поможет починить каналы ДС.

ДС-1/2, апдейт 2

---

modular_splurt/code/modules/cargo/packs/armory.dm
modular_splurt/code/modules/cargo/packs/goodies.dm

1 - Понизил стоимость обычных риот шотганов с 8000 до 6000 (Нелогично, что Риот стоят столько же, сколько и комбат.)
2 - Повысил стоимость револьвера .45 long с 800 до 1600 (Он слишком хорош для такой цены.)
3 - Повысил стоимость винтовки .45 long с 1500 до 2200 (Винтовка > Револьвер.)

cargo_guns_rebalance

---

modular_bluemoon/code/game/objects/items/devices/multitool.dm

Фикс бага со спавном подарка до спавна сило

Фикс cargonia gift без привязки к сило

---

modular_splurt/code/game/objects/items/stacks/tiles/tile_reskinning.dm

теперь можно потешно менять спрайт тайла у борга и это не ломает тайл

Фикс неработающих тайлов железа при смене их у боргов

---

code/game/objects/items/stacks/rods.dm
modular_splurt/code/game/objects/items/stacks/tiles/tile_reskinning.dm

Фикс бага с использование прутьев у борга вместо железа медицины (от чего максимум их количества был всего 10) + изменение цены под ротацию 2 прута за 1 железо (

[BLUEMOON FIX] Фикс прутьев у боргов

---

modular_bluemoon/oni3288/code/pipebomb.dm

Фиксанул насёр в код, из-за чего нельзя было крутить таймер у гранаты, ну и заметил почему конкретно пайп-бомба взрывается как обычная самоделка, ближе к выходным займусь этим фиксом.

ied_quick_fixes

---

modular_bluemoon/MRSKO/code/modules/mod/mod_theme.dm

Было 80, стало 30.
Как же насрали в Описании.

Уменьшил Wound

---

modular_bluemoon/MRSKO/code/modules/mod/mod_theme.dm
modular_bluemoon/MRSKO/code/modules/mod/mod_types.dm
modular_bluemoon/MRSKO/code/uplink/uplink_items.dm

Совсем небольшой ребаланс модсъюта Интек.
1 - армор = армору элитрига.
2 - тестировочно снижена стоимость (всё ещё дороже элитрига).
3 - заменена БС-реакторка на обычную БС.

inteq_mod_rebalance

---

.github/labeler.yml
.github/workflows/labeler.yml
.github/workflows/tgs_merge_detector.yml

Автоматизация работы на гитхабе, по управлению метками.

[GITHUB] Added action for test merge detect and autolabeling

---

code/modules/client/preferences.dm

Вводит совершенно не существующей на билде фичи в виде возможности выбрать огонь из головы для дуллухана
Багфиксы круто

Neckfire для дуллаханов

---

code/modules/mob/living/carbon/carbon.dm

фикс моей тупости (у очков проверялся тип шляп (это так не работает)
очки не работали

Перепутанный istype в очках

---

code/datums/components/dullahan.dm

При снятии, надевании одежды и чем-либо меняющим внешность персонажа это вызывало рекурсивный цикл вызывающий рантаймы без следов, боле без рантаймов (пожалуйста не бейте меня ржавой трубой за тотальное костыльное решение задачи)
Багфиксы и исправление рантаймов

Фикс одежды у дуллухан

---

modular_bluemoon/code/modules/mob/bluemoon_emotes.dm

При её активации прогрывается корректная фраза в чат
Багфикс

Фикс фразы "Какое время?"

---

code/modules/events/travelling_trader.dm

Теперь он не рантаймит
Заебало в дебаг моде на рантайм стейшене ловить из-за этого фриз процессов

Фикс появления странствующего торговца

---

modular_bluemoon/phoenix404/modules/vending/games.dm

Добавлена возможность купить лак для ногтей и помаду.
https://discord.com/channels/875735187449847830/1323824844030083072
Нужен был способ получать данные предметы внутри раунда.

Помада и лак для ногтей в вендмат

---

modular_splurt/_maps/RandomRuins/SpaceRuins/spacehotelbluemoon.dmm

Фикс отеля + немного декалей

---

code/game/machinery/limbgrower.dm
code/modules/admin/create_mob.dm
code/modules/arousal/arousal.dm
code/modules/mob/dead/new_player/preferences_setup.dm
code/modules/mob/living/carbon/human/human.dm
modular_splurt/code/datums/components/pregnancy.dm

Бесполезный верб который не имеет никакого применения и является атавизмом когда одежда была припаяна к персонажу
Очистка кода от мусора

Вырезание Toggle undergarments

---

code/game/machinery/dance_machine.dm
code/game/machinery/dance_machine_handled.dm
modular_bluemoon/Fink/code/items/moniq.dm
modular_bluemoon/jukebox/jukebox_function.dm
modular_bluemoon/phoenix404/modules/client/preferences_savefile.dm
tgstation.dme
tgui/packages/tgui/interfaces/Jukebox.js

Теперь можно добавлять треки в избранное, чтобы быстрее находить их.
В случае если по какой-то причине ваш трек был удален или изменен на сервере, название будет подсвечено красным с предложением убрать его из избранного. Вы можете попытать найти его снова, скорее всего у него поменялось название.

[TGUI] Jukebox favorites

---

code/controllers/subsystem/job.dm

фикс рантайма происходящего при попытке зайти за гостя (незалогиненный акк бьёнда) за любую профу.
(нет, я не стану пояснять причину почему я захожу за гостя во время дебага)
багфиксы

Фикс рантайма лодаута и guest

---

code/modules/events/living_entity/cat_surgeon.dm
code/modules/events/living_entity/deathclaw.dm
code/modules/events/living_entity/gigachad_inteq.dm
modular_bluemoon/Ren/Code/mobs.dm

Теперь оповещения о сбежавших заключенных приходят факсом в бриг.
DO NOT MERGE

Escapee announce change

---

code/modules/integrated_electronics/subtypes/converters.dm
code/modules/integrated_electronics/subtypes/input.dm

Добавлена интегральная плата сканера аномалии, а так же расширены возможности text to num и num to text.
Сканер аномалии выдаёт в ответ на реф точную частоту аномалии и рандомный код в пределах 10 от настоящего кода.
Делаю интегралки удобнее, а ещё я очень давно хотел добавить возможность взаимодействовать с аномалиями
https://github.com/user-attachments/assets/5da7594f-da0c-42ee-a340-aadabd0d593f

Новые интегральные платы

---

code/modules/reagents/chemistry/reagents/other_reagents.dm

исправил воду

---

_maps/splurt_maps/map_files/4Nalstation/4NaL_Station.dmm

Мусор спавнится в воздухе (над пустым турфом) при старте проверок выводя рантаймы. Фикс данной проблемы

Фикс проверок для пров

---

modular_bluemoon/oni3288/code/pipebomb.dm

Фикс 2 Misc в крафт меню

---

modular_bluemoon/Fink/code/items/summon_chalk.dm

1) Добавление отклика на отсутсвие призываемых
2) Проверки на наличие клиента в мобе
Фиксы рантаймов и дополнительные маркеры для уверенности в работоспособности

Если призываемых нет, то об этом сразу скажет при попытке призвать

---

modular_bluemoon/phoenix404/modules/vending/megaseed.dm

Они были, но их потеряли
Возвращение потерянного

Возвращение ягод в вендомат ботаников

---

_maps/map_files/Mining/Lavaland_novaya.dmm

Куча труб были повёрнуты не так
Фикс карты

Фикс красных труб на лаваленде

---

_maps/RandomRuins/SpaceRuins/spacehermit1.dmm

Он просто стоит и отдыхает (не бродит вокруг если не спровоцировать)
Данный голиаф имел тенденцию забредать в капсулу до спавна хермитов

Голиаф у спейс хермита теперь не забредает в его капсулу

---

modular_splurt/_maps/away_mission/AGRComplexClock.dmm
modular_splurt/_maps/away_mission/AGRComplexCult.dmm

Не хватало кабеля до одного из апц
Теперь кабель более целостный и всё заряжается

Фикс недоведённого кабеля в гейте AGR

---

_maps/map_files/PeaceSyndicateStation/PeaceSyndicateBoxStation.dmm
_maps/map_files/SyndicateStation/SyndicateBoxStation.dmm

Трубы криво между собой соединялись 
Фиксы карт

Фикс мусорной трубы на синди станции

---

modular_splurt/code/datums/components/crafting/recipes/recipes_clothing.dm

Теперь для крафта подходит только пустой tailbag 
Исключение шансов крафта тэйлбэга XL из тэйлбега с вещами внутри

Фикс возможности сделать tailbag XL при помощи tailbag с вещами

---

modular_bluemoon/fluffs/code/donator.dm

Добавление Noir suitskirt в личный лодаут игрока famas098. 
Второй раз потому-что у меня локалка была на старой сборке, к сожалению...

Добавление Noir suitskirt в личный лодаут игрока famas098. №2

---

_maps/map_files/PubbyStation/PubbyStation.dmm

Переименование с крематория на Brig Medical на Пабби (с заменой этого названия и на апц)
Изначальный вариант с крематорием без крематория не работает

Пабби лазарет в бриге переименован с крематория на Brig Medical

---

_maps/map_files/BoxStation/BoxStation.dmm

Болты на дверях накидываются правильно от кнопок
Заслонки закрываются правильно от кнопок
До этого одни кнопки отвечали за другую кабинку и наоборот

Фикс дорм офицеров

---

_maps/map_files/Deltastation/DeltaStation2.dmm

Перетащил чуть выше кнопку от света в комнате, чтобы та не была под кнопкой в комнате се, загараживая вид для гостов и ии
Упрощение визуального восприятия со стороны ии

Чуто подвинул переключатель света на Дельте, чтобы госты и ии видели кнопку

---

_maps/map_files/KiloStation/KiloStation.dmm

1) Пофиксил расположение апц в аплоаде ии
2) Пофиксил невозможность залинковать эксперементор с терминалом в начале раунда (да он имеет ужасный радиус работы)
Фиксы карты

Килостейшон эксперементор и аплоад ии

---

_maps/RandomRuins/LavaRuins/bluemoon/lavaland_surface_syndicate_base1_bluemoon.dmm
_maps/RandomRuins/SpaceRuins/BlueMoon/defcon2.dmm
_maps/RandomRuins/SpaceRuins/BlueMoon/defcon3.dmm
_maps/RandomRuins/SpaceRuins/BlueMoon/defcon4.dmm
_maps/RandomRuins/SpaceRuins/BlueMoon/defcon5.dmm
_maps/RandomRuins/SpaceRuins/listeningstation.dmm
code/game/area/areas/ruins/lavaland.dm
code/game/area/areas/ruins/space.dm

1) У станции прослушки появилась зона с душем
2) У таркона появилась зона душа
3) Фикс криво поставленной зоны на ДС-1
Дополнение и упрощение жизни для гостролей и багфиксы

Добитие гостролей с душами и фикс корявого маппинга (моего)

---

_maps/map_files/MetaStation/MetaStation.dmm

1) Убраны лишние трубы (без начала и конца)
2) Пофикшены чуток кривые куски мусорных труб
3) Мусорная труба в сжигателе теперь выкидывает вещи в космос, а не на солнечные панели
4) Убрано большинство мест где трубы проходят в стенах или в окнах
Уменьшение странностей карты у упрощение взаимодействие с мусорной системой

Ещё один ремап мусорных труб на Мете

---

modular_bluemoon/fluffs/code/donator.dm
modular_bluemoon/fluffs/code/mask.dm

Давно хотел чтобы у меня как на арке была пиздатая бумажная маска, а не то уёбище что перед волосами.

Добавление в мой лодаут paper mask, НО! которая прячется за прической.

---

modular_sand/code/modules/mob/emote.dm

1) звук дублировался - теперь нет
Багфиксы

Фикс двойного стона при *moan

---

_maps/RandomRuins/SpaceRuins/BlueMoon/forgotten_ship.dmm
_maps/RandomRuins/SpaceRuins/BlueMoon/sol_ship.dmm

1) Турели чуток лучше расставлены, сколько некоторые вообще были в камне
2) Часть космоса вокруг заменена на "около станции" just in case чтобы реже спавнились структуры друг в друге
Фиксы карты

forgotten/sol фикс туррелей и немного космоса вокруг

---

_maps/map_files/BoxStation/BoxStation.dmm

1) камера была в воздухе
2) лампа была на двери
3) альены спавнились в стене
фиксы карты

Пара багфиксов бокса

---

_maps/map_files/BoxStation/BoxStation.dmm

Перепланировка бокс парка чтобы он был красивым
Неразрушаемый пол заменён на дерево и траву
Добавлена вентиляция в парк
Мусорки заменены на мусорные баки с мусоропроводом
Фикс карты и украшательства

Ремап Бокс парк

---

code/game/objects/structures/beds_chairs/chair.dm

теперь на stool'e можно сидеть, я не понимаю почему такое делать было нельзя.
Я считаю это хуйней.

Серьёзно, почему я не могу застегнуться на чертовоме stool'e

---

_maps/map_files/BoxStation/BoxStation.dmm

1) Комната отбытия расширена чтобы вмещать в себя достаточно космонавтиков
2) Добавлено больше игровых автоматов
3) Дизайн переделан под стандарты меты
4) Добавлен мусорный бак в целью увеличения валидных мест для выброса мусора
5) Выход в космос "огорождены" стенкой во избежания выхода в космос из-за пролага со стоны игрока
6) А ещё меж делом общий факс вытащен из под стекла куратора, а в игровую добавлен автомат с кофе
Ремап и улучшение игры

Ремап эвака бокса

---

code/modules/mob/living/carbon/carbon_defense.dm

Проведя за кодом около недели и одного марафона кодинга, я смог сделать что сделал, так ещё и смог самостоятельно укоротить свой говнокод.
Вульп можно за хвосты дергать. (Остальных хвостатых тоже)
файл большой, так что... 
https://discord.com/channels/875735187449847830/1053678815714484384/1330076250122752042

Дергать за хвостик.

---

_maps/map_files/BoxStation/BoxStation.dmm

1) Кулл рум венты убраны с парка бокса
Мапфиксы

Хот фикс атмоса парка бокса

---

_maps/map_files/BoxStation/BoxStation.dmm

1) Эскейп под офицерский на боксе перенесён подальше от окон парка
2) Добавлен вентилятор в дверь около офицерского пода
3) В парке статуе ~~прикручен хуй~~ прикручена к полу
4) Удалены хелперы автоматического закрытия дверей и пода брига и выхода в космос около парка (они работают только если дверь напротив двери стоит)
Мапфиксы и улучшение игры

Фиксы парка бокса (ещё одни)

---

code/modules/cargo/bounties/medical.dm
code/modules/cargo/bounty.dm

1) Баунти на кровь можно выполнить
2) Теперь баунти на кровь в обязательной программе карго
3) Кровь это топливо
Багфиксы

Фикс невозможности выполнить баунти на кровь

---

_maps/RandomRuins/SpaceRuins/BlueMoon/space_syndicate_base.dmm

1) декаль лишний был в стене
мапфикс

ДС-2 фикс стены

---

modular_bluemoon/olgachan/blackmesafromnova/code/mobs/snark.dm
modular_bluemoon/olgachan/blackmesafromnova/code/structures.dm

Изменения были протестированы на локальном сервере
Изменения готовы к тест мерджу 
Изменения не были портированы с других проектов.
Даёт возможность поднять дружелюбного снарка + внёс новые ключ карты для гейта
Ну.. Типа.. Снарк был не закончен... И у людей там траблы с ключ картами были (не понятно какие нужны для открытия двери)

дополнительные ключ карты плюс возможность подобрать снарка

---

code/modules/reagents/chemistry/machinery/reagentgrinder.dm

1) Атака на харме предметом всегда работает (до этого открытая панель блендера делала тот неуничтожимым предметами (тоесть зомби не могли его уничтожить (да баррикады из блендеров))
2) В блендер ничего нельзя запихать или заменить банку когда блендер работает
Багфиксы, фиксы абузов (даже которых никто ещё не использовал) и улучшение ответной реакции игры на действия

Блендер и фиксы для него

---

code/modules/reagents/chemistry/machinery/reagentgrinder.dm
modular_bluemoon/code/datums/ruins/maint.dm

1) Когда чистил код забыл удалить у блендера вытаскивание при рабочем состоянии
2) Когда проверял код забыл убрать у сломанной перемычки техов 300 вес относительно других
Ой

Блендер, Теха и моя тупость

---

modular_bluemoon/kovac_shitcode/code/sprite_update.dm

СИЛВЕР БЛЯТЬ

---

modular_citadel/code/modules/clothing/suits/suits.dm

1) Красный плащ (одежда без брони и тд) можно повесить и на шею
Флафф вещь без брони, никому не навредит, но позволить делать СтИлЬ

Красный плащ можно повесить и на шею

---

_maps/map_files/BoxStation/BoxStation.dmm

1) Офис Блющилда переехал на место вакантного офиса А
2) вакантный офис А переехал в сброс мусора
3) сброс мусора переехал вглубь  техов
4) Театр переехал на место офиса детектива и склада с инструментами
5) склад с инструментами переехал в теха между новым офисом блющилда и раздевалкой
6) офис детектива переехал на место офиса блющилда
7) зона стройки переехало на строе место театра
8) зона входа карго немного переделано и уменьшена рубка сб для увеличения места на выдаче
Освежение карты и подготовка карты к перемапу мостика целиковому

Переставление офисов, комнаты для сброса мусора и театра на боксе

---

_maps/RandomZLevels/away_mission/spacebattle.dmm
_maps/RandomZLevels/away_mission/undergroundoutpost45.dmm

Что-бы не втыкали
(Убрал саблю из гейтов которая де факто должна быть только у капитана)

Убираем сабельки гейтерам

---

modular_sand/code/datums/interactions/interaction_datums/lewd/cursed/bite.dm

1) Куси доводят до оргазма жертву, а не кусающего
2) в дополнение теперь от куся похоти прибавляется в 2 раза меньше только если жертва не мазохист
Фиксы странностей механа (кусают жертву, стонет жертва, а кончает кусающий)

Куси доводят до оргазма жертву, а не кусающего

---

code/game/objects/items/stacks/sheets/sheet_types.dm
code/game/objects/structures/crates_lockers/crates.dm
code/game/objects/structures/tables_racks.dm
code/game/turfs/simulated/reebe_void.dm
code/game/turfs/turf.dm

1) Дотянут механ закидывания ящиков на стеллаж для ящиков с Джуси Муна
2) Изменены все комментарии джуси на наши (комментарии должны быть только апстримов и наши, а то аутизм так на каждое изменение делать свой "а мот это из такого-то форка")
3) Добавлено создание наборов создания стеллажа для ящиков за 10 железа
Багфиксы и работоспособный механ
(левый обычный - справа дебаг версия)

Фикс стеллажа для ящиков

---

_maps/map_files/MetaStation/MetaStation.dmm

Она вела не в мусор, а в комнату кма (какая ирония)
Мапфикс

Фикс мета-стейшен мусорки в карго

---

modular_bluemoon/fluffs/code/donator.dm
modular_bluemoon/oni3288/code/catcrin_stuff.dm

catcrin_ckeys_add

---

_maps/map_files/BoxStation/BoxStation.dmm

1) Переделан сервис бокса + дормы
Красиво и освежение игры на боксе

Ремап сервиса бокса

---

modular_bluemoon/code/datums/components/demoraliser.dm

Микрофикс настроения InteQ
*виляет ушками*
Проёбан \n, из-за чего в настроении писалось например:
"Да здравствует Адмирал Браун! Я недавно попила."
А не
"Да здравствует Адмирал Браун!"
"Я недавно попила."
Всем похуй

Проёбан \n

---

modular_splurt/code/game/objects/items/lewd_items/shibola.dm

[BLUEMOON] Шибари бола и бондажная веревка несовместимы в динамик

---

modular_bluemoon/fluffs/code/donator.dm

1) Добавил 1 человеку в лодаут 1 вещь
2) если он её будет ради боёвки юзать - выкручивайте хвост на 360 градусов и забирайте ко всем чертям

Сикей в донатерский лодаут

---

_maps/RandomRuins/SpaceRuins/BlueMoon/forgotten_ship.dmm
code/game/objects/items/storage/belt.dm
modular_bluemoon/SmiLeY/hecu/icons/inteq_cards.dm
modular_bluemoon/SmiLeY/inteq_ghostrole/forgottenship.dm
modular_splurt/code/game/objects/structures/ghost_role_spawners.dm

Добавлена ролька Инженера космоInteQ, который умеет в проводку, имеет инструментики и сварочные очки, а то глазкам больно приваривать эмиттер, чтоб элитку убитб.
Чутка лора захотелось и специализации, хз + делать нехрен на работе.

Инженер Space InteQ

---

code/modules/client/preferences.dm

Фикс поля Set Custom Species Lore по багрепорту.

[BLUEMOON] Set Custom Species Lore Fix

---

boxstation.dm

1) рандомный файл - копия файла форса карты бокстейшена завалялся в корневой папке билда
чистка кода

удаление случайного файла (не моего) из корневой папки билда

---

modular_bluemoon/Gardelin0/code/interactions/stuffed_movement.dm
modular_bluemoon/Gardelin0/code/items/lewd_items/dildo_custom.dm

Устранение багов в коде плагов и прочего, восстановление утерянного функционала. Тестмерж на несколько дней.

[BLUEMOON] Toys fix

---

code/modules/arousal/arousal.dm

Устранил передачу лишних реагентов из лишних мест в процессе ерп. Рекомендуется тестовый морж на несколько дней.

[BLUEMOON] Lewd reagents transfer fix

---

modular_bluemoon/fluffs/code/donator.dm
modular_bluemoon/oni3288/code/catcrin_stuff.dm

Вписал пару сикеев в шмотки, по хуйне.

ckeys_into_my_staff

---

modular_bluemoon/fluffs/code/melee.dm
modular_bluemoon/krashly/code/uplink/uplink_items.dm

Закинул в аплинк модкит на то, чтобы делать из косы/меча - десворд и есворд. https://discord.com/channels/875735187449847830/1214898953275834418/1362383449570410507
Почему модкитом.
Потому что в ином случае сохраняются звуки и эффекты плазмы от косы и плазма меча. Модкит просто делает из Плазма меча - энергомеч и из косы - десворд.

energy_de_swords_modkit

---

modular_bluemoon/code/game/machinery/robo_liquid_generator.dm
modular_bluemoon/code/modules/reagents/chemistry/reagents/other_reagents.dm

Кровь работает через жопу, так что нужно накидать костылей, иначе кровь получается не такая, как нужно.
Попросили.

Фикс генератора жидкостей для робо

---

code/modules/mob/living/carbon/carbon_update_icons.dm
code/modules/mob/living/carbon/human/human_update_icons.dm

Устраняет появление чужих маркингов на телах персонажей. Обязательный тестовый морж на неделю.

[BLUEMOON] Fix unwanted markings appearance

---

_maps/map_files/MetaStation/MetaStation.dmm

Улучшил бригмедскую на мете сделав её человеческой

---

modular_sand/code/game/objects/items/fleshlight.dm

Этот билд возведен на костях легаси говнокода со сплюртов, и под ними будет он погребён...

[BLUEMOON] Fix portal pants fluid transfer

---

code/modules/research/experimentor.dm

1) небольшая награда за изучение странных предметов в эксперементоре
Награда за науку наукой

Очки за изучение странных обьектов (реликвий)

---

code/modules/research/experimentor.dm

Я действительно считаю, что добавить 5000 за артефакт хорошая цена, ведь это НЕВОЗОБНОВЛЯЕММЫЙ и редкий ресурс который придётся ещё найти, чем сидение в ТраблПК по КД с 3750 очками

Повышение очков за странные объекты

---

_maps/map_files/BoxStation/BoxStation.dmm

Расставил настольные звоночки на стойках отделов.

[BLUEMOON] Настольные звоночки для Бокса

---

modular_bluemoon/code/modules/client/loadout/uniform.dm
modular_bluemoon/code/modules/vending/kinkmate.dm

Добавлен латексный джампсьют его half версия в кинкомат.
[Запрос](https://discord.com/channels/875735187449847830/1366839370577084577) в предложке.
Эта униформа была в кинкоматах до нашего обновления с категориями-списками.
Не нужно.

Латексный костюм в кинкоматах

---

_maps/map_files/MetaStation/MetaStation.dmm

часть мест на станции имело пол без воздуха в перемешку с полом с воздухом.
фикс бесоёбства атмоса в начале раунда

Мета, фикс перемешивания пола с воздухом и без

---

_maps/map_files/Mining/Lavaland.dmm
_maps/map_files/bluemoon_maps/icemoonstation.dmm
code/modules/atmospherics/machinery/components/trinary_devices/filter.dm

1) какой-то гений поставил фильтрам в рбмк на айс муне (а потом и идя следом на интердюну) вместо нормальной переменной лист (фильтр не воспринимает листы и у него взрывается жопа)
2) небольшой ремап сломанной проводки на интердюне
багфикс

ФИКС КРИТИЧЕСКОГО БАГА ВЫЗЫВАЮЩЕГО ВЫЛЕТ СЕРВЕРА

---

code/game/objects/structures/ghost_role_spawners.dm
code/modules/awaymissions/corpse.dm
modular_splurt/code/game/objects/structures/ghost_role_spawners.dm

[BLUEMOON] Фикс выдачи языков для гост ролей

---

modular_bluemoon/code/modules/clothing/under/miscellaneous.dm

Устранена проблема отображения ленточки на персах с кривыми ногами.

[BLUEMOON] Gift ribbon fix

---

modular_bluemoon/code/game/objects/items/summon_chalk.dm

1) Призываемый если должен телепортироваться в свёрнутую комнату отеля (которая сворачивается когда в ней никого нет) вместо этого не телепортируется и ему даётся сообщение с причиной
2) Призываемый во время отказа может дать ответ с причиной отказа.
Багфикс и фича

Да ещё больше фиксов призываемых

---

modular_bluemoon/fluffs/code/donator.dm
modular_bluemoon/fluffs/code/guns.dm

Убить бы того кто сделал отдельно протолатскую версию лазера
Добавил и протолатную версию лазера

Это просто прикол.

---

modular_sand/code/game/turfs/simulated/floor/plating.dm

Подтираю за сплюртами. Желателен тестмерж.

[BLUEMOON] Фикс разбирания пола в космос

---

code/game/machinery/limbgrower.dm
modular_bluemoon/Gardelin0/code/interactions/stuffed_movement.dm
modular_bluemoon/Gardelin0/code/items/lewd_items/magic_wand.dm
modular_sand/code/game/objects/items/fleshlight.dm
modular_splurt/code/game/objects/items/lewd_items/chastity_hypno/chastity_hypno_magazine.dm
modular_splurt/code/game/objects/items/lewd_items/genital_equipment/chastity/metal_chastity_cage.dm

- Фикс багов
- Меньше спама от пробок
- Микрофичи

[BLUEMOON] Lewd tweaks

---

modular_sand/code/modules/jobs/job_types/_job_alt_titles.dm
modular_splurt/code/modules/jobs/job_types/_job_alt_titles.dm

Удаляю дубликаты, возвращаю утерянное.

[BLUEMOON] Фикс названий профессий

---

modular_citadel/code/modules/reagents/chemistry/reagents/astrogen.dm

Исправлена ошибка невозможности вернуться в собственное тело. Одержимость другим призраком НЕ была протестирована (нет возможности), но вероятность проблем мала.

[BLUEMOON] Astrogen fix

---

code/modules/language/language_holder.dm
code/modules/mob/living/simple_animal/friendly/drone/_drone.dm
modular_bluemoon/code/_onclick/hud/drones.dm
tgstation.dme

Добавил кнопочку языков на экране для дрончиков. Дрончики больше не говорят на общем языке. НО я оставил возможность понимать общий язык (не говорить).

[BLUEMOON] Drone languages tweaks

---

code/modules/arousal/arousal.dm
modular_bluemoon/code/modules/lewd_structures/milking_machine.dm
modular_splurt/code/modules/arousal/arousal.dm

Фикс+адаптация milking machine. Даже спиздить нормально не можем, все приходится доделывать самому.
Тестмерж.

[BLUEMOON] Fix milking machine

---

code/modules/client/preferences.dm

фикс рантайма из-за которого нельзя было изменить персонажа
багфикс

Ладно выскочило, фикс тавров и их членов

---

_maps/RandomRuins/SpaceRuins/BlueMoon/forgotten_ship.dmm

Ремапп гостроли интеков с новыми приколами 
Полезно потому-что новое. Засуньте в тестмердж и зацените 
В маппдифбот

ремап гостроли интекю от cniperdodo

---

code/game/objects/structures/crates_lockers/closets/cardboardbox.dm
modular_bluemoon/code/modules/clothing/neck/_neck.dm
modular_splurt/code/game/machinery/self_actualization_device.dm
modular_splurt/code/game/objects/items/lewd_items/genital_equipment/chastity/metal_chastity_cage.dm

- Актуализатор восстанавливает знание языков.
- Нормальный звук взаимодействия с картонной коробкой.
- Расстановка проебанных SIGNAL_HANDLERов

[BLUEMOON] Актуализатор и микрофиксы

---

modular_bluemoon/code/game/objects/structures/statues.dm

Добавил разбор блока для статуй, что бы его можно было распилить сваркой. Ну и все остальное заодно тоже, повороты на ALT и т.д.

carving block QOL

---

modular_bluemoon/code/game/objects/structures/beds_chairs/bed.dm

Стоит 4, а разбирается на 2 металла. Фиксим.

Giant bed deconstruct 2 -> 4 metal

---

_maps/map_files/bluemoon_maps/icemoonstation.dmm

1) кнопка в карго была внутри окна
2) внешнее окно стойки карго было за доступом
3) в баре не хватало света
4) на кухне юзался пол без воздуха
мапфиксы

Ещё пачка фиксов айсмуна

---

modular_sand/code/datums/interactions/interaction_datums/interaction_definitions.dm

Поглаживания через панельку теперь дают бафф к муду, плюс квирк поглаживаний (Тактилофилия) теперь тоже работает через панельку. Плюс текст слегка перевел.

headpat slut panel updt

---

modular_bluemoon/code/game/objects/structures/extinguisher.dm
tgstation.dme

При установке руками extinguisher cabinet, отсутствовал спрайт. Фиксим

extinguisher cabinet sprite fix

---

modular_citadel/code/modules/custom_loadout/custom_items.dm

Убираю точку с платья.
"fitted = FEMALE_UNIFORM_TOP" фиксит любые аналогичные проблемы.

[BLUEMOON] Divine robes fix

---

code/modules/mob/living/carbon/life.dm
modular_bluemoon/code/datums/interactions/interaction_datums/lewd/tail.dm
modular_bluemoon/code/modules/mob/living/carbon/human/damage_procs.dm
tgstation.dme

Прирост возбуждения от квирка на удушения будет возникать при любом получении урона удушением, а не только при особых атмосферных условиях.

[BLUEMOON] Фикс квирка на удушайки

---

modular_bluemoon/code/modules/reagents/chemistry/reagents/other_reagents.dm

У мяты прозрачный цвет реагента. Фиксим на зеленый

catnip color fix

---

code/modules/ruins/spaceruin_code/hilbertshotel.dm

1) Фикс, что последующие заходяие в бесконечный номер отеля появлялись не там где нужно, а на стандартной точке спавна в отеле
фикс бага

Фикс, что последующие заходящие в бесконечный номер отеля появлялись не там

---

code/modules/mob/living/emote.dm
modular_bluemoon/SmiLeY/code/serverside/emote_panel.dm
modular_bluemoon/code/modules/mob/living/emote.dm

Эмоут (полезный пока, только хуманам), который оставляет только тихий смех, как у остальных антропоморфов.
Хочется тихо смеяться, а не ржать как лошадь, когда это не нужно.

soft laugh add

---

modular_sand/code/datums/components/interaction_menu_granter.dm
tgui/packages/tgui/interfaces/MobInteraction/InfoSection.tsx

Догадался до одной нереально полезной и удобной кнопки в панельке, до которой не догадались сплюрты, какой же я охуенный. Какой именно - не скажу, пусть будет хоть какая-то интрига, посмотрите сами)

[BLUEMOON] Удобная кнопка в панельке

---

code/modules/mob/living/emote.dm
modular_bluemoon/code/modules/mob/emotes.dm
modular_citadel/code/modules/mob/cit_emotes.dm
modular_splurt/code/modules/mob/living/emotes.dm

Затронуты модули ТГ, цитадели, сплурта и наш.
Мы должны или сидеть с полным переводом этого куска игры, или с полностью оригинальными эмоутами. Также добавлены некоторые фиксы и дополнение смысла.
Не думаю, что нужно.

Переводы эмоутов

---

modular_bluemoon/code/modules/mob/emotes.dm
modular_splurt/code/modules/mob/living/emotes.dm

С указанием пожеланий и критикой. Посмотрим.
Работа над ошибками
*Жалобно мяучит

Шлифовка переводов эмоутов

---

code/modules/cargo/expressconsole.dm

ей не прописали интерфейс экспресс консоли
багфиксы

Фикс экспресс консоли

---

code/modules/mob/living/carbon/human/examine.dm

и нужно-же им ещё доебаться что у людей показываются только положительные квирки
фикс

Фикс того, что госты видели не все квирки

---

_maps/map_files/BoxStation/BoxStation.dmm
_maps/shuttles/cargo_box.dmm

переделано целиком карго, стилёво мощно и бла-бла-бла
ну и чуток подправлены декали на карго шаттле, один из декалей нормально выглядит только при маппинге
да я та ещё мудилка и делаю ещё левые штуки
в рнд на конце ксенобиологии добавлена курилка проходная через техи
теха между медом рнд и инженеркой переработаны
а ещё поправлен окончательно мусоропровод по всей станции
ну и чуток расширена зона около инженерки забирая под себя часть техов (которые там очень мерзко стояли
обновление карты и украшательства

Фулл ремап карго на боксе

---

_maps/map_files/SmolStation/SmolStation.dmm

у маячков шатллов не был прописан айдишник и шатллы не могли летать
фикс

SmolStation фикс шатллов рнд и пермабрига

---

modular_splurt/code/modules/awaymissions/mission_code/AGRComplex.dm

Из минусов - игрокам в любом случае нужно будет RNGшить в ботанике в поиске эмпаверед цинка - так что Т6 будут более распростроннёными - но всё так же НЕ гарантироваными

Добавил возмонжость изучать клоковские детали - те что падают с культа в динамик и есть в космосе/некрополисе в еденичном экземлпяре

---

_maps/RandomRuins/SpaceRuins/BlueMoon/abductor_crushed.dmm
_maps/templates/apartment_train.dmm

Хот фикс моей тупости

---

modular_bluemoon/code/game/objects/items/plushes.dm

Фикс незначительного бага с игрушками, который не был выявлен на локалке. Изъятие из контейнера изначально считается как на открытом турфе, поэтому одна из игрушек могла исчезнуть.

plushes fix

---

_maps/map_files/MetaStation/MetaStation.dmm
_maps/map_files/generic/CentCom.dmm
modular_splurt/_maps/RandomRuins/SpaceRuins/spacehotelbluemoon.dmm

1) сфера инфинити дорм в гост кафе перенесена ко входу
2) в ботанику гост кафе добавлен манипулятор генов
3) в отель добавлен манипулятор генов
4) на Мете 3 двери в рнд получили общий доступ (к протолату в основе)
упрощение жизни экспедиторам на Мете
украшательства, чтобы часто используемая штука (инфинити дорма) не стояла в углу как никому не нужная

Пачка небольших мап эдитов

---

code/modules/vore/eating/living.dm

QOL. Если в радиусе sniff или lick есть только одна цель, то радиальное меню не появиться, а сразу выберется цель.

vore qol sniff and lick

---

code/modules/reagents/reagent_dispenser.dm
modular_bluemoon/code/modules/reagents/reagent_dispenser.dm

Обновил пивную кегу по запросу. Теперь она будет трястись когда с ней играют. Взрываться не с шансом 100%.
У Антропоморфов 10%
В харме + 10% = 20% (Собакам +30% = 40%)
Макакам сверху еще 10% на взрыв
Дворфы пивные мастера, у них всегда 0% подорваться и особые реплики.
Остальные расы не взрываются, кроме антро и макак

beerkeg updt

---

code/game/objects/items/stacks/sheets/sheet_types.dm
modular_bluemoon/code/modules/lewd_structures/bdsm_furniture.dm
modular_bluemoon/code/modules/lewd_structures/shibari_stand.dm
modular_bluemoon/code/modules/vending/kinkmate.dm

- Добавил БДСМ кровать в кинкмат и билд менюшку, сама кровать была уже в коде
- Добавил X stand в кинкмат, уже был в коде
- Включил возможность крутить стенд шибари (А точнее куклу в нем), ибо странно, что было запрещено, т.к. это удобно, кукла в стенде всегда на нижнем слое и нельзя встать у нее "за спиной", а так просто ее можно повернуть

bdsm bed and X stand

---

code/modules/reagents/chemistry/recipes/pyrotechnics.dm

1) максимум реакции емп 300 (чтобы не ебашили 900-ти юнитовые банки с емп на 128 турфов радиусом
2) добавлен алюминий по примеру тг
баланс

Добавляем в ЕМП алюминий и ограничиваем взрыв до 300 юнитов

---

modular_bluemoon/fluffs/code/donator.dm

- [+ ] Изменения были проверены на локальном сервере
- [+ ] Этот пулл-реквест готов к тест-мерджу.
1. Человеку понравилось парочка вещичек из моего личного лодаута, попросился и он их получил. Мне не жалко =)
2. Так-же он получает в свой личный лодаут две вещички, которые нельзя изначально получить из обычного лодаута раундстартом.
- А именно: "powder ganger jacket" и "black and red hooded cloak" (для Тешарей), которые не обладают никакой защитой и/или преимуществом.
Не требуется.

[Bluemoon|Loadout] Adding items to loadout. + Adding CKeys.

---

code/modules/cargo/blackmarket/blackmarket_telepad.dm
modular_splurt/code/modules/cargo/blackmarket/weapons.dm

Починил сломанные заказы, которые отоброжались не коретно, ускорил ЛБТМС на Т4 деталях - раньше он требовал 4 минуты на разгон, теперь 2, совсем каплю изменил шансы спавны смешного и так же каплю этого смешного удешевил. 
Я ВЕРЮ ЧТО РЕВОЛЮЦИЯ КОГДА НИБУДЬ ПОЯВИТСЯ НА БМЕ

Улучшил чёрный рынок

---

code/modules/food_and_drinks/recipes/drinks_recipes.dm

Часть напитков не показывалась в картридже BOOZE, пофикшено.
Проверено на локалке

drink recipes fix

---

_maps/map_files/bluemoon_maps/icemoonstation.dmm

1) все камеры на айсмуне просмотрены чтобы не было повторов (на то чтобы камеры были с нужным тэгом гарантий не даю)
2) добавлено требование по доступу в оружейку
3) добавлена допросная
мапфиксы

Пачка фиксов на айсмун

---

modular_splurt/code/modules/toys/cards.dm

Альт-клик по колоде карт позволет выбирать сразу группу искомых карт, позволяя быстро доставать из колоды не только джокеров.

[BLUEMOON] Find cards in deck

---

modular_bluemoon/code/game/objects/items/dice.dm
modular_bluemoon/code/modules/vending/games.dm
tgstation.dme

В вендомат с игрушками добавлен отдельный мешок с классическими д6 кубиками.

[BLUEMOON] d6 dice set

---

_maps/festivestation.json
_maps/map_files/FestiveBall/FestiveStation.dmm
code/game/area/areas/edina.dm
modular_citadel/code/modules/vectorcrafts/vectorcraft.dm
modular_citadel/code/modules/vectorcrafts/vectorvariants.dm

Постепенное исправление обнаруженных проблем и багов карты, до чего только дотянутся руки. QoL обновления. Актуальная информация будет выкладываться в дискорде в тематической предложке с таким же именем.
Тестмерж до месяца.

[BLUEMOON] Festive fix

---

code/game/objects/items/storage/belt.dm

Фикс вместимости бандольера
https://discord.com/channels/875735187449847830/1390803327998234655/1390803327998234655

bandolier fix

---

modular_bluemoon/fluffs/code/donator.dm

Простое добавление сикея к персональным шмоткам. Ничего особого.

[BM|Loadout-Personal] Adding ckeys.

---

modular_bluemoon/fluffs/code/donator.dm

Надо было с маленькой буквы писать... А кто знал? Я не знал

donate ckey fix

---

code/modules/projectiles/gun.dm

Добавлена... Возможность стрелять по яйцам из дробовика (только баллистика) 💀
Если урон от выстрела превысит 20 (т.е. если вы стреляете боевыми) то balls сделают 💥
Сделано по аналогии с самоубийством.
Трейт мазохиста заставляет кончать от этого...
Условия использования: 
- Интент Синий/желтый
- У обоих преф на ЕРП, у обоих преф на harm действия
- Если вы стреляете не по себе, то у цели должен быть преф нонкона.
Во всем виноват https://discord.com/channels/875735187449847830/875757279230701628/1398916628590104606

balls shooting

---

code/modules/food_and_drinks/drinks/drinks.dm
code/modules/reagents/reagent_containers/glass.dm
code/modules/reagents/reagent_containers/spray.dm
modular_bluemoon/code/modules/reagents/reagent_containers.dm

Прочие контейнеры реагентов (помимо бикеров, стаканов) теперь дозволяется нагревать с помощью зажигалки, спичек и т.п., например таблетки или шприцы. Теперь реагенты внутри будут нагреваться при нахождении внутри этих и прочих контейнеров реагентов. 
Это не должно вредить механу игры, потому что аналогичный результат добивается бросанием контейнеров в открытый огонь или нагреванием в микроволновке, теперь это можно делать и с помощью подручных нагревательных штук.

[BLUEMOON] Heat reagent containers

---

_maps/RandomZLevels/away_mission/ihategordon.dmm
code/controllers/subsystem/processing/quirks.dm
modular_bluemoon/code/modules/awaymissions/blackmesa/mesa_ghost_spawners.dm
modular_bluemoon/code/modules/awaymissions/blackmesa/weapons/mesa_guns.dm

Пошаманил слегка с картами и аутфитами
Куалити оф лайф или как там его. Надо короче

Фиксы лодаутов и карт гост ролей мезы

---

modular_bluemoon/code/modules/mob/living/simple_animal/tentacles/tentacles.dm
modular_sand/code/datums/interactions/lewd_definitions.dm
modular_splurt/code/modules/mob/femclaw.dm
modular_splurt/code/modules/mob/living/simple_animal/hostile/deathclaw/funclaw.dm
modular_splurt/code/modules/mob/living/simple_animal/hostile/werewolves/funwolf.dm

1. Фанклавы и прочие lewd монстры (тентакли, вервульфы и т.д.) теперь не будут даже пытаться "атаковать" персонажей с неподходящими префами, вместо этого, сразу нападая на подходящих персонажей. Написана одна проверка в общем проке, остальные вырезаны за ненадобностью
2. Стоны фанклава, заменены на его рычание (раньше дублировались обычные стоны + фанклавские)
3. Симпл мобам и прочим у кого нету клиентских префов, минимальный шанс стона повышен до 30%
4. Переведены фразы "окончания" у фанклава
5. Переведены фразы "You moan" и прочие в стонах
6. Пофикшен баг, что фанклав и от фанклава нельзя было кончить
т.к. у нас стоит спавн только мирных фанклавов, а проверка на префы была уже при атаке, было комично наблюдать, как моб бежит в персонажа, а потом стоит и ничего не …

Funclaw updt

---

_maps/map_files/BoxStation/BoxStation.dmm
_maps/map_files/Deltastation/DeltaStation2.dmm
_maps/map_files/LambdaStation/lambda.dmm
_maps/map_files/MetaStation/MetaStation.dmm
_maps/map_files/PubbyStation/PubbyStation.dmm
_maps/map_files/bluemoon_maps/icemoonstation.dmm
_maps/map_files/layenia/layeniastation.dmm
modular_bluemoon/code/modules/pedalgen/PedalGen.dm

Добавляю по возможности на большинство карт педалевый генератор, чаще всего в пермабриг, качалку и инженерку.

[BLUEMOON] Pedal Generator mapping

---

code/game/machinery/lightswitch.dm
code/game/objects/items/stacks/sheets/sheet_types.dm

Выключатели света теперь крафтятся из листов металла и разбираются отверткой.

[BLUEMOON] Craftable light switch

---

code/datums/components/storage/concrete/pockets.dm
code/game/objects/structures/flora.dm

https://discord.com/channels/875735187449847830/1388664326398808115
Возможность прятать малые предметы в кустах, крутое. 

Предметы в кустиках

---

code/game/machinery/doors/poddoor.dm
code/game/machinery/doors/shutters.dm

Подсасывание обновлений створчатых дверей с новотг.

[BLUEMOON] Pod doors update

---

modular_splurt/code/game/objects/items/lewd_items/genital_equipment/chastity/chastity_cage.dm
modular_splurt/code/game/objects/items/lewd_items/genital_equipment/chastity/metal_chastity_cage.dm

Переписал старый кривой код, наложения оверлеев клетки. Сделал универсальные проки и пофиксил наложение. Старое все вырезал. Дополнительно, теперь оверлеи корректно работают с функцией показа органов всегда.

cage overlay fix

---

modular_bluemoon/code/datums/traits/neutral/criminal_quirk.dm

Исправление повторной выдачи квирка нарушителя закона после актуализации персонажа

---

modular_bluemoon/SmiLeY/code/nanosuit/nanosuit.dm
modular_splurt/code/modules/mob/living/simple_animal/hostile/deathclaw/funclaw.dm

Теперь фанклавы не безобидные болванчики и будут защищаться
- При нанесении урона фанклаву, вы попадаете в его личный список врагов.
- Если фанклав видит личного врага, он бросит свои дела (даже если уже рейпает кого-то) и побежит за личным врагом
- Если личного врага можно рейпать, фанклав изобьет его до полусмерти (40% ХП +-) и будет рейпать. Если его нельзя насиловать, то он просто его прикончит.
- Всех кто не является личным врагом и кого нельзя насиловать, фанклав дальше будет игнорировать _(опять, же если вы не ударите его)_
Проверено на локалке, но **надо в ТЕСТМЕРЖ**

funclaw agro updt

---

code/__HELPERS/areas.dm
code/modules/movespeed/modifiers/status_effects.dm
code/modules/research/xenobiology/crossbreeding/_status_effects.dm
code/modules/research/xenobiology/crossbreeding/consuming.dm

- Починил бс печеньки.
- Радиус действия светло-розовых и масляных печенек расширен до двух тайлов. 
- Эффект масляных печенек усилен и теперь реально заметен.

[BLUEMOON] Slime cookies update

---

code/game/objects/items/devices/flashlight.dm
modular_bluemoon/code/game/objects/items/deviant_permits.dm
modular_bluemoon/code/modules/client/loadout/__donator.dm

Добавляет тёмно-фонарик для донатеров с пермитом на него.
:cl:
add: Тёмнофонарик для донатеров
/:cl:

Микро-патч 1.0.1

---

code/game/objects/items.dm
code/game/objects/items/dualsaber.dm
code/game/objects/items/melee/misc.dm
modular_bluemoon/kovac_shitcode/code/modules/guns/weapons.dm

Чиню отображение статов парирования и блокирования на некоторых оружиях.

[BLUEMOON] Block and parry stats fix

---

modular_bluemoon/code/game/objects/structures/ghost_role_spawners.dm

Благодаря стараниям и тестам Hero998 нашли косяк в проверке на режим. Вот теперь точно все правильно работать будет

if() issue fix

---

code/game/objects/items/storage/bags.dm
modular_bluemoon/code/modules/research/designs/bioaegis_designs.dm
modular_bluemoon/code/modules/research/machinery/protolathe.dm
modular_bluemoon/code/modules/research/techweb/nodes/medical_nodes.dm
modular_bluemoon/code/modules/surgery/organs/bioaegis_other.dm
modular_bluemoon/code/modules/surgery/organs/heart.dm
modular_bluemoon/code/modules/surgery/organs/liver.dm
modular_bluemoon/code/modules/surgery/organs/lungs.dm

Патчи для первой части обновления, фиксики.
I was sent to the Cum Zone and now I can't go back to my normal life. Help
I was singing "Welcome to the Cum Zone" because it's funny, but my universe took it literally and I was sent to the Cum Zone. It's a universe where all matter is cum. Even atoms don't exist here. Cum in itself is the simplest and fundamental form of matter. The only living beings are anime girls made of cum.
This world is very strange. I'm just trying to live my life normally, and do the normal stuff like traveling through worm holes and eating antimatter, but this universe's laws of physics make it so I keep falling into hentai anime situations all the time. It's tiresome. First I'm flying and I happen to bump right into a girl's boobs. Next I ask my boss for a raise, …

[Biological Ascension micro-patch]If you are happy and you know it - clap your hands!

---

code/__DEFINES/misc.dm

Сделал слой гениталий выше слоя частей тавров (некоторых).
Проверено на локалке, выглядит корректно, протыкал с десяток тел тавров
Функции под одеждой/под бельем у части тел тавров не работали корректно, ибо визуально ничего не было видно.

genitals layer fix

---

modular_sand/code/datums/interactions/_interaction.dm

sessil_rape

---

_maps/map_files/FestiveBall/FestiveStation.dmm
modular_citadel/code/modules/vectorcrafts/vectorcraft.dm

- Крупный фикс атмоса. Полный реворк атмосферного отдела.
- Фикс камер.
- Фикс некоторых доступов и кнопок для гаражей.
- Фикс ПДА сообщений и смеса телекомов.
- Микрофикс труб карго.
- Инженерам в отдел добавлено некоторое нехватающее оборудование.
- Отключены бусты у машинок, так как я уже достаточно упростил управление машинками, и если раньше без него некоторые типы автомобилей не могли даже сдвинуться с места, то теперь в нем нет прямой необходимости и его наличие лишает смысла переключение передач.
- Прочий QoL маппинг.

[BLUEMOON] Festive fix 3

---

code/game/objects/items/storage/briefcase.dm
code/modules/jobs/job_types/medbay/psychologist.dm

По запросу публики - все пилюли что раньше срали в рюкзак и вместе с лодаутом - теперь идут в кейсе что раньше спавнился вместе с психологом в его руках

Кейс с пилюлями для психолога

---

code/modules/reagents/chemistry/reagents/drink_reagents.dm

Теперь Молоко лечит скелетов от берн урона
https://discord.com/channels/875735187449847830/1425199460111356156

skelet milk change
